### ISSUE TITLE
Out-of-Position Unknown Trash Discharge

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#119]
Proposal:
If the next player doesn't have the (unclued) Third Finessed Position, then we can do an **Out-of-Position Unknown Trash Discharge** on the two-seat-away player.

_For example: kopen has a known purple 1 on slot 1, an unknown blue card on slot 2, and a known green 1 on slot 3. IAMJEFF clues blue to Livia in turn 6. kopen knows that he can't blind-play his First Finessed Position (on slot 4) to demonstrate an UTD occurred, and he sees Razvogor has a playable card on his Third Finessed Position, then he knows IAMJEFF is doing an OOP UTD instead, and plays the purple 1 normally. Razvogor knows that if he does nothing, Livia would misplay the blue 1 as a blue 2, then he blind-play his slot 3 as an Out-of-Position Unknown Trash Discharge, and a red 1 is successfully played. Now Livia marks her slot 1 blue card as a Trash._

![Out-of-Position Unknown Trash Discharge](https://user-images.githubusercontent.com/50160641/69497373-163d4500-0f17-11ea-8225-add5211c848d.png)

**Comment by iamwhoiamhahaha** [comment]
We might apply this to 5CE as an Out-of-Position 5 Color Ejection, if the next player doesn't have (unclued) Second Finessed Position.

**Comment by iamwhoiamhahaha** [comment]
If it is approved, I will propose some other crazier ideas based on OOP UTD. 😋

**Comment by Zamiell** [comment]
seems okay as long as it is not in reverse, e.g. alice clues donald 5ce, bob discards, cathy plays slot 2

i think this kind of thing will probably work in the existing conventions without any explicit pre-coordination. thus, it might not make sense to document it unless you are already doing this move in a semi-routine fashion

**Comment by iamwhoiamhahaha** [comment]
### Out-of-Position Unknown Trash Discharge Finesse

Bob's hand: (unclue) blue 2, (unclue) red 2, (known) green 2, (known) some 5
Cathy's hand: (slot 3) blue 3

- All 1's played on the stacks.
- Alice clues yellow to Donald, touching a yellow 1.
- Bob doesn't have the _Third Finessed Position_ to demonstrate the _Unknown Trash Discharge_ occurred and realizes Alice is performing an _Out-of-Position Unknown Trash Discharge_. However, Cathy doesn't have a playable card on her _Third Finessed Position_ (the blue 3 is one-away from being playable), if Bob does nothing, Cathy would misplay the blue 3, then he knows he must have blue 2 to fulfill the _Discharge_ and blind-plays his _Finessed Position_ as an **_Out-of-Position Unknown Trash Discharge Finesse_**, and blue 2 is successfully played.
- Cathy blind-plays slot 3 as a (known) blue 3 and Donald marks his yellow card as trash.

**Comment by iamwhoiamhahaha** [comment]
### Unknown Trash Double Ejection

Bob's hand: (unclue) blue 2, (unclue) red 2, (known) green 2, (known) some 5
Cathy's hand: (slot 2) red 3, (slot 3) blue 4

- All 1's played on the stacks.
- Alice clues yellow to Donald, touching a yellow 1.
- Bob doesn't have the _Third Finessed Position_ to demonstrate the _Unknown Trash Discharge_ occurred and realizes Alice is performing an _Out-of-Position Unknown Trash Discharge_. However, Cathy doesn't have a playable card on her _Third Finessed Position_ (the blue 4 is two-away from being playable), if Bob does nothing, Cathy would misplay the blue 4. Unfortunately, Bob cannot blind-play his _Finessed Position_ as an _Out-of-Position Unknown Trash Discharge Finesse_, or Cathy would still misplay the blue 4. Then he blind-plays his _Second Finessed Position_ to "tell" Cathy not playing her slot 3, and a red 2 is successfully played.
- Cathy now knows her _Third Finessed Position_ is not playable (either two-away or trash), however, if she does nothing, Donald would treat this move as a _5 Color Ejection_ since Bob blind-plays his slot 2. Then she blind-plays her _Second Finessed Position_ as an _**Unknown Trash Double Ejection**_, and a red 3 is successfully played.
- Donald marks his yellow card as trash.

*Cathy's slot 2 is either playable or one-away, while slot 3 is either two-away or trash.

**Comment by Zamiell** [comment]
those last 2 seem extremely rare / niche

**Comment by iamwhoiamhahaha** [comment]
yeah but might be useful imo 😝

**Comment by Zamiell** [comment]
**Out-of-Position Unknown Trash Discharge** (by Jeff)

* Normally, players are only allowed to perform a *Discharge* on the very next player (similar to a *Bluff*).
* However, if a *Unknown Trash Discharge* is performed, and the very next player does not have a *Third Finesse Position*, then they cannot demonstrate to the team that the clued card is trash.
* In this situation, the *Discharge* is on the next player with a *Third Finesse Position*:
  * The player being passed over knows that the next player will blind-play, so they can either discard or give an unrelated clue.
  * After that, the next player should blind-play their card immediately to demonstrate what is going on.
* For example, in a 4-player game:
  * All of the 1's are played on the stacks.
  * Bob's hand is as follows, from left to right: g1, r(5), b(5), g(5)
  * Alice clues red to Donald, touching a red 1 on his slot 1 as a *Play Clue*.
  * Bob knows that Donald will think that this red card is red 2. But if a card blind-plays from *Finesse Position*, then Bob will think that the card is red 3. Thus, this must be an *Unknown Trash Discharge*.
  * Bob does not have a *Third Finesse Position*. (He only has one unclued card in his hand.)
  * Thus, Bob knows that this is an *Out-of-Position Unknown Trash Discharge* on Cathy.
  * Bob clues number 5 to Alice as a *5 Save*.
  * Cathy blind-plays her *Third Finesse Position* and it successfully plays as red 2.
  * Donald knows that since Cathy blind-played her *Third Finesse Position* card, this must be an *Unknown Trash Discharge* and that his red card is red 1. Donald discards the red 1.
