### ISSUE TITLE
Playing to the Out

### ISSUE THREAD

**Issue by alercah** [Zamiell/hanabi-conventions#126]
- We always play with the object being to get a perfect score, not just to score highly.
- As the end game approaches, due to the distribution of cards in people's hands and the plays that still need to be made, there may be limited possibilities of cards remaining in the deck that will give the team a perfect score ("outs").
- Players should therefore play under the assumption that it is possible to achieve a perfect score, even if it risks losing the game.
- Example:
  - There is one card remaining in the deck, and no clues. All cards have been played except for yellow 4 and 5. The team has already made two strikes.
  - Bob has one card in hand clued yellow. From the *Good Touch Principle*, Bob knows it is the yellow 4 or yellow 5, but there is no contextual information available that might tell them apart. Bob also has negative yellow on the rest of his hand. Thus, he knows that the other yellow card must be the last card in the deck.
  - Bob deduces that the only way to achieve a perfect score is for him to play the yellow 4, draw the yellow 5, and then play it on the last turn.
  - On the other hand, discarding so that another player could clue the 4 would guarantee a respectable score of 24/25.
  - Nonetheless, even though he does not know that his yellow card is the 4, he plays it in order to preserve the chance at victory.

**Comment by Zamiell** [comment]
> We always play with the object being to get a perfect score, not just to score highly.

this is not true. often times all players will have a max score in the current variant, and in that situation they are playing to get the highest score possible
other times, players will play a very difficult variant with the intention that they will not get a perfect score but just intend to get as high of a score as possible without striking out.
thus, players need to coordinate before the game starts in order to determine what strategies will be used and this probably doesn't need to be in the reference document
