### ISSUE TITLE
Gentleman Discard Ejection

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#129]
### Proposal: Gentleman Discard Ejection

If someone does a _Gentleman Discard_, but the gentlemaned card is not on someone else's _Finessed Position_, and there's also a trash on his _Finessed Position_. Then the next player should blind-play his _Second Finessed Position_ as a _**Gentleman Discard Ejection**_ to demonstrate the situation.

For example:

> Alice's hand: a known blue 2
> Bob's hand: a red 2 on slot 2
> Cathy's hand: a red 1 on slot 1 and a blue 2 on slot 2

- All 1's has played on the stacks.
- Alice discards her known blue 2 to "gentleman" Cathy's blue 2.
- However, Cathy has a trash on slot 1 and the real blue 2 is on slot 2, Alice discards for some reasons. Bob realizes Alice is performing a _**Gentleman Discard Ejection**_ and blind-plays his _Second Finessed Position_, and a red 2 is successfully played.
- Cathy is surprised, she realizes Bob blind-plays for some reasons, and then blind-plays her slot 2 as the blue 2. She also marks her slot 1 as trash.

**Comment by hanabirnoob** [comment]
Gentleman's Discard Discharge can work in a similar manner.

**Comment by iamwhoiamhahaha** [comment]
> Gentleman's Discard Discharge can work in a similar manner.

I've thought about that but might be too confusing

**Comment by iamwhoiamhahaha** [comment]
**Kopen:**

Re: Gentleman's Discard Ejection
Could you use that to do a layered Gentleman's through a trash card?

Presumably if trash is on finesse then yes, but how about if it's the second card?

> Stack: b1, r2, y2
> Alice: known r3
> Bob: x - b2 - x - x - x
> Cathy: y3 - kt - r3 - x
> 
> 1: Alice discards r3 as a gentleman's on Cathy's r3
> Bob does something
> Cathy plays y3 as r3
> Alice does something
> Bob ejects b2 to tell Cathy to skip a card in searching for r3
> Cathy skips kt and blind plays r3
> 

I guess the problem with this is just the amount of asynchronous information going around.  Luckily, Cathy can't do anything that would cause Bob to eject (right?)

I'm sure it would be easy to say that this extends to layered gentleman's (in the case where y3 and kt are swapped)

But also, what if Cathy and Bob's hands are swapped?  can Alice still do this move and Bob plays y3 as r3 and then Cathy ejects b2 to tell Bob to skip a card?

And a final question, does the skipped card have to be trash? Or maybe if it is still potentially playable it is a ejection and if it is trash it is a discharge?

(If someone wants to mirror this to github that would be good too)

**Comment by iamwhoiamhahaha** [comment]
kopen, i dont think it works, too confusing

**Comment by Zamiell** [comment]
that was kodo not kopen

**Comment by iamwhoiamhahaha** [comment]
Oops LOL

**Comment by iamwhoiamhahaha** [comment]
This convention is quite powerful in my opinion. Most of the time, you are praying the player, who has another copy of the card, could draw a playable card to perform a _Layered Gentleman Discard_, but it ends up with a trash. With this convention, you can still perform a "gentleman discard" even if the player draws a trash, not only protects his chop (by giving him a playable card and a known trash), but also gets a free card to play (through an ejection).

**Comment by Zamiell** [comment]
seems fine
it should be illegal to perform if the card is not on *Second Finesse Position*

**Comment by Zamiell** [comment]
you can also do it as a baton discard (but then it should never be layered)

**Comment by alercah** [comment]
Is there any reason that this shouldn't similarly apply to a *Layered Finesse* through trash as the first card?

**Comment by Zamiell** [comment]
no

**Comment by NoMercyO** [comment]
I think there is. This convention prevents gentleman's discards that require an additional fix clue on the trash in slot 1.

Obviously that is a loss of little of value, there will be almost no reason to do so.

If the gentleman a discard becomes layered however its value increases, often to the point where it is worth it with a lie/fix required.

As an analogous comparison if the card in slot 1 we're 1 away from playable it would be reasonable for an intermediate player to assume a patch is required. If the gentleman a discard were layered, they would be much more likely to assume fix clue needed.

**Comment by Zamiell** [comment]
agreed:
* if the fix clue is on a trash card, then it is a 2-for-1 on the ejected card + the layered card, which is worth it
* if the fix clue is on a N-away from playable card, then it is a 3-for-1 on the ejected card + the layered card + the fixed card

**Comment by Zamiell** [comment]
* Normally, if a player performs a *Gentleman's Discard* and the other card is **not** on *Finesse Position*, it could be several things:
  1) If the card on *Finesse Position* is itself playable right now, then it would be a *Layered Gentleman's Discard*.
  2) If the card on *Finesse Position* is exactly one-away-from-playable, then it would be a *Patch Gentleman's Discard* (and call for the next-player to blind-play their *Finesse Position* card).
  3) If the card on *Finesse Position* is two or more away from playable, or a trash card, then it is usually an emergency situation or a player is making a mistake.
* If the third option is true and it is **not** an emergency situation and the player is **not** making a mistake, then the player who is performing the weird *Gentleman's Discard* is instead intending for the next player to *Eject* as a *Gentleman Discard Ejection*. Doing so will demonstrate that the card is not on the *Finesse Position* and is instead on the *Second Finesse Position*.
* For example, in a 3-player game:
  * All 1's are played on the stacks.
  * Alice discards a known red 2 as a *Gentleman's Discard*.
  * Bob sees that Cathy has the red 2, but it is not in her *Finesse Position*. Cathy has a red 1 (trash) on *Finesse Position*, followed by a red 2.
  * Bob knows that it would be pointless for Alice to perform a *Gentleman's Discard* and then for Bob to waste a clue giving a *Fix Clue*. So, if Alice is not making a mistake, she must be trying to communicate something deeper.
  * Bob knows that if Alice wanted him to play his *Finesse Position* card, this would not work, as Cathy would interpret the situation as a *Patch Gentleman's Discard* and would go on to misplay the red 1.
  * Bob knows that this situation signals a *Gentleman's Discard Ejection*, so he blind-plays his *Second Finesse Position* card and it a blue 2 and it successfully plays.
  * Cathy knows that some kind of *Ejection* is going on, since Bob blind-played his *Second Finesse Position*. Since the previous action was a *Gentleman's Discard*, this must be a *Gentleman's Discard Ejection*, which means that Cathy's red 3 is on her *Second Finesse Position* instead of her *First Finesse Position*.
  * Cathy blind-plays the red 2.

**Comment by iamwhoiamhahaha** [comment]
Wrong text: which means that Cathy's "**_red 2_**" is on her Second Finesse Position instead of her First Finesse Position
