### ISSUE TITLE
5 Double pull example

### ISSUE THREAD

**Issue by jeep** [Zamiell/hanabi-conventions#130]
Am I missing something here?
- It is the first turn and nothing is played on the stacks.
- Alice clues number 5 to Cathy, touching a red 5 on slot 3.
- Cathy's slot 4 card is a red 1. (This was her chop card prior to the number 5 clue being given.)
- It is now Bob's turn. Bob sees that Donald has a red 2 on his slot 2 that could be Play Clued with a red color clue.
- Normally, since it is the *Early Game*, a number 5's clue to Cathy might just be a *5 Stall*. However, since Alice could have given the red *Play Clue* to Donald, 

Clearly the R2 can't be play clued by Alice since there is nothing on the stack and the 2 is not playable until the 1 which is not on finesse plays. Is that part of the example even needed, though? Since it is non-sensible to 5CM the red 1, it must be a pull, but the only way to indicate that is for Bob to play.

**Comment by Zamiell** [comment]
how about this:

* For example, in a 4-player game:
  * It is the first turn and nothing is played on the stacks.
  * Cathy's hand is as follows, from the left to right: blue 4, blue 4, red 5, red 1
  * Alice clues number 5 to Cathy, touching a red 5 on slot 3.
  * It is now Bob's turn. Bob sees that since there were other *Play Clues* for Alice to give, Cathy will interpret this as an *Early 5's Chop Move*.
  * Bob also knows that it is nonsensical to *Chop Move* a playable red 1 - Alice could have just give a red *Chop Focus Play Clue* to the red 1.
  * Thus, this must be a *5 Double Pull*, so Bob blind-plays his *Finesse Position* card. It is blue 1 and it successfully plays.
  * Cathy knows that if this was an *Early 5's Chop Move*, then Bob would not have blind-played anything. Since he blind-played his *Finesse Position* card, this must be a *5 Double Pull*. Cathy blind-plays her slot 4 card (the card to the right of the clued 5).

**Comment by jeep** [comment]
Seems better to me. The early 5 flowchart will also need to update.

**Comment by Zamiell** [comment]
that flowchart is more for beginners, i'm not sure that it should be added
