### ISSUE TITLE
Positional Double Bluff (in Null Variant)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#141]
### Positional Double Bluff (in Null Variant)

If the next player who received the positional clue cannot find a null card after blind-playing 2 playable cards, he should stop playing and the original positional clue should be treated as a _Positional Double Bluff_.

This is very useful in 2-player and I believe we can use this in 3 or more player game.

Example: The 4 clue gets the red 1 and yellow 1 as a _Positional Double Bluff_.
![positional double bluff](https://user-images.githubusercontent.com/50160641/71448957-1f703a80-277f-11ea-9be5-f6b7a40bfa78.png)

**Comment by Zamiell** [comment]
seems fine

**Comment by Zamiell** [comment]
actually this can get messy because the bluffed player will not know that a null card is gotten yet

essentially this desynchronizes the team because the player in the null layer is not guaranteed to continue blind-playing cards, they may stop to perform other clues, so the lie may not be revealed for a very long time

**Comment by Zamiell** [comment]
so this pretty strongly violates *Good Lie Principle*

**Comment by Zamiell** [comment]
ok so then sounds like we should close this for now
