### ISSUE TITLE
Pink Tempo Clue and Brown Tempo Clue

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#142]
### Pink Tempo Clue and Brown Tempo Clue
It's always a good idea to _Tempo Clue_ a pink card or a brown card, in case the player draws another blocking card. In this situation, it does not trigger the _Tempo Clue Chop Move_.

**Comment by iamwhoiamhahaha** [comment]
It also applies in Muddy Rainbow and Light Pink Variants I think.

**Comment by Zamiell** [comment]
I think that this is already the way we play actually

**Comment by iamwhoiamhahaha** [comment]
i know. just want to add this in the doc

**Comment by Zamiell** [comment]
**Pink Tempo Clues**

* If a player gives a *Tempo Clue* to a pink card, it is never a *Tempo Clue Chop Move*, even if it only gets one card played.
* This is because it is fairly valuable to get pink cards out of the hand as soon as possible in case blocking cards are drawn.

**Brown Tempo Clues**

* If a player gives a *Tempo Clue* to a brown card, it is never a *Tempo Clue Chop Move*, even if it only gets one card played.
* This is because it is fairly valuable to get brown cards out of the hand as soon as possible in case blocking cards are drawn.
