### ISSUE TITLE
Priority exception for 4's

### ISSUE THREAD

**Issue by sjdrodge** [Zamiell/hanabi-conventions#147]
Playing a 4 that leads into your own hand is almost always worse than playing a 5. So much so that adding an explicit exception to the priority rules is justified. However, I think playing a 3 into one's own hand over playing a 5 should still be left up to judgment.

**Comment by NoMercyO** [comment]
Sure. 4s suck. 
Generally speaking im on board with the assertion that general card play order should be 1 2 3 5 4, with the only exception being 5s gain exceptional priority at 0 clues. 

There is to me however a cautionary defense against this suggestion, and it unfortunately appeals to human error:  Does everyone know that Alice (x b5 r4 r5) knows her b5 is playable immediately?  

2) Ultimately the goal of priority is to establish an agreed upon order of card play, to then exploit it for gain. Thus there are 3 things to trade off:
- perfecting an actual best card play order in a vacuum
- perfecting a card play order that has more exploitable opportunities
- maintaining a priority ruleset that is globally understandable and simple enough to memorize. 

I agree that known priority bluffs should never be triggered in these edge cases because our groups understanding of all the nuance of priority is not consistent, largely due to how complex it really is.

**Comment by Zamiell** [comment]
> Does everyone know that Alice (x b5 r4 r5) knows her b5 is playable immediately?

the case where alice knows the full identity of her 5 is around 50%?
so the exception in the doc would have to be worded such that the exception only applies if the 5 is globally known blah blah.
honestly it might be better to just leave it to common sense (which is the way that it is now)

**Comment by sjdrodge** [comment]
The reason I think this exception is valuable is because playing a 5 instead of a 4 that goes into your own hand should never trigger a known priority bluff, and I've witnessed a few situations where people were afraid that it might. In two cases this actually lost a close endgame. In other words, it's demonstrably true that not having this explicit exception is inducing errors (even if you believe that it should not be).

I don't understand the objection about whether the 5 is globally known. The wording of the exception doesn't need to specify any of that. A known priority bluff attempt will not work on the next player if they are unaware that you could have played your 5. Is there some other complication that I'm missing?

**Comment by Zamiell** [comment]
if alice has a known playable red 4, an unknown red 5, and a known playable blue 5, then alice would play the blue 5.
from bob's perspective, the red 4 has priority, so he interprets this as a known priority bluff, and bombs green 5, and the game is lost

**Comment by Zamiell** [comment]
but mercy is saying that the inverse is also true. if bob thinks that the blue 5 has priority, and alice doesn't known that she has b5, she will play the red 4, then bob bombs green 5, and the game is lost.

**Comment by sjdrodge** [comment]
Bob can make that kind of mistake in all priority situations. Right now this class of error is more likely, not less likely, because the conventions "require" players to play their cards in an order which is demonstrably illogical. Right now, if a player deviates from the rules to make the correct play, odds are decent that it could cause a misunderstanding.

**Comment by Zamiell** [comment]
ok i see now, you are saying that *all* priority rules are turned off when cards are not globally known

**Comment by Zamiell** [comment]
so you want to just change "Cards that lead into the player's own hand" --> "Cards that lead into the player's own hand that are not a 4"

**Comment by sjdrodge** [comment]
Exactly.

**Comment by Zamiell** [comment]
can you submit a PR

**Comment by Zamiell** [comment]
```
### The 4's Priority Exception

* If a player has a known playable 5 and a known playable 4 that leads into their own hand, then according to the above *Priority* table, the known playable 4 would have *Priority*. However, this doesn't make much sense, since the 5 has to be played no matter what, playing the 5 gives the team a clue back, the 4 could be played by someone else, and so on.
* Thus, if a player has a known playable 5 and a known playable 4 that leads into their own hand, then the 5 is said to have *Priority*.
```
