### ISSUE TITLE
Positional Bluff Finesse (in Null)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#155]
### Positional Bluff Finesse (in Null)

- This convention only applies to the variants with Null suit. 

- Only the player who is on the _Bluff Seat_ can give this kind of clue.

- Normally, _Positional Clues_ are only allowed to "get" null cards. What if the next player blind-plays a card from the positional clue and he doesn't have a playable Null card to the right of the card he just played?

- In this situation, the _Finesse_ is still on but not on the Null suit. Instead, it is on the card which triggers the positional clue.

_Example 1:_
![Positional Bluff Finesse](https://user-images.githubusercontent.com/50160641/75253756-287e9600-581a-11ea-8266-4c0927ff3524.png)
_sankala gives a 2 clue to NoMercy. Fireheart knows it is a (rank choice) positional clue and blind-plays slot 2, and a green 1 is successfully played. NoMercy sees Fireheart blind-plays slot 2 for some reason and realizes the 2 clue must be some kind of positional clues. However, Fireheart doesn't have a playable Null card on slot 3, if he does nothing Fireheart will go on and misplay the brown 5. Then he realizes this is a _Positional Bluff Finesse_ and plays his unknown 2 as a green 2. Fireheart now knows he doesn't have a Null card on slot 3 since NoMercy plays his mystery 2 as a green 2 that used as a positional clue, and he stops looking for a Null card._

_Example 2:_
![Positional Bluff Finesse 2](https://user-images.githubusercontent.com/50160641/75254722-c32ba480-581b-11ea-8c9d-9d66d8f584c7.png)
_IAMJEFF gives a 3 clue to Zamiel. sankala sees NoMercy has a blue 2 on Finessed Position. However, if it is a blue finesse then IAMJEFF would just give a blue clue to Zamiel. sankala realizes it is a (rank choice) positional clue and blind-plays his slot 3, and a blue 1 is successfully played. However, NoMercy sees sankala doesn't have a playable Null card on slot 4, if he does nothing sankala will go on and misplay the blue 5. Then he realizes this is a _Positional Bluff Finesse_ instead. To fulfill the Finesse, NoMercy must have a blue 2 on Finessed Position or Zamiel will misplay the white 4 from slot 1, and he blind-plays his Finessed Position as a blue 2. Later, Zamiel plays the blue 3 in his turn. Back to sankala, he stops looking for a Null card since NoMercy and Zamiel play the blue 2 and 3 as a Positional Bluff Finesse._

- Notes: The problem of this convention is what if the next player sees the player who receives the clue has enough information on his card. Playing the green 2 in Example 1 probably won't stop Fireheart looking for a Null card if the green 2 is locally known from Fireheart's and NoMercy's perspective.

**Comment by iamwhoiamhahaha** [comment]
### Positional Double Bluff (in Null)

- To solve the problem mentioned above, we can just define this kind of move as a _Positional Double Bluff_, which means the next two players have to blind-play the same slot from the _Positional Clue_ and no one is promised a Null card.

**Comment by Zamiell** [comment]
>  Positional Double Bluff, which means the next two players have to blind-play the same slot

why does Cathy play the same slot and not play *Finesse Position*?

**Comment by iamwhoiamhahaha** [comment]
seems fine. bob plays the specific slot and cathy plays slot 1

**Comment by aliblong** [comment]
There's a much simpler solution to the problem you outline at the end of the original post: if Bob's blind play matches the target, the clue is resolved; Bob shouldn't look for n1. If it doesn't match, Cathy should play from slot 1. Call these "positional finesse" and "positional double bluff".

**Comment by Zamiell** [comment]
1) we would have to rename positional finesses to null finesses, which seems fine
2) yeah i guess null cards would never "match", so that wouldn't hurt anything other than layered positional finesses

**Comment by Zamiell** [comment]
actually lets keep positional finesse for null cards, since it matches positional clue

jeff come up with a new name for this

**Comment by Zamiell** [comment]
slot finesse?
ghost finesse?
shadow finesse?

**Comment by iamwhoiamhahaha** [comment]
i haven't come up with a good name. but let's talk about one problem if cathy blind-plays slot 1: should bob treat this as a patch and continue looking for null card? i know we can just define this as a sort of double bluffs

**Comment by iamwhoiamhahaha** [comment]
to distinguish a real patch (even though it seems rare), cathy should blind-play slot 2 i guess

**Comment by Zamiell** [comment]
patch finesses are almost never done, never assume a patch finesse

**Comment by iamwhoiamhahaha** [comment]
how about changing the current positional finesses as *Positionull Finesses* for null and leave the name for this proposal LOL (just kidding)

**Comment by Zamiell** [comment]
lol

**Comment by iamwhoiamhahaha** [comment]
#### Option 1
* Rename the current *Positional Finesses* as ***Null Finesses***. Since we can't perform a *Finesse* on a null card other than a *Positional Clue*, we don't need to specify them as *Positional Finesses*.
* Name my proposal as ***Positional Finesses*** and ***Positional Double Bluff***.

#### Option 2
* Rename the current *Positional Finesses* as ***Positionull Finesses***. To specify they are the *Finesses* on a null card. LOL.
* Name my proposal as ***Positional Finesses*** and ***Positional Double Bluff***.

#### Option 3
* Name my proposal as ***Slot Finesses*** and ***Slot Double Bluff***

**Comment by iamwhoiamhahaha** [comment]
i prefer option 1

**Comment by Zamiell** [comment]
do you also propose to rename positional clue to null clue? there is an asymmetry

**Comment by iamwhoiamhahaha** [comment]
hmm
why not just call them *Positional Finesses (on Null cards)* and *Positional Finesses (on non-Null cards)*

**Comment by iamwhoiamhahaha** [comment]
and option 2 looks interesting, isn't it?

**Comment by Zamiell** [comment]
> why not just call them Positional Finesses (on Null cards) and Positional Finesses (on non-Null cards)

because it is more clear to have two separate names for two separate things

**Comment by Zamiell** [comment]
option 2 is kind of dumb, lets go with option 3 for now

**Comment by Zamiell** [comment]
### The Slot Finesse 

* Normally, if a *Positional Clue* is used to get a non-null card, then the blind-playing player would continue blind-playing cards as a *Positional Layered Finesse*. For that reason, it is normally impossible to *just* get a non-null card with a *Positional Clue*.
* As a rare exception, players can perform a *Finesse* using a *Positional Clue* that has the blind-play "match" the card that was clued. If they match, then **no null cards are promised**.
* This is called a *Slot Finesse* to distinguish it from a *Positional Finesse*. In other words, *Positional Finesses* use *Positional Clues* to get null cards to blind-play into other null cards. And *Slot Finesses* use *Positional Clues* to get non-null cards to play into other non-null cards.
* For example, in a 3-player game of the "Null (6 Suits)" variant:
  * It is the first turn of the game and nothing is played on the stacks.
  * Alice clues number 2 to Cathy, touching a red 2 as a *Play Clue*.
  * Bob sees that Cathy has no other red cards in her hand, so Alice had a *Free Choice* between cluing red and cluing number 2. If Bob really had a red 1 on his *Finesse Position*, then Alice would clue red. Thus, this must be a *Rank Choice Positional Clue*.
  * Bob blind-plays his slot 2 card as a null 1. Instead, it is the red 1 and it successfully plays. Bob now knows that this must be a *Positional Layered Finesse*, so Bob marks his slot 3 card as the null 1.
  * Cathy knows that since Bob played slot 2 instead of slot 1, this must be a *Positional Clue*. However, Cathy also knows that you are only supposed to use *Positional Clues* to get null cards. So this must be a *Positional Layered Finesse* on Bob.
  * However, from Cathy's perspective, Bob has no null cards, so Alice must have been intending something else. If Cathy does nothing, then Bob will go on to misplay his slot 3 card as a null 1. Cathy knows that since a red 1 matches a number 2 clue, then this must be a *Slot Finesse*.
  * Cathy plays her 2 as a red 2 and it successfully plays.
  * Bob knows that cards clued as part of *Positional Clues* are not promised to be playable, so it was very strange that Cathy played her 2. This must mean that he does not have the null 1 after all and that Alice's clue was simply a *Null Finesse*.

### The Slot Double Bluff

* Normally, if a *Positional Clue* is used to get a non-null card, then the blind-playing player would continue blind-playing cards as a *Positional Layered Finesse*. For that reason, it is normally impossible to *just* get a non-null card with a *Positional Clue*.
* One way to get the blind-playing player to stop searching for a null card is to perform a *Slot Finesse* (see above).
* One other way to get the blind-playing player to stop searching for a null card is to force the next player after that to blind-play their *Finesse Position* card (in the exact same way as a *Pesitlent Double Bluff*). After seeing the second blind-play, the first player will know that it is impossible for them to have a layered null card.
* For example, in a 4-player game of the "Null (6 Suits)" variant:
  * All the 1's are played on the stacks.
  * Alice clues number 4 to Donald, touching a red 4 as a *Play Clue*.
  * Bob does not see anyone else have any red cards. And Bob knows that *Double Self-Finesses* are turned off in null variants, so this must be a *Positional Clue*.
  * Slot 4 is Bob's chop, so normally Bob would treat this as a *Positional Save Clue* on a null 5. However, Bob currently has a globally-known playable blue 2 in his hand on slot 1 (e.g. he is *Loaded*). That means that this is a *Loaded Play Clue* and that he has a playable null 2 on his slot 4.
  * Bob blind-plays slot 4 as null 2. It is instead a green 2 and it successfully plays. Bob now knows that this must be a *Positional Inverted Layered Finesse*, so Bob marks his slot 3 card as the null 2.
  * Cathy sees that since Bob did not play a null card, Bob will assume an *Positional Inverted Layered Finesse* and will go on to play his slot 3 on his next turn. However, Bob does not have any null cards in his hand. Alice must have intended for something else to happen.
  * Cathy knows that this must be a *Slot Double Bluff*, so she blind-plays her *Finesse Position* as any playable card. It is yellow 2 and it successfully plays.
  * Donald knows that from the sequence of events that Alice performed a *Slot Double Bluff*, so the 4 clue is to be treated as a *Positional Clue* (e.g. the 4 in his hand might be trash).
  * Bob sees that since Cathy blind-played her *Finesse Position* card for "no reason", he must not actually have the null 2 in his hand after all. Bob can reason that Alice performed a *Slot Double Bluff*.
