### ISSUE TITLE
Convention Update/Proposal: Trash Push

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#186]
So I've been looking at the doc on trash pushing and I realized that we can update it to be more efficient and clear.

For consistency sake we should have trash push ejection be changed to Unknown Trash Push Discharge.  In the trash flowchart it lists it as Unknown Trash Ejection, which we've removed from the doc for Unknown Trash Discharge.  This will let players know that the card being pushed is trash.

This leaves opens the spot for a Trash Push Ejection.  We can have it set such that if the card that is being pushed is 2 or more away from being playable it should just be an ejection.  This will let players know to actually keep the card to the left of the trash and they can put a note on it that it's some card that's 2 or more from being playable.

**Comment by sjdrodge** [comment]
Sounds like the flowchart could use an update, but the current Trash Push Ejection is not related to Unknown Trash Ejection (deprecated) or Unknown Trash Discharge. The big difference being that the clued card is already known trash without a blind-play when a Trash Push Ejection takes place.

That said, I'm okay with augmenting the Trash Push Ejection to allow the pushed card to be either trash or 2+ away from playable, as we've commonly been doing with these kinds of moves.

**Comment by sjdrodge** [comment]
It occurs to me that the proposal should probably be read as "let's trash Trash Push Ejections such that if the pushed card is trash, it's a Discharge, and if the pushed card is simply 2+ away from playable, it's an Ejection instead." I think this is a great idea, and we should definitely implement it.

**Comment by Dr-Kakashi** [comment]
> It occurs to me that the proposal should probably be read as "let's change Trash Push Ejections such that if the pushed card is trash, it's a Discharge, and if the pushed card is simply 2+ away from playable, it's an Ejection instead." I think this is a great idea, and we should definitely implement it.

That's exactly what I'm asking for as right now the answer to both is to eject.  So the player being pushed has no clue if he was pushed for trash or a 2+ away card.

**Comment by iamwhoiamhahaha** [comment]
https://docs.google.com/document/d/1vxd8ecOIRnP5HtGZ3toyTsY-w0Yldir3D5cBN241M_U/edit?ts=5d66152e#heading=h.9zcbnfec21c7

Actually I made this proposal the first time I brought out this idea, but Zamiel just didn't like it. And it turned out to be the current "Trash Push Ejection" you see in the doc.

**Comment by Zamiell** [comment]
i didn't like it because it is unlikely to be used. link a game where it is used

**Comment by Zamiell** [comment]
> This leaves opens the spot for a Trash Push Ejection.

let's be clear that searching for undefined things for the purposes of coming up with new assignments for them is an anti-goal. historically, i think a lot of issues that you and hanabirnoob have opened fall under this category. it is a misunderstanding of how this all works. we want conventions that 1) are going to be applicable to a wide variety of games, and 2) flow from actual games where you used the thing. not just because you realized that something was undefined and want to come up with a definition for it.

with that aside, i guess it is reasonable that trash pushing a trash card should get slot 3 like UTD does. that assignment is going to be easy to remember for everyone in the group. (although I have yet to see a case for this in a real game.)

however, then wouldn't it also follow a trash push that causes an ejection should be a 5 like 5CE is? i guess that isn't super-important, just pointing that out.

**Comment by Zamiell** [comment]
### Trash Push Discharge

* Normally, when known trash is touched as the focus of the clue, and the known trash is on chop, it communicates a *Trash Push*.
* However, what if the *Trash Pushed* card is trash? The other players can see that this clue must have some other purpose - it should signal an *Discharge* on the very next player.
* This move is extremely similar to the *Unknown Trash Discharge*. In UTD, the focus of the clue is promised as trash. In the *Trash Push Discharge*, the *Trash Pushed* card is promised as trash.

**Comment by Zamiell** [comment]
trash push ejection --> trash push discharge
has been changed now in the doc, so i'll be closing this issue.

new convention proposals should go into a separate issue. if you still want to add the brand-new Trash Push Ejection to the doc, then open a new issue with a link to a game where it was used (no hypotheticals), or a link to a game where it would have been optimal to use on a specific turn
