### ISSUE TITLE
Definition of Selfish

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#197]
I found a lot of people misunderstood the meaning of selfish. I believe we need the definition of "**_Selfish_**" in the doc. We can define it [here](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-selfish-finesse-a-finesse-through-your-own-hand).

**Comment by Zamiell** [comment]
selfish doesn't mean anything. it is simply a random word that i came up with to describe a finesse on a playable card that you currently have in your hand.

1) what would you define selfish as
2) how exactly do you think that people are misunderstanding what it means

**Comment by iamwhoiamhahaha** [comment]
i like this term tbh
1. selfish means the player gives a clue touching a card through their own hand (but i'm not sure if it is clear)
2. some people think `selfish = occupied`

**Comment by Zamiell** [comment]
How about this:

### The Selfish Clue

* A *Selfish Clue* is when a player:
  1) has a playable card in their hand (e.g. red 2)
  2) gives a *Play Clue* to the next connecting card (e.g. red 3)
* In almost all cases, there is no reason to give a *Selfish Clue*. Players can simply play your playable card and let someone else on the team "get" the next card. Being *Selfish* is typically associated with having bad teammwork.
* However, in rare cases, giving a *Selfish Clue* can be good.
* For example, in a 3-player game:
  * All the 1's are played on the stacks.
  * Alice has a globally-known playable red 2 in her hand.
  * Bob hand is as follows, from left to right: blue 1, red 3, red 4, red 5, blue 1
  * Both Bob and Cathy has a safe discard.
  * Alice knows that on this turn, she is expected to play the red 2, unless she has a really good clue to give.
  * Alice sees that if she plays the red 2, then Bob will probably have nothing to do, and will go on to discard the blue 1.
  * At that point, the red 5 will be on chop, and it will be difficult for the team to get all of the red cards. Specifically, someone will probably have to give a number 3 clue to Bob as a 1-for-1 on the red 3.
  * Alice sees that if she gives a red clue to Bob *right now* (e.g. before she plays the red 2), then she will be able to "lock-in" a nice 3-for-1 clue. Even though the team will lose *Tempo*, this will be incosequential because Bob has a safe discard and Cathy has a safe discard.
  * Alice clues red to Bob as a *Selfish Play Clue*.

**Comment by iamwhoiamhahaha** [comment]
seems good

**Comment by iamwhoiamhahaha** [comment]
ohh wait sorry
you are supposed to add "selfish clues can only be done with color clues"

**Comment by Zamiell** [comment]
why is that

**Comment by iamwhoiamhahaha** [comment]
ohh yeah, it can be done by a rank clue
however, *Selfish Focus Inversion* can only be done by color clue
you should probably specify that i guess

**Comment by iamwhoiamhahaha** [comment]
like call it *Selfish Color Focus Inversion*

**Comment by iamwhoiamhahaha** [comment]
or specify it in the document "SFI can only be done with color clues"

**Comment by Zamiell** [comment]
ok.

side question:
can you perform selfish color focus inversion with a color of a card that is not in your hand?

**Comment by iamwhoiamhahaha** [comment]
definitely not

**Comment by iamwhoiamhahaha** [comment]
it is not "selfish" though

**Comment by Zamiell** [comment]
lol

**Comment by Zamiell** [comment]
but thats only because you made me change the name of it

**Comment by Zamiell** [comment]
it used to be OFI, and under the name OFI, what i just said is allowed

**Comment by Zamiell** [comment]
i think you should acknowledge that that is an actual convention change rather than just a renaming

**Comment by iamwhoiamhahaha** [comment]
but actually i don't care too much about selfish color focus inversion tbh. i've never done it before. the only thing i care is the definition of selfish clues for my selfish conventions in 2-player

**Comment by iamwhoiamhahaha** [comment]
it's romain's convention, i don't want to steal his credit. if you want to add that title on me, up to you

**Comment by Zamiell** [comment]
this is funny because i didn't realize that this changed

**Comment by iamwhoiamhahaha** [comment]
the reason why i wanted to change OFI to SFI (or SCFI) is because i saw a lot of newbies use it when they were occupied and caused a lot of problems
i believe romain meant to define it as SCFI instead of OFI before the term "selfish" was invented

**Comment by Zamiell** [comment]
this can be continued in #219
