### ISSUE TITLE
Self Color Ejection & Color Double Bluff

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#205]
### Self Color Ejection

* In non-2-player games, *Self-Bluffs* with color clues are explicitly illegal. But what if the player gives a color clue touching a card(s) on their next player, and the player who receives the clue knows that the card is not playable?
* In this situation, the player who receives the clue should blind-play their *Finessed Position* as a *Color Double Bluff*.
* However, if it cannot be a *Double Bluff*, then they should look at the table to see if it can be a *Patch Finesse*. If it is possible, then they should blind-play their *Finessed Position* as a *Patch Finesse*.
* However, what if the *Patch Finesse* is also impossible? In this scenario, they should blind-play their *Second Finessed Position* as a *Self Color Ejection*.
* Note that you are also allowed to perform a *Self Color Ejection* by touching a *Chop Moved* card.
* For example, in a 4-player game:
  * Bob has a green 5 with a 5 clue on it.
  * Alice gives a green clue filling the green 5 and touches no brand-new card.
  * Bob sees that Cathy doesn't have a playable card (or a one-away card) on her *Finessed Position*, so it cannot be a *Triple Bluff*.
  * Bob also sees no other green cards on Cathy and Donald's *Finessed Position*, so it cannot be a *Patch Finesse*.
  * Bob knows that *Self Color Bluff* in a 3 or more player game is illegal. If he blind-plays his *First Finessed Position*, it delivers the wrong information to the whole team.
  * Therefore, he blind-plays his *Second Finessed Position* as a *Self Color Ejection*, and a blue 1 is successfully played.

**Comment by iamwhoiamhahaha** [comment]
### Color Double Bluff
* In non-2-player games, Self-Bluffs with color clues are explicitly illegal. But what if the player gives a color clue touching a card(s) on their next player, and the player who receives the clue knows that the card is not playable?
* If they see their next player has a playable card on their *Finessed Position*. In this situation, the player who receives the clue should blind-play their *Finessed Position* as a *Color Double Bluff* (even it touches a 5, since *Triple Bluff* is rare).
* For example, in a 3-player game:
  * No cards are played on the stacks.
  * Bob has a green 2 with a 2 clue on it.
  * Alice gives a green clue filling the green 2 and touches no brand-new card.
  * First, Bob thinks that it is a *Finesse* on the green 2. However, he doesn't see any green 1 on Cathy's hand.
  * Bob sees that Cathy has a playable red 1 on her *Finessed Position*, then blind-plays his *Finessed Position* as a *Color Double Bluff*, and a blue 1 is successfully played.
  * Now, it's Cathy's turn, she thought she has a green 1 on her *Finessed Position* before Bob blind-played. However, Bob blind-plays for some reasons, then she realizes it must be a *Patch Finesse*.
  * Cathy blind-plays her *Finessed Position*, and a red 1 is successfully played.
  * Since two unrelated blind cards have played, then Cathy realizes that it is not a *Patch Finesse* but a *Color Double Bluff*. No one has green 1.

**Comment by Zamiell** [comment]
the reason we outlaw Self-Bluffs with color clues is because it is a common mistake. if we continue to prescribe actions for *every possible mistake*, then we have no wiggle room left whenever a mistake happens.

the point of proposing conventions is that we think it will increase our overall win-rate. if we have no wiggle room left when a mistake is made, then it actually does the opposite, and decreases our total win rate, which is an anti-goal.

you could use the same argument to say that we should delete *Priority Finesses*, since playing the wrong card into *Priority* is a common mistake. however, we do *Priority Finesses* all the time, and we get an extreme positive amount of value from having the convention, so it is worth the cost.

are self color ejections worth the cost? to answer that question you have to actually demonstrate that the convention will be used in a common way. e.g. post several screenshots / replays of games where it would be:
1) the best move available
2) be super clear
3) be able to get cards that are not able to be gotten with one of our (many) existing moves

**Comment by iamwhoiamhahaha** [comment]
> the reason we outlaw Self-Bluffs with color clues is because it is a common mistake

* *Self Color Bluffs* have proven themselves to be one of the most powerful and useful conventions in 2-player.
* I don't think `it is a common mistake` is a very good reason. From my understanding, it is an illegal move because of the existence of *Patch Finesses*.
* If you agree that we should never assume a *Patch Finesse* occurs if someone gives this kind of move, like the situation as you stated [here](https://github.com/Zamiell/hanabi-conventions/issues/155#issuecomment-629917184), then I believe enabling *Self Color Bluffs* and making them legal is not a big problem in my opinion. 

> the point of proposing conventions is that we think it will increase our overall win-rate

* Statistically, *Self Color Bluffs* increase a ton of win-rate in a 2-player game. Why? They not only provide **positive** information on the clued cards but also get a blind-card. In some specific situation, you can also give a 2-for-1 clue by touching a brand-new card, which is quite efficient.
* In a 3 or more player game, we probably don't have enough context to do a 2-for-1 *Self Color Bluff*. However, giving positive information on the clued cards is still a very good reason why *Self Color Bluffs* can increase the win-rate.

> are self color ejections worth the cost?

* We can still forbid *Self Color Bluffs* in a 3 or more player game, leaving the room for *Self Color Ejections*. Ejections are advanced moves, which means we might not see a lot of mistakes in an expert-only game if we enable *Self Color Ejections*.

> to answer that question you have to actually demonstrate that the convention will be used in a common way

* I agree. I'll look for screenshots and replays to prove them.
* Actually, I've seen a lot of chance where people can setup an *Ejection* for their next player to do a *Self Color Ejection* while spectating. Unfortunately, they didn't know this move and I forgot to take the screenshots and I also don't remember the Game ID.
* In theory, I don't think I need to prove them. They are extremely powerful and useful without causing any confusion in my imagination. But I know you need a proof.

**Comment by iamwhoiamhahaha** [comment]
### Self Color Ejection Example

* swineherd gives a red clue to melwen

![self color ejection example](https://user-images.githubusercontent.com/50160641/82684493-42970b80-9c85-11ea-9279-d3b532c5a0cc.png)

https://hanabi.live/replay/176685/16

**Comment by Zamiell** [comment]
> From my understanding, it is an illegal move because of the existence of Patch Finesses.

negative. it is an illegal move because fill-in clues (in e.g. double discard situations) get interpreted as self bluffs with color, which decreases overall win rate.

subsequently, self color ejections have the exact same problem that self color bluffs do. its just defining an interpretation for a common mistake that will decrease overall win rate.

**Comment by Zamiell** [comment]
SCB in hard-variants seems fine though

**Comment by iamwhoiamhahaha** [comment]
Okay I see why SCB is illegal in 3p+ now......
Hmmmmmm, but in an expert-only game, I don't think it's a big problem, isn't it?

**Comment by Zamiell** [comment]
1) fill-in stalls are less likely in hard variants, because DDA is turned off.
2) however, fill-in stalls still happen in hard variants, because of scream discards, and situations where players are locked.
3) in a situation where a player thinks they are screamed discarded for (but they are not actually scream discarded for), SCB as a convention has the potential to lose the game.
4) in a situation where a player thinks they are locked (but they are not actually locked), SCB as a convention has the potential to lose the game.

**Comment by Zamiell** [comment]
if anything, we would only enable it in hard-variants, and only if expert players are playing.
however, notice that the two screenshots you posted are for easy-variants,

**Comment by iamwhoiamhahaha** [comment]
> in a situation where a player thinks they are screamed discarded for (but they are not actually scream discarded for), SCB as a convention has the potential to lose the game.

it doesn't matter whether SCB is a convention. the team might still lose the game for treating it as a finesse. (Bob won't bomb but Cathy would definitely bomb)

> in a situation where a player thinks they are locked (but they are not actually locked), SCB as a convention has the potential to lose the game.

same situation

**Comment by iamwhoiamhahaha** [comment]
> if anything, we would only enable it in hard-variants, and only if expert players are playing

yeah, how about accept it and see what happens. i believe it is a good convention to make it legal

**Comment by Zamiell** [comment]
i will accept it if you can post 2 screenshots that show it is optimal in the given gamestate (no hypotheticals)

**Comment by iamwhoiamhahaha** [comment]
you mean SCB or SCE?

**Comment by Zamiell** [comment]
whatever you think is more optimal

**Comment by iamwhoiamhahaha** [comment]
### Self Color Ejection Examples (in hard variants)

* Example 1:
  * hakha3 gives black clue to kimbifille
  * https://hanabi.live/replay/191466/25

![SCE example](https://user-images.githubusercontent.com/50160641/83702243-b3073a80-a63e-11ea-960f-223bb3e49543.png)

**Comment by iamwhoiamhahaha** [comment]
### Self Color Double Bluff Examples (in hard variants)

* Example 1:
  * Livia gives a yellow clue to IAMJEFF
  * https://hanabi.live/replay/95616/21

![SCDB example 1](https://user-images.githubusercontent.com/50160641/83706935-53fbf280-a64b-11ea-9693-1dcaefebf090.png)

**Comment by Zamiell** [comment]
what about the ejection?

**Comment by iamwhoiamhahaha** [comment]
don't you see the examples above?

**Comment by Zamiell** [comment]
oh i missed that

**Comment by iamwhoiamhahaha** [comment]
i added the explanation

**Comment by aliblong** [comment]
In the 176685/16 example, 3 to melwen seems like it works, and is better than a hypothetical colour self ejection. Then the other example requires "imagining", when the goal was to show how common the situation is, lol.

I'm not in principle opposed to either of these. In fact, what "common" mistake class does it conflict with? Brand new players randomly cluing cards? Wrong DDA/stall? Forgetting to clue a playable one round and therefore putting wrong context on it? I think all of these usually get misplays from other players, so it doesn't seem like a big deal to transfer the misplay to the receiving player's own hand.

However, the gain does seem pretty marginal. The only really compelling example I see out of all the ones you posted is the brown 4 one, because it's a genuine 3-for-1. I'm going to stay neutral here.

**Comment by iamwhoiamhahaha** [comment]
> the gain does seem pretty marginal.

Yeah i agree. Most of the SCE (or SCB in 2p) are 1-for-1. However, they give positive information on the clued cards (or *Chop Moved* card as a 2-for-1), which seems good. Basically, it's an ejection + a prompt.

Take my screenshots as examples:

#### Example 95607/5
* The only clue that Livia can give is blue to Zamiel if we don't have SCE as a 1-for-1 clue. It also gives negative blue information on the other cards.
* If SCE is available, it not only gets the b1 but also tempos the r2, which seems better.

#### Example 95648/25
* The only clue that Zamiel can give is black to IAMJEFF if we don't have SCE as a 1-for-1 clue. It also gives negative black information on the other cards.
* If SCE is available, it not only gets the k3 but also pre-saves the y3, which seems much better.

**Comment by Zamiell** [comment]
sounds like libster is neutral
i am somewhere between neutral to against
thus, this is on hold until someone else likes it enough to shift consensus

**Comment by Zamiell** [comment]
since no-one else has commented since may 8th, i think this is stale enough to close

**Comment by pianoblook** [comment]
This is cool stuff

- Almost all of the SDB examples are exactly the same as what Zam has references as a _Double Ignition_ ('randomly' recluing a nonplayable when all teammembers can see there was something more useful to do)

- Example 1 (Brown to schark) is unique because it actually touches a _new_ card. As Jeff has stated, imo in expert play it should still work and is just a super cool edgecase

**Comment by florian-5f3759df** [comment]
It's stale, but we had another one in a real game, so if you're still collecting examples for if this should reopen: https://hanab.live/replay/258449/13.

I think after patch finesses are more restricted / deleted, self color bluffs should be re-examined and hopefully added, since they used to interfere with patch interpretation.

**Comment by Zamiell** [comment]
florian, i dont know if thats a great example to post here.

in that replay, it just looks like a *Known 5 Double Bluff*, because florian can see that there are no possible double bluff targets for kim to use.
if kim had a 4 or 5 to use in kakashi's hand, then she would just use that.

i think that this thread is more about a SCB that calls for 1 blind play

**Comment by Zamiell** [comment]
this is approved now as of #353

**Comment by iamwhoiamhahaha** [comment]
glad to see it
