### ISSUE TITLE
Pink Promise with a 5's Chop Move

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#215]
* This convention only applies to variants with a pink suit.
* When a player performs a *5's Chop Move*, it is clearly a type of *Save Clue*. But the focus of the clue is unclear.
* We define the focus of the clue to be the 5 that is one-away from the chop.
* Thus, when a player knows for sure that a number 5 clue indicates a *5's Chop Move*, the *Pink Promise* convention only applies to the 5 that is one-away from the chop.

**Comment by fpvandoorn** [comment]
@Zamiell Suppose Alice's hand is `b1 r5 i4 i5`, and assume that `b1` is trash and everything else is useful but not playable. 

* Pink is likely to get a misplay on `i5`, and even if it is a valid fake save, it doesn't touch `r5`.
* 5 is not allowed, because by this convention it promises that slot 4 is `i5`.

**Comment by fpvandoorn** [comment]
@iamwhoiamhahaha

**Comment by fpvandoorn** [comment]
If the convention only applies if the 5 that is 1-away from chop is non-pink, this convention might be okay.

**Comment by Zamiell** [comment]
are your cards from left to right or right to left

**Comment by fpvandoorn** [comment]
`i5` is chop (as always). It needs to be saved, and this convention disables all allowed save clues.

**Comment by iamwhoiamhahaha** [comment]
I don't understand your question

**Comment by Zamiell** [comment]
i dont understand the hypothetical. why would it be illegal to give a number 5 clue (as the *5 Save* convention) to an i5 that is on chop

**Comment by fpvandoorn** [comment]
Because this convention (as I read it) then states indicates that slot 3 is a 5.

Maybe I misunderstand this convention.

This part is confusing: *when a player knows for sure that a number 5 clue indicates a 5's Chop Move, the Pink Promise convention only applies to the 5 that is one-away from the chop.*

In what cases do you know for sure that a number 5 clue indicates a 5's Chop Move?

Please give a situation where this convention applies.

**Comment by Zamiell** [comment]
Example 1:

* It is a 3-player game.
* The variant is "Pink (6 Suits)".
* It is the middle of the game and no 5's are yet playable.
* Alice clues number 5 to Bob, touching one 5 on slot 4.
* Bob knows that this is a *5's Chop Move*, and marks his slot 5 card as being chop moved.
* Bob knows that the clue is focused on slot 4 (since that was the only card that was touched). *Pink Promise* applies to this card, so he marks it as a 5.
* Later on in the game, another rank clue "fills in" his slot 4 card to be a pink card. From *Pink Promise*, Bob knows that it must be exactly the pink 5.

Example 2:

* It is a 3-player game.
* The variant is "Pink (6 Suits)".
* It is the middle of the game and no 5's are yet playable.
* Alice clues number 5 to Bob, touching two 5's on slot 1 and slot 4.
* Bob knows that this is a *5's Chop Move*, and marks his slot 5 card as being chop moved.
* Bob knows that the clue is either focused on slot 1 or slot 4.
* Because of the convention in this thread, Bob knows that since this clue caused him to *Chop Move*, it is focused on slot 4.
* Thus, *Pink Promise* applies to this card, so he marks slot 4 as a 5.
* Later on in the game, another rank clue "fills in" his slot 4 card to be a pink card. From *Pink Promise*, Bob knows that it must be exactly the pink 5.

**Comment by fpvandoorn** [comment]
Oh, I completely misunderstood the convention. This is a good convention (and mostly just clarifies what people expect).

I thought it dealt with a situation where the slot 5 card (in an unclued hand in a 3p game) was pink, and was also touched by this "5 chop move".

Disregard my comments, this convention is good (and sorry for assuming things).
