### ISSUE TITLE
Convention Proposal: Unnecessary Trash Push Finesse

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#220]
![2020-05-18_1707](https://user-images.githubusercontent.com/48993588/82270623-3c71f980-992a-11ea-8a2d-b53f22cf845b.png)

Was wondering what you guys think about this.  Normally with an unnecessary trash push the immediate next player must blind play.  However, if the trash push is a "true finesse" shall it be treated as such?

**Comment by Zamiell** [comment]
no, because the cards don't match. that doesn't follow from first principles.
its basically the same reason that we don't allow 5 pull finesses in reverse

**Comment by Dr-Kakashi** [comment]
Thank you for the quick response

**Comment by padiwik** [comment]
This is basically the idea behind #185 but less confusing, right?

**Comment by Zamiell** [comment]
its actually disanalogous to 5 pulls. in your screenshot, you are doing a reverse UTP, not a forward one, which makes this a weird example.

**Comment by Dr-Kakashi** [comment]
yea......it's forward zam.....so I was thinking it's a "true finesse" as this is undefined currently.

**Comment by Zamiell** [comment]
the example in the doc is forward, the example in your screenshot is reverse

**Comment by Dr-Kakashi** [comment]
Oh I see like if sin and padi switched seats then padi is doing the blind play

**Comment by Zamiell** [comment]
right

**Comment by Zamiell** [comment]
in that hypothetical, sin is bob. and i guess from first principles bob assumes finesse over bluff, so he would defer to donald. this is quite weird though. lets leave this issue open for a while and see if anyone else does this

**Comment by Zamiell** [comment]
and if you do it in another game, post the screenshot

**Comment by iamwhoiamhahaha** [comment]
seems fine to me

**Comment by Dr-Kakashi** [comment]
![2020-05-20_2331](https://user-images.githubusercontent.com/48993588/82530393-08493500-9af2-11ea-8808-875ec721cdd3.png)

Similar situation...if Dr_Kakashi does 3 and y2 plays, should the team let alphabeta play the y3?

**Comment by Zamiell** [comment]
how is 3 a trash push

**Comment by sjdrodge** [comment]
Regarding the initial question, my initial proposal for the Unnecessary Trash Push convention was precisely for cases like this:
`Proposal: if you trash push a card that could have been cleanly clued, it has weak form trash finesse implications
e.g. if you trash push an r4 that could have been cleanly clued, it also gets r5 on someone's finesse position`
I ended up simplifying the convention in order to increase its chances of being accepted because Zamiel's initial reaction was: `the average skill level of the group seems to have gone down in the past 3 months, so i dont think the group is at a level where that kind of thing would be particularly useful`
Given that the convention has now been around for a while and is well-established as being useful, I would definitely support its usage being expanded back to the original intention. i.e. both bluff and finesse variants being allowed.

**Comment by iamwhoiamhahaha** [comment]
* Zamiel, I guess Kakashi meant:
  * If the r3 has negative green information, Kakashi clues 3 to TheDaniMan.
  * TheDaniMan knows that the 3 is not playable, then he blind-plays *Finessed Position* as a *Self-Finesse*, and a yellow 2 is successfully played.
  * Lilliana sees that TheDaniMan blind-played the yellow 2 for some reasons, if he does nothing, TheDaniMan is going to bomb the red 3 as a yellow 3. By conventions, he is supposed to blind-play 
  *Finessed Position* as a *Pestilent Double Bluff*.
  * However, Lilliana also sees that alphabeta has a yellow 3 on his *Finessed Position*. By this proposal, he should "pass" his *Pestilent Double Bluff* to alphabeta as a ***Pestilent Finesse***.
* I guess it should be called *Pestilent Finesse*. This convention is fancy but it kills the *Pestilent Double Bluff*. In my opinion, we should leave the room for *Pestilent Double Bluff*, and Kyle can *Finesse/Bluff* the yellow 3 on his turn in this situaion, which is the better line than *Pestilent Finesse*.

**Comment by sjdrodge** [comment]
@iamwhoiamhahaha The prescription here if you follow the conventions to the letter is not actually for a _Pestilent Double Bluff_, but instead a _Heal Clue_ getting the y3 in some way (another bluff being a valid way to do this).

**Comment by Zamiell** [comment]
yeah jeff i dont think you understand what a disease bluff is

**Comment by Zamiell** [comment]
and looks like kakashi doesn't as well

**Comment by iamwhoiamhahaha** [comment]
ohh i heard of that convention but never used it. okay i see

**Comment by Dr-Kakashi** [comment]
> how is 3 a trash push

it is not, but the r3 is "diseased" and requires a heal clue and/or blind play

**Comment by Dr-Kakashi** [comment]
Looks like you guys have commented on the r3 being y3.  Yes the team should get alphabeta's y3.  I didn't mean to clutter this thread, should we just delete that post?

**Comment by Dr-Kakashi** [comment]
Wait, I don't think this should be closed.  Probably should add this as a principle on if it's a true finesse it should be treated as such right Zam?

**Comment by Zamiell** [comment]
i guess

**Comment by Zamiell** [comment]
### The Unnecessary Trash Push (Finesse Form)

* First, see the *[Unnecessary Trash Push](#unnecessary-trash-push)* section.
* Normally, the *Unnecessary Trash Push* calls for the very next player to blind-play an unrelated card, similar to a *Bluff*.
* However, if the very next player can see that it could be a *Finesse*, then they should prefer that interpretation. This is similar to how the next player should always prefer a *Finesse* interpretation over a *Bluff* interpretation.
* For example, in a 4-player game:
  * All of the 2's are played on the stacks.
  * Alice clues number 1 to Cathy, touching a single 1 on her chop. Since all of the 1's are already played, it is globally known that this must be some kind of *Trash Push*.
  * Bob sees that the pushed card is a red 3. Cathy has no other red cards in her hand, so Alice could have just clued red to Cathy instead of doing a complicated *Trash Push*.
  * Thus, Bob knows that this is an *Unnecessary Trash Push*. Normally, Bob would immediately blind-play his *Finesse Position* card. However, Bob also sees that Donald has a red 4 in his *Finesse Position*. Since *Finesses* take precedence over *Bluffs*, Bob knows that he should let Donald be the one to blind-play from the "unnecessaryness".
  * Bob discards.
  * Cathy knows that this must be a *Trash Push*. Cathy blind-plays her slot 3 card. It is red 3 instead and it successfully plays.
  * Similar to Bob, Donald also sees that the *Trash Push* was unnecessary. Since Bob did not blind-play anything, this must be an *Unnecessary Trash Push Finesse*. Donald blind-plays his *Finesse Position* as red 4 and it successfully plays.

**Comment by fpvandoorn** [comment]
I'm not a fan on this convention. 

* Suppose Alice performs a `Unnecessary Trash Push (Finesse Form)` by cluing Bob
* Bob plays `r2` into Alice's clue
* Cathy sees that Donald has `r3` in slot 1, so doesn't respond. Instead, Cathy gives a play or save clue to Bob
* Donald plays `r3` from slot 1.

Now Bob *cannot* know whether Donald blind-played into Alice's clue or into Cathy's clue, and this will not be automatically clarified to Bob later. This is unlike most conventions we have currently.

@Dr-Kakashi
