### ISSUE TITLE
Convention Proposal: 1 away 5CE

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#223]
![2020-05-22_0059_(new_type_of_ce)](https://user-images.githubusercontent.com/48993588/82646107-d8b92c00-9bc8-11ea-8b59-2db46ba3d69a.png)

I think I've figured a new type of 5CE.  It's a 1 away 5CE.  Normally a 5CE is done when a 5 is newly touched and the next player has 2+ blind plays.

Btw this is an Up & Down game, so this is a 1CE, but I'm sure it follows into other 5CE situations

In this example, Dr_Kakashi gives greens to duck touching a g1.
Alphabeta can see that only g3 needs to be played. 
If alphabeta plays slot 1, then duck will write g2 on g1.  
Additionally, if alphabeta plays g3 from slot 1, then Duckmammal will bomb g1 as g2.
Therefore alphabeta must play slot 2, to tell duck it is g1.

**Comment by Zamiell** [comment]
i mean it works here but you failed to mention that this convention isn't generic because ooo takes precedence in almost all cases.
the screenshot is an exception because a) it is only a 3 player game and b) it is done in this specific order (e.g. if it is done in reverse then kakashi has time to give the ooo fix)

**Comment by Dr-Kakashi** [comment]
Sounds good.  Thanks!
