### ISSUE TITLE
Proposal: Expand Finesse-position-exception to apply to all clues

### ISSUE THREAD

**Issue by NoMercyO** [Zamiell/hanabi-conventions#225]
[original title: Proposal: Expand Finesse-position-exception to apply to all clues]

As per title. FPE shouldnt only apply to deciding if you are considering to 5-stall in the early game. 

All other caveats still apply: (beware if finesse card could be in you own hand. only consider one FPE, so two finesse position cards are not ignore-able (maybe they should be if they are in a row?)

**Comment by NoMercyO** [comment]
*crickets*. 

Maybe justified. 

Currently as written the situation is as follows: 
"when you are evaluating if you are in a valid 5 stall situation, and there is a 5 clue to give, you may consider 1 finesse position, which is not immediately after you, as an exception and the 5 stall is valid."

Proposal:
"when you evaluating your actions, you may always ignore 1 finesse position, which is not immediately after you, as an exception and act accordingly."
Result: in the early game if there are no more clues except one finesse position, you may discard if there are no 5 stalls to give. No change for higher severity situations.

Devils advocate: I think based on Florrat's version of ending the early game this is already covered. Based on document it is not.

Final conclusion:
- Document should better cover florrat's evalution of endgame in advnaced section.
- I will continue to feel comfortable ending the early game with FPE applied whether or not there is a 5 stall. 

If you feel this is reckless and we should hard enforce giving the crappy play clue on the finesse position then speak up! :)

**Comment by Zamiell** [comment]
I think we should hard enforce giving the crappy play clue on the finesse position because it has less of a chance to be misinterpreted (e.g. as a fake chop move, causing a discard of an **actual** critical card and losing the game)

**Comment by Zamiell** [comment]
in fact, that is a good argument to delete FPE entirely

**Comment by Zamiell** [comment]
the extra efficiency of a single finesse is **not needed** in non-hard variants.
in hard variants, FPE doesn't apply, because 5 stalls don't apply.
thus, the only way that FPE would be a good idea is it we lost a non-hard variant by needing exactly 1 extra single clue of efficiency in order to get a maximum score. seems incredibly unlikely

**Comment by aliblong** [comment]
> the extra efficiency of a single finesse is not needed in non-hard variants.

That misses a big part of the reason for doing finesses in easy games, which is touching useful cards.

**Comment by Zamiell** [comment]
useful cards can still be touched in the same way, just as a normal *Play Clue*.

however, you are right that we miss out on 3 bluffs, etc.

**Comment by Zamiell** [comment]
another point against FPE is that it can introduce more asymmetry into early game (because people don't know whether or not they have a finesse position playable when the 5 clue is given, and then they have to retroactively reason about it, which can lead to mistakes)

now, on libster's point, regardless of whether we miss out on 3 bluffs or not, i think getting rid of FPE would be a nice way to reduce overall complexity, without costing us too much. as a general point of recommendation, i think we should capitalize on any low-cost complexity reduction that comes up

**Comment by fpvandoorn** [comment]
So we're arguing over the following situation?
* it's the early game
* there is no unclued 5 (ignoring 5s to your right)
* there is only 1 unclued playable card, which is in finesse position, not in the next player's hand and cannot be gotten by you by a finesse.

Yes, I think you should be allowed to discard then. (in my early game notes you are required to give the play clue if it's a 2-for-1 or better, which I'm also fine with).

**Comment by Zamiell** [comment]
um, i think we are arguing over something else.
consider the following example:

* It is the *Early Game*.
* Alice clues number 5 to Bob, touching a 5 that is one-away from chop. This is either a *5 Stall* or a *5's Chop Move*.
* Bob sees that Cathy has a playable card on her *Finesse Position*, and maybe Alice just wanted to do a *5 Stall* and pass so that he can *Finesse* it.
* If the "FPE" convention exists, then Bob takes this interpretation, and does not *Chop Move*.
* If the "FPE" convention does not exist, then Bob would always treat this as a *Chop Move*, because Alice is expected to clue Cathy's hand.
* In either situation, Bob will now "get" the card in Cathy's hand, either with a normal *Play Clue* or with a *Finesse*.

I'm proposing that we **delete FPE and that it is always a *Chop Move* on Bob**.
For reference, FPE does not apply in "hard" variants and only applies in "easy" variants.

* Cons: Less flexibility in the *Early Game* to stall when you need to.
* Cons: Overall reduced efficiency in "easy" variants, because we can potentially miss out on *Finesses* or *Bluffs*.
  * Counterpoint: We don't need extra efficiency in "easy" variants.
* Cons: Overall more "bottom-deck" losses in "easy" variants because we potentially miss out on *Bluffs* on one-away cards.
* Pros: Less asynchronous situations that require retroactive reasoning that is prone to mistakes.
* Pros: Less complexity. More verbosely, there would be one less "gotcha"-style exception to remember. 5's stalls are already extremely complicated to reason about.

**Comment by Zamiell** [comment]
mercy should we close this?

**Comment by NoMercyO** [comment]
Close.
