### ISSUE TITLE
Convention Proposal: Positional Rank Clues for Pink Fives

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#241]
Since we can't use 5 as a rank and 5's are touched by all rank.

In a 3p game, since there are 5 slots with positional clues we add 1 to the rank clue given
1 is slot 2
2 is slot 3
3 is slot 4
4 is slot 5

In a 4p-5p game, since there are only 4 slots
1 is slot 2
2 is slot 3
3 is slot 4
4 is slot 4

Or

1 is slot 1
2 is slot 2
3 is slot 3
4 is slot 4

In a 6 p game, since there are 3 slots
1 is slot 2
2 is slot 3
3 is slot 2
4 is slot 3

**Comment by iamwhoiamhahaha** [comment]
Can you define it with [*Bubblegum Finesse Wraparounds & Skips*](https://github.com/Zamiell/hanabi-conventions/issues/214) properties? They are easier to remember

**Comment by Zamiell** [comment]
agree with jeff

**Comment by Zamiell** [comment]
since pink clues automatically apply to pink-fives, no additional changes to the document need to be done, right jeff?

**Comment by iamwhoiamhahaha** [comment]
* Just realized that _Bubblegum Finesse Wraparounds & Skips_ do not apply to _Pink Choice Tempo Clue_. The problem is in 2p and 3p, how do we give a *Tempo Clue* on slot 5?
* For example, in a 3-player game:
  * All of the 1's are played.
  * Bob has x x x i5 i2 (known as pink cards).
  * In this scenario, we're not able to get i2 from slot 5.
* Solution 1: (as kakashi has defined)
  * 1 is slot 2
  * 2 is slot 3
  * 3 is slot 4
  * 4 is slot 5
* Solution 2: Apply _Bubblegum Finesse Wraparounds & Skips_ to _Pink Choice Tempo Clue_ in Pink-Fives
  * 1 means the tempo clue on i5 in the example above
  * 2 means the tempo clue on i2 in the example above
  * 3 means the tempo clue on i5 in the example above
  * 4 means the tempo clue on i2 in the example above

**Comment by Zamiell** [comment]
go with solution 2, as it doesn't involve in making any new conventions

as with the other thread, this topic already flows from existing pink choice and/or pink positional clue conventions, so i dont think that any new changes to the document need to be made
