### ISSUE TITLE
Convention Proposal: The Shout Discard

### ISSUE THREAD

**Issue by postmansh** [Zamiell/hanabi-conventions#252]
When Alice scream discards with a known trash card this is safer than a regular scream discard. As such I'd say it could be useful to allow this also to safe non-critical, but later on playable cards on chop. 

This of course does not work for generation discards

An even stronger case is when Alice has both a known trash and a playable 5 (that would generate a clue). This could even have implications when it could potentially be a generation discard.

![hanabi ice 2](https://user-images.githubusercontent.com/66225929/83364752-d9f61000-a3a3-11ea-841a-2fdf7c881887.PNG)

Here is an example. where both 4y and 5r are fully known. 4y is trash. Given both hands 3pink is a relaly interesting card, there is plenty of room otherwise for some discards. Thus chop moving 3pink is nice from postmans POV. Under current conventions discarding 4y would indicate to hanabiplus a critical card (though in the game from context it is maybe not, but I'd like to consider the situation without such context).

For some names: I called it a whisper discard, but that is already taken by almost the opposite move (discard unknown card when having known trash). I guess stealing a name is a bad plan so some other options: Soft scream discard, safe scream discard, known trash scream discard, known trash chop move. Or the soft ice scream discard.

**Comment by Zamiell** [comment]
seems fine.

ideally you would find a one-word name for the move, e.g. a X discard

**Comment by fpvandoorn** [comment]
Yeah, I've also noticed this situation before, and this seems fine to me. Note that scream discards/generation discards are always *last resort* options. This doesn't have to be.

Questions:
* Does this Echo? (If hanabiplus has a play does TheDaniMan also cm?) I think it shouldn't.
* Does this work differently if there are clues available (I think not)
* Is hanabiplus allowed to discard after chop moving? Here I'm not sure. Pro: if that card was also discarded, postmans could have done a whisper + scream discard by discarding slot 3, chop moving hanabiplus twice (I don't think that convention is mentioned in the doc, but should exist). Con: if we say hanabiplus is not allowed to discard, then postmans doesn't have to risk discarding a potentially critical slot 3.

**Comment by pianoblook** [comment]
How about just 'icecream discard'? Keeps the 'scream'-connotation but still evokes the 'softer' nature of it.

**Comment by Zamiell** [comment]
> Does this Echo? (If hanabiplus has a play does TheDaniMan also cm?) I think it shouldn't.

agree

> Does this work differently if there are clues available (I think not)

agree

> Is hanabiplus allowed to discard after chop moving? Here I'm not sure.

i think we follow same rules as scream discard for simplicity, meaning that no, he is not allowed to discard

**Comment by Zamiell** [comment]
> How about just 'icecream discard'?

ice cream is two words, better to find something that is one word

**Comment by Zamiell** [comment]
furthermore it sounds like a scream discard, which is confusing

**Comment by padiwik** [comment]
i'm not sure i like this, but something like "voiced discard"? (it's in between a scream and whisper in terms of levels of how loud you are). or maybe like "stressed discard", but that might be confusing since it's a synonym of anxiety

**Comment by iamwhoiamhahaha** [comment]
I always do this if I have a save discard (even there are 4 or more clues in the bank). Imo this is just a scream discard chop move.

**Comment by Zamiell** [comment]
postmans/pianos suggestions are not 1 word, and voiced discard is terrible, so lets go with "shout discard" instead.

### The Shout Discard

* Normally, when a player performs a *Scream Discard*, they are discarding their chop (e.g. an unknown and unclued card).
* However, if a player has both a known-playable card and a known-trash card, then discarding the known-trash card instead of playing their known-playable card would *still* communicate a *Scream Discard* to the next player in the exact same way.
* This situation is slightly different than the normal case, so we call it a *Shout Discard* to differentiate it from a more-ordinary *Scream Discard*.
* A *Shout Discard* *Chop Moves* the very next player in the exact way that a *Scream Discard* does.
* A *Shout Discard* forces the next player to **not** discard on their turn in the exact way that a *Scream Discard* does.
* Normally, a *Scream Discard* is only allowed to *Chop Move* a critical card or a playable card. Unlike a *Scream Discard*, it is permissible to use a *Shout Discard* to *Chop Move* any card that is desirable, even if it is not critical or playable.
* Normally, a *Scream Discard* is only allowed if the team is at 0 clues (or if cluing the card is impossible). Unlike a *Scream Discard*, it is permissible to use a *Shout Discard* to *Chop Move* regardless of the amount of clues that the team has.
* Normally, a *Scream Discard* would turn into an *Echo Scream Discard* if the next player has a playable card. *Shout Discards* can also turn into *Echo Shout Discards*, but only if the team is completely out of clues and it can be seen to be a "last-resort" move.

**Comment by NoMercyO** [comment]
I would call it a Safe-Scream

but Shout is fine too. 

Looks fine

**Comment by fpvandoorn** [comment]
> Shout Discards can also turn into Echo Shout Discards, but only if the team is completely out of clues and it can be seen to be a "last-resort" move.

What does this mean? Is this desirable?

**Comment by Zamiell** [comment]
> What does this mean? Is this desirable?

yes, it is desirable for the same reason that echo scream discard chop moves are desirable

if alice needs to perform an echo scream discard chop move to prevent losing the game, and alice has a known trash card, what exactly do you expect alice to do

**Comment by postmansh** [comment]
Looks as a good concretisation to me Zamiel. Basically everything the same as a scream, safe for the critical aspect and the echo. Thanks

**Comment by fpvandoorn** [comment]
@Zamiell you didn't answer my most important question: how do players recognize when it echo's?

**Comment by Zamiell** [comment]
It always echos unless bullet point 6 or bullet point 7 is being utilized

**Comment by fpvandoorn** [comment]
Oh sorry, my bad. I didn't read the last sentence carefully enough. You do say that it is a last resort exactly when you are at 0 clues. 

Your bullet points seem good.
