### ISSUE TITLE
Delete the Finesse Position Exception (FPE)

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#253]
Consider the following example:

* It is the *Early Game*.
* Alice clues number 5 to Bob, touching a 5 that is one-away from chop. This is either a *5 Stall* or a *5's Chop Move*.
* Bob sees that Cathy has a playable card on her *Finesse Position*, and maybe Alice just wanted to do a *5 Stall* and pass so that he can *Finesse* or *Bluff* the card on Cathy's *Finesse Position*.
* If the "FPE" convention exists, then Bob takes this interpretation, and does not *Chop Move*.
* If the "FPE" convention does not exist, then Bob would always treat this as a *Chop Move*, because Alice is expected to clue Cathy's hand. (e.g. You are **only** allowed to *5 Stall* if there is nothing else to do, end of story.)
* In either situation, Bob will now "get" the card in Cathy's hand, either with a normal *Play Clue* or with a *Finesse*/*Bluff*.

I'm proposing that we **delete FPE and that it is always a *Chop Move* on Bob**.
For reference, FPE does not apply in "hard" variants and only applies in "easy" variants.

* Cons: Less flexibility in the *Early Game* to stall when you need to.
* Cons: Overall reduced efficiency in "easy" variants, because we can potentially miss out on *Finesses* or *Bluffs*.
  * Counterpoint: We don't need extra efficiency in "easy" variants.
* Cons: Overall more "bottom-deck" losses in "easy" variants because we potentially miss out on *Bluffs* on 3's or one-away 4's.
* Pros: Less asynchronous situations that require retroactive reasoning that is prone to mistakes.
* Pros: Less complexity. More verbosely, there would be one less "gotcha"-style exception for players to remember. 5's stalls are already extremely complicated to reason about.
* Pros: Easier for new players to learn how to play the *Early Game*.

**Comment by fpvandoorn** [comment]
> Cons: Overall more "bottom-deck" losses in "easy" variants because we potentially miss out on Bluffs on 3's or one-away 4's.

Since this is the main way you lose in easy variants, I think this is important.

> Pros: Less asynchronous situations that require retroactive reasoning that is prone to mistakes.

How is there less asynchronous information? It's still asynchronous whether a 5 clue is a stall or a chop move: it depends on whether you have playable cards, which you don't know at the moment.

> Pros: Less complexity. More verbosely, there would be one less "gotcha"-style exception for players to remember. 5's stalls are already extremely complicated to reason about.
Pros: Easier for new players to learn how to play the Early Game.

I do agree that it's important to keep our conventions easy for beginners, However, pang of guilt is also an important concept to teach beginners. I still feel like we should keep FPE.

**Comment by Zamiell** [comment]
> How is there less asynchronous information? It's still asynchronous whether a 5 clue is a stall or a chop move: it depends on whether you have playable cards, which you don't know at the moment.

indeed, it is still async for Bob.
but it would **not** be async for Cathy.
with FPE turned on, Cathy has to get a play clue and then retroactively reason about the 5 clue.
with FPE turned off, Cathy knows 100% whether or not this is chop move or not as soon as the clue is given.

**Comment by Zamiell** [comment]
> I do agree that it's important to keep our conventions easy for beginners, However, pang of guilt is also an important concept to teach beginners.

you are thinking about this from the perspective of Alice, encouraging good habits like not stealing finesses.

but i am instead mostly considering the case of Bob. a common mistake here is that Bob will not realize that FPE applies, and then will incorrectly *Chop Move*, and then discard an **actual** critical card on his next turn.

this is common because often times when we introduce 5CM to a new player, we don't bother introducing FPE at the same time (because FPE is more of an edge case thing and better to not overload them with too much complexity when introducing a new move).

even if it isn't a new player who hasn't been briefed on FPE, the accidental *Chop Move* **still** routinely happens to intermediate players because its non-trivial to see exactly when it applies. For example, consider the following situation:

* It is the *Early Game*.
* Alice clues number 5 to Bob, touching a 5 that is one-away from chop. This is either a *5 Stall* or a *5's Chop Move*.
* Cathy's hand is as follows, from left to right: red 1, red 3, x, x, x
* Bob sees that Cathy has a playable card (red 1) on her *Finesse Position*, and maybe Alice just wanted to do a *5 Stall* and pass so that he can *Finesse* or *Bluff* the card on Cathy's *Finesse Position*. Thus, Bob does not *Chop Move*.
* Bob later discards his chop and it was a blank card and the players lose the game.
* Bob failed to realize that cluing red to Cathy would be an excellent 2-for-1 clue (picking up the valuable one-away-from-playable red3), so the FPE didn't apply in the situation where Alice gave him a 5's clue.

**Comment by NoMercyO** [comment]
I agree that we should keep FPE. I am in favor of trying to have florrat's guide for when to discard be either verbatim adopted, or simplified. But FPE is too good to pass up despite the complexity.

**Comment by fpvandoorn** [comment]
> with FPE turned off, Cathy knows 100% whether or not this is chop move as soon as the clue is given.

This is just false, and only achievable if we disable all 5 stalls.

**Comment by fpvandoorn** [comment]
> Bob failed to realize that cluing red to Cathy would be an excellent 2-for-1 clue (picking up the valuable one-away-from-playable red 3), so the FPE didn't apply in the situation where Alice gave him a 5's clue.

As written in the current doc, FPE also applies in this case. I'm happy to say that FPE only applies if the alternative is to do a 1-for-1 clue.

**Comment by Zamiell** [comment]
> As written in the current doc, FPE also applies in this case.

then the doc is wrong because AFAIK that is not how we have historically been playing.

> with FPE turned off, Cathy knows 100% whether or not this is chop move as soon as the clue is given.

sorry, i meant that Bob knows 100% that it is a chop move as soon as the clue is given.
in any case, you're right, there will always be async-ness. im just trying to manage it i guess.

**Comment by iamwhoiamhahaha** [comment]
> For example, consider the following situation:
> * It is the Early Game.
> * Alice clues number 5 to Bob, touching a 5 that is one-away from chop. This is either a 5 Stall or a 5's Chop Move.
> * Cathy's hand is as follows, from left to right: red 1, red 3, x, x, x
> * Bob sees that Cathy has a playable card (red 1) on her Finesse Position, and maybe Alice just wanted to do a 5 Stall and pass so that he can Finesse or Bluff the card on Cathy's Finesse Position. Thus, Bob does not Chop Move.
> * Bob later discards his chop and it was a black card and the players lose the game.
> * Bob failed to realize that cluing red to Cathy would be an excellent 2-for-1 clue (picking up the valuable one-away-from-playable red 3), so the FPE didn't apply in the situation where Alice gave him a 5's clue.

How about making this as an exception for the FPE lolol

**Comment by Zamiell** [comment]
it already is afaik (undocumented)

**Comment by NoMercyO** [comment]
I would not chop move in Jeff's case. Its an interesting point. My counter to that suggestion is picking up the r3 incidentally is not excellent, it is perfectly fine. However by invoking the FPE Alice is giving bob the flexibility to either take the perfectly fine 2-1 or find a more urgent 2-1 opportunity (namely cluing blue to the b3 on Alice's chop as a 3 bluff). 

Ultimately what matters is:

a) we agree the fpe is useful, to varying amounts
b) we dont seem to agree that fpe is simple to justify its existance.

I dont think "one finesse position playable is always invisible for early game clue count" is that hard. Yes it is asynchronous, so there are some rare cases where one player (typically Bob) must be smart and retroactive. 

Eg: Bob and Cathy have unique cluable playables. Alice clues Bob's 5. Bob interprets the clue as a 5 stall, and finesses Cathy. However when Alice then retroactively calls on Bob to play he undoes his 5stall and reinterprets it, either as a 5 pull as plays the pulled card, or as a 5cm and plays slot 1. This is not clean and im ok with find a way to remove this issue. However deleting FPE doesnt remove this - it will exist with 5stalls and playables in Bob's hand either way. FPE just adds a little more complexity to the already deceptively complex early game 5 stall. 


Suggestions that FPE is bad because it prevents 5cm, or 5ND to become a 5 stall is frankly nonsense arguements. That is only relevant when all other clues have been exhausted, and if your issue is with situations where that happens very quickly - then your issue with 5stalls, not with FPE.

**Comment by fpvandoorn** [comment]
> > As written in the current doc, FPE also applies in this case.
> 
> then the doc is wrong because AFAIK that is not how we have historically been playing.

This is a tricky exception. If Bob has a red card or 3 clued in his hand (or maybe just a chop moved card), does this exception to FPE still apply? Presumably not. What if Alice has a red card or a 3 in her hand?

> sorry, i meant that Bob knows 100% that it is a chop move as soon as the clue is given.
> in any case, you're right, there will always be async-ness. im just trying to manage it.

Still, that is true independent of whether we have FPE turned on or not. In both cases Bob knows whether the 5 clue was a chop move or not (and obviously Bob is the one that has to know). So I still don't see how you are trying to manage that with removing FPE.
