### ISSUE TITLE
Rainbow Ones conventions

### ISSUE THREAD

**Issue by TheDaniMan** [Zamiell/hanabi-conventions#261]
I played rainbow ones recently, and it could really use some conventions, which I did not find.
(1) when colour is clued in early game, is there any sort of promise for what colours the things touched are? (I'm inclined towards no, play focus and assume good touch on other cards).
(2) "1s lie finesse": nothing is played on stacks. Cathy's cards are R2, Y2, G2, G2, B1. Alice clues Cathy purple, touching only B1. This is very strange, since Alice has no reason to lie about the colour of B1. Bob plays his finesse position as P1, and Cathy plays B1 as P2 or any 1. Note: this should not be used as a bluff, because this results in Cathy holding her 1 indefinitely. Does not apply if Alice lies to touch a useful card, e.g. by cluing yellow.
(3) prompts vs finesses: in pink, we always assume finesse over prompt when the numbers don't match, so that we do not play our 5s into a pink 2 finesse. Should a similar principle apply for non-matching colours? What about in dark rainbow?

**Comment by Zamiell** [comment]
we actually have some conventions relating to this, they are not written though

1) mostly yes, you are supposed to match the color to reduce confusion, however you can *sparingly* break this rule to get a good touch on e.g. a one-away-three that you would otherwise not be able to save 

2) i've not seen that yet, but it seems fine/reasonable

3) in this variant, the normal multi-color prompting rules apply just like in a normal 6 suit rainbow game. see: 
https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#prompts-in-multi-color-variants

4) the same "Prompts in Multi Colors" link from above applies to dark rainbow

**Comment by Zamiell** [comment]
there is a page for this now:
https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Rainbow-Ones_%26_Rainbow-Fives.md
let me know if i made any mistakes
