### ISSUE TITLE
Proposal: The Bad Touch Layered Finesse (Bluffs that touch two identical cards)

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-conventions#266]
https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-bad-touch-double-finesse-for-3s

The Bad Touch Double Finesse can also call for a layered finesse. For example, if you bad touch two purple 2s, that is not a bluff, but a layered finesse. 

However, *The Bad Touch Layered Finesse* is already taken (for the case where the blind-played card is a bad touch), so we might need to rename it.

One downside of this convention is that Cathy (the clue receiver) doesn't know what's going on for 1 turn. But I've seen this move in actual games already, and the two possibilities are quite clear from Cathy's perspective.

Proposal of the convention to (before a name-change):
```
### The Bad Touch Layered Finesse (Bluffs that touch two identical cards)

* Normally, *Bluffs* takes priority over *Layered Finesses*. This means that if Alice clues a red 2 using red to Cathy, and then Bob blind-plays blue 1 on the very next turn, no-one is promised the red 1.
* However, if Alice touched **both** red 2's with the red clue, then that would violate *Good Touch Principle*, and this would be considered a "bad touch".
* If someone is violating *Good Touch Principle*, they must have a very good reason, so the clue must be a *Layered Finesse* instead of a *Bluff*. In the above example, the clue also calls Bob to play red 1 from *Second Finesse Position* as a *Layered Finesse*.
* After that, the player who received the clue can safely discard the focused red 2.
* For example, in a 3-player game:
  * It is the first turn and nothing is played on the stacks.
  * Alice clues purple to Cathy, touching two purple 2's.
  * Bob blind-plays his *Finesse Position* and it is red 1.
  * Cathy sees that Bob has red 1 in slot 2. At this point, the clue is ambiguous to Cathy. It can either be a *Bluff* or a *Bad Touch Layered Finesse*. Cathy must wait and do something else to see if the red 1 also blind-plays on the very next turn. If the red 1 does play, Cathy knows a bad touch occurred, and can discard the focus of the clue. If the red 1 doesn't play, Cathy knows that no bad touch occurred.
  * Bob knows that normally, this would be a *Bluff*. However, since the purple 2's are duplicated, this must be a *Bad Touch Layered Finesse*, so on Bob's next turn, Bob will blind-play  *Second Finesse Position* as red 1.

```

**Comment by Zamiell** [comment]
i dont think this warrants a separate section. we could probably just add a final bullet point to the bottom of the existing section that says:

* Note that you can also perform a *Bad Touch Layered Finesse* on the next player. The next player will know to keep continuing to play because it was a *Bad Touch*. However, only do this very sparingly, because it violates *Good Lie Principle*, and Bob will have the potential to become completely synchronized.

**Comment by Zamiell** [comment]
i think you would only want to ever do this if e.g. the team was at 0 clues and cathy would be forced to discard

**Comment by fpvandoorn** [comment]
First I wanted to add it as a bullet point. But I think a separate convention makes more sense, since it's trickier for Cathy (and it's not a double finesse anymore). I think Cathy should respect the potential layered finesse even if she has clues.

**Comment by Zamiell** [comment]
> I think Cathy should respect the potential layered finesse even if she has clues.

i disagree, because doing so would encumber cathy unnecessarily in the 98 out of 100 times when a *Bad Touch Layered Finesse* is not happening

**Comment by fpvandoorn** [comment]
I'm a little surprised that if you are Cathy's situation, your reaction is not "I hope there is some context to make a layered finesse". 

I agree that this indeed increases the temporary asynchrony(?), in the same way that other conventions do, like clandestine finesses, double finesses, triple finesses, double bluffs, double half bluffs, reverse finesses, trash bluffs, trash finesses, and other conventions.

**Comment by fpvandoorn** [comment]
If we decide we don't want to allow this, then we should explicitly add it to doc as illegal, since it's so similar to the bad touch double finesse. However, I don't see a problem with it yet. We seem to deal with Clandestine finesses just fine, despite it being temporarily asynchronous.

**Comment by Zamiell** [comment]
For example, in a 3-player game:

* It is the first turn of the game and nothing is played on the stacks.
* Alice clues number 3 to Cathy, touching two 3's on slot 1 and slot 5.
* Bob sees that this is a *Known 3 Bluff* (since nothing is played on the stacks yet).
* Bob sees that Cathy has a critical 5 on her chop (slot 4). However, Bob also knows from *Guide Principle* that Alice is guiding him and that he doesn't have to worry about this.
* Bob blind-plays and it is successfully plays as a red 1.
* Cathy sees that Bob has a red 2 on his 2nd slot. Bob has no other interesting cards in his hand.
* Cathy sees that Alice has no interesting cards in her hand.
* If this is a *Bad Touch Layered Finesse* on two red 3's (instead of the much more common *3 Bluff*), then Bob will blind-play the red 2 "for free".
* Since Cathy does not have anything else to do except to clue the red 2, Cathy discards. It is a red 5 and the team loses the game.
* Alice's plan was to "lock-in" this very nice 3-for-1 *3 Bluff* and the to have Cathy *Play Clue* the red 2. Alice did not predict that Cathy would entertain the extremely edge-case scenario of having two red 3's.

**Comment by Zamiell** [comment]
> We seem to deal with Clandestine finesses just fine, despite it being temporarily asynchronous.

* The concept here is almost exactly the same as a *Clandestine Finesse*, so I agree that is an apt analogy to draw.
* The difference though is that *Clandestine Finesses* are fairly common. We do them all the time, and they are fresh in everybody's minds.
* If Alice performs a *Clandestine Finesse* on Bob, then Cathy is in a state of uncertainty and is encumbered. X times out of 100, it will be the truth. X is a nice high number that makes the encumbrance is worth the cost, on average.
* If Alice performs a *Bad Touch Layered Finesse* on Bob, then Cathy is in a state of uncertainty and is encumbered. Y times out of 100, it will be the truth. Y is a low number that makes the encumbrance not worth the cost, on average.
* Furthermore, since Y is so much less than X, Cathy is more prone to forget that Y even exists and make a mistake, further decreasing win-rate.

**Comment by fpvandoorn** [comment]
I see your points, and agree that it might not be worth it. In your example with the 3 clue it is indeed a lot less clear.

However, I think we should mention it in the doc as illegal:

> if we decide we don't want to allow this, then we should explicitly add it to doc as illegal, since it's so similar to the bad touch double finesse.

As evidence that it is very similar to an existing convention, I would like to point out this comment:

> i dont think this warrants a separate section. we could probably just add a final bullet point to the bottom of the existing section

I would suggest to add as a final bullet point to *Bad Touch Double Finesse* (or as a new section):
```
* Alice could try to attempt a *Bad Touch Layered Finesse*, where Alice performs a bad touch on a 1-away card or a 3 in Cathy's hand to perform a *Layered Finesse* on Bob (if there was no bad touch, this clue would just be a *Bluff*). However, this is explicitly **illegal** to do, because Bob does not demonstrate that it is a bad touch until after Cathy's turn. So before Bob can demonstrate the bad touch, Cathy is already allowed to clue Bob's hand, and therefore Bob cannot demonstrate the bad touch.
```
(feel free to edit)

**Comment by Zamiell** [comment]
I added the following section to the doc:

### The Bad Touch Layered Finesse (Bluffs that Blind-Play a Duplicated Card)

* If a player performs a *Bluff* that causes a blind-play of a globally-known duplicated card, that is quite strange. Doing this is not very good, as it violates *Good Touch Principle* and does not accomplish very much in general.
* Players agree that this is not a *Bluff* at all, but instead a *Layered Finesse*. The player who blind-played the card should continue to blind-play cards until they find the promised card.
* This section also applies to *Priority Bluffs* that cause the blind-play of a duplicated card.
* For example, in a 3-player game:
  * All of the 2's are played on the stacks.
  * Alice has a globally-known red 3 in her hand. (It is "filled in" with both a red clue and a number 3 clue.)
  * Alice clues blue to Cathy, touching a blue 4 as a *Play Clue*.
  * Bob knows that this must be a *Finesse*, so he attempts to blind-play a blue 3 from his *Finesse Position*. Instead, he blind-plays a red 3.
  * Cathy discards her chop.
  * Alice discards her known red 3 (since it is already played and is now trash).
  * Bob knows that *Bluffs* that duplicate a card like this are supposed to be treated as *Layered Finesses*. Bob blind-plays his *Second Finesse Position* as blue 3 and it successfully plays.

**Comment by Zamiell** [comment]
will close now, let me know if i should reopen
