### ISSUE TITLE
Pink Tempo Clue Exception

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#274]
https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Pink.md#pink-tempo-clues

- If a player gives a Tempo Clue to a pink card, it is never a Tempo Clue Chop Move, even if it only gets one card played.
- This is because it is fairly valuable to get pink cards out of the hand as soon as possible in case blocking cards are drawn.

Can we have an exception here that for hard variants it's a tempo clue chop move?

**Comment by Zamiell** [comment]
there probably isn't a big need for that.
in hard variants, you need more efficiency, but a chop move doesn't increase efficiency - you still have to use a clue to clue the card.

**Comment by Dr-Kakashi** [comment]
I understand that we don't have tempo clue chop moves for pink because it's easy for players to draw another pink card, but what about dark pink variants?  Can we have it be a tempo clue chop move?

**Comment by Zamiell** [comment]
ok

**Comment by Zamiell** [comment]
### Dark Pink Tempo Clues

* Normally, *Tempo Clues* on pink cards would never cause a *Tempo Clue Chop Move* (because *Tempo* on pink cards is important).
* However, this does not apply to dark pink cards. *Tempo Clues* on dark pink cards work as they normally do. (Meaning that it is possible to perform a *Tempo Clue Chop Move* by giving a *Tempo Clue* to a dark pink card, provided that all of the other normal *Tempo Clue Chop Move* conditions are met.)

**Comment by iamwhoiamhahaha** [comment]
* In an easy variant (eff < 1.25) with a dark pink suit, I believe it shouldn't be a *Tempo Clue Chop Move* while giving a *Tempo Clue* on the pink card, since we don't need efficiency somehow. Therefore, this convention should only apply to hard variants.
* However, I'm fine with this proposal, since it's somehow useful that we can *Chop Move* a card for free.

**Comment by iamwhoiamhahaha** [comment]
But I'm curious why @Dr-Kakashi want to make it be a *Tempo Clue Chop Move* but disagree with [this](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Score_Hunting_Guide.md#tempo-clue-chop-move-change)?
