### ISSUE TITLE
information strategies

### ISSUE THREAD

**Issue by WuTheFWasThat** [Zamiell/hanabi-conventions#3]
Hi!  would you consider adding the "information" based strategies from this paper? https://sites.google.com/site/rmgpgrwc/research-papers/Hanabi_final.pdf?attredirects=0

The basic idea is this hat-guessing game:  consider 5 players each with a secret number from 0 to M-1; each can see everyone else's number but not their own.  If one player can give a hint between 0 and M-1, they can immediately communicate to all other players by hinting the sum (modulo H).  If they can only give a hint between 0 and H (where H < M), they can still communicate log(H) bits of information to *everyone* via a similar (but more complicated to describe) scheme.

Implementations here:
https://github.com/WuTheFWasThat/hanabi.rs/blob/master/src/strategies/information.rs
and here:
https://github.com/Quuxplusone/Hanabi/blob/master/InfoBot.cc

These give AFAIK the best known results to Hanabi

**Comment by Zamiell** [comment]
Hello, and nice to see your interest in our conventions document.

1) Have you played Hanabi with us? We play at https://hanabi.live and are always willing to play with new players.

2) This document is specifically meant to catalog OUR specific convention framework, and not to document every possible Hanabi strategy or convention framework. Thus, your request is kind of strange in that regard.

3) I am aware of the hat guessing strategy, yes. However, to quote myself from this [BoardGameGeek thread](https://boardgamegeek.com/thread/1950068/compendium-strategies-and-conventions-hyphen-ated):

> I actually have read this paper! However, there is a subtlety here. In some Hanabi versions (mostly released in the Europe), it states that "negative" clues are allowed, which is to say that you can give a clue that touches 0 cards. In other Hanabi versions (mostly released in the United States), it explicitly disallows this. Why did they bother changing the rule? We could posit that:
> 
> 1) It makes the game unnecessarily easier. It is already possible to get a perfect 30 in nearly all deals if the players play perfectly and make no mistakes (depending on the variant, of course). Simply put, there are other clever ways that you can convey information without having to resort to negative clues.
> 2) It allows for extremely powerful conventions that "break" the game. And the paper that you linked illustrates one such strategy.
>
> So, is it better to have negative clues "on" or "off"? I propose that Hanabi players should prefer that the rule is "off" and side with the American version. My group certainly takes this stance; it is not even possible in the Hanabi.live user interface to give such clues.

It is my understanding that the implementations you link here rely on negative clues, and my group would thusly deem them as cheating. (If I'm mistaken, then my apologies, as I didn't actually go through the code.) While I don't expect everyone in the world to agree with me on this issue, hopefully I've at least better illustrated the nuance here and made a good argument. = )

4) For an example of a hat-guessing strategy that does **not cheat**, I submit to work done by one of our group members, Floris van Doorn: https://github.com/fpvandoorn/hanabi/blob/master/doc_hat_player.md
However, as I mentioned above, since it is a different convention framework entirely, it isn't really a candidate for something to be integrated within this document/repository. But we have played games with this convention framework and it was quite fun, and quite powerful.

**Comment by WuTheFWasThat** [comment]
Ha, I was linked to this document and didn't realize its purpose.  Sorry for the strange discussion.

I've never played Hanabi with you guys, but I'll keep it in mind!

In my implementation, I do not rely on negative clues, and the strategy is still game-breakingly good compared to human play.  In fact, I independently came up with the exact same strategy as in that doc, to fix a canonical card, and either clue color, number, or a 3rd card.  My implementation actually optimizes a bit more, for details see this comment: https://github.com/WuTheFWasThat/hanabi.rs/blob/9214006ccb783c79ed000eebaefd24c48c8c1d9e/src/strategies/information.rs#L678

With negative clues, the hat-guessing strategies would be dramatically better than my version; I couldn't find a good way to get nearly as much information out of hints, and this was generally quite annoying to deal with, as you might guess.

**Comment by WuTheFWasThat** [comment]
BTW, for 2 or 3 player games, the hint strategy still works *unless* a player has 3 copies of the exact same card.  Turns out this never happens - I have a panic!() in my code for that case but I've never hit it :)

**Comment by Zamiell** [comment]
RE: Best strategy
To be clear, Florrat says that the intent is for his strategy is to be actually playable (and fun) by humans, and that he wasn't optimizing it for maximum bandwidth. So, that explains why yours is better - different convention frameworks, different niches.

RE: Panic
I've played thousands of games of Hanabi, and I've personally seen 3 player games where someone has all 3 copies of a 1, so it definitely can happen. ;)
