### ISSUE TITLE
The Blaze Discard

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#302]
This is a proposal to generalize / simplify the doc.
It is an easy way to incorporate #301, incorporate #218, and incorporate the submitted Gentleman's Discard Charm that Jeff wants.

1) *Patch Gentleman's Discards* are now explicitly illegal.
2) The *Blaze Discard* is defined as any *Gentleman's Discard* or *Baton Discard* that promises the wrong position, calling for a blind-play of the matching position. (Specifically, the matching *Finesse Position*, not the matching slot.)
3) The person blind-playing for a *Blaze Discard* **must** be the very next player, in order to minimize confusion and keep things simple.
4) The *Blaze Discard* replaces the *Gentleman's Discard Ejection* (as a more general form).

**Comment by Zamiell** [comment]
Full text:

### The Blaze Discard (A Gentleman's Discard or Baton Discard That Promises the Wrong Slot)

* Normally, if a player performs a *Gentleman's Discard* and the other card is **not** on *Finesse Position*, it could one of two things:
  1) If the card on *Finesse Position* is itself playable right now, then it would be a *Layered Gentleman's Discard*.
  2) If the card on *Finesse Position* is not playable right now, then it is an emergency situation or a player is making a mistake.
* Alternatively, if a player performs a *Baton Discard* and the other card is **not** on *Finesse Position*, then it is an emergency situation or a player is making a mistake.
* If the second option is true and it is **not** an emergency situation and the player is **not** making a mistake, then the player who is performing the weird *Gentleman's Discard* (or *Baton Discard*) is instead trying to communicate something extra.
* In this situation, the discarding player intends for the very next player to blind-play the slot that **matches the true slot** of the other card. This is called a *Blaze Discard* because it "ignites" the next player's hand to fix the problem.
* For example, in a 3-player game:
  * All 1's are played on the stacks.
  * Alice discards a known red 2 as a *Gentleman's Discard*.
  * Bob sees that Cathy has the red 2, but it is not in her *Finesse Position*. Cathy has a red 1 (trash) on her *Finesse Position*, followed by a red 2.
  * Bob knows that it would be pointless for Alice to perform a *Gentleman's Discard* and then for Bob to give a *Fix Clue*, as that would waste a clue. So, if Alice is not making a mistake, she must be trying to communicate something extra.
  * Bob knows that this must be a *Blaze Discard* and he must blind-play the slot that matches the other card. In this case, since the red 2 is on Cathy's slot 2, Bob must play slot 2.
  * Bob blind-plays slot 2. It is a blue 1 and it successfully plays.
  * From Cathy's perspective, she first suspects that some kind of *Ejection* is going on, since Bob blind-played his *Second Finesse Position*. However, since the previous action was a *Gentleman's Discard*, Alice knows that this must be a *Blaze Discard*. In other words, Bob was just blind-playing his slot 2 to communicate to Cathy that she should play her slot 2.
  * Cathy blind-plays the red 2 from slot 2.

**Comment by pianoblook** [comment]
So if I'm reading the full proposal correctly, this is calling on the exact _Slots_ to match, not the _Finesse Positions_? I can't tell if that is more or less useful/intuitive than the alternative - curious to understand why or why not.

First of all, is it agreed that this should only work if both target cards are currently unclued? Barring extreme edge cases (e.g. one of their hands is clued completely brown/pink/3's e.g), it seems like this could get dangerous and easily misinterpreted. 

If that's assumed, then the question is just whether it would be more functional to match slots vs. _Finesse Position_. The current _GD Ejection_, the proposed _GD Discharge/Ejection, and the _Baton_ extension all built off of matching Finesse Positions, so why the proposed change?

Here's my stab at thoughts on both sides:

Slot Match pros:
- Simpler to see & remember
- More cleanly accounts for _Chop Moved_ cards in either hand
- Keeps the opportunity to pull this off open in situations where B&C's hands are unevenly touched (e.g. one of them only has one or two _Finesse Positions_ left)
- Position 3+ cards sometimes otherwise could be harder to get if there are blocking cards/no easy way to touch things.

Finesse Position Match pros:
- Remains consistent with _GDE_ convention
- More flexibility in when it could occur, since Finesse Positions can be more easily manipulated than Slot Positions.
- Position 3+ cards can already often be _Finessed_, _Ejected_, and _Discharged_ assuming cards are touched.

**Comment by NoMercyO** [comment]
Clarifying if this applies to wrong prompts is important. I would propose it does not as it isn't clear for the baton discard if wrong promising the slot is a thing. For the gentleman case it is less clear.
Of course the slot call from the bluff/ejected player is unclued, that much is obvious.

Overall looks good.
-----

I'll use this opportunity to also raise a side issue. Should a baton discard that promises transfers to a unclued slot convention exist, or should be transfer be reserved only for situations where the card becomes playable?

**Comment by Zamiell** [comment]
> Clarifying if this applies to wrong prompts is important.

* *Blaze Discards* do not apply when someone performs a *Gentleman's Discard* or a *Baton Discard* that looks like a *Sarcastic Discard*. In these situations, one of the following is true:
  * The discarding player is making a mistake (as a *Wrong Prompt*).
  * The discarding player is not making a mistake and there is enough past context for the player with the cards to be able to tell the difference.

**Comment by Zamiell** [comment]
> Should a baton discard that promises transfers to a unclued slot convention exist

Provide an example

**Comment by Zamiell** [comment]
> So if I'm reading the full proposal correctly, this is calling on the exact Slots to match, not the Finesse Positions?

Yeah in retrospect this was a mistake, I've edited the example now to clarify that it calls for *Finesse Positions* and not slots.

**Comment by pianoblook** [comment]
<img width="1208" alt="Screen Shot 2020-06-30 at 4 10 35 PM" src="https://user-images.githubusercontent.com/32303453/86172414-4ae82f00-baec-11ea-8f39-acc17be72ac2.png">

Just occurred in game for good value. Piano discarding m2 threatens an impending misplay of piper's i4 (previously touched here as just a '2'). hanabiplus needs to play slot 1 to fix things.

(though I did it in game anyway as a patch-finesse, but hey it works if it works)

**Comment by TheDaniMan** [comment]
Can you do it layered?
Suppose all 1s are played on stacks. C's hand is g1 r2 r3 g2 b5. Can A discard g2 for B to play second finesse position?

**Comment by Zamiell** [comment]
use their names

**Comment by piper0** [comment]
@pianoblook and I spent quite a bit of time trying to make this work last night. It sounds great, but there's a pretty major problem I don't immediately know how to get around. 

Here's an example that I think _does_ work:

<img width="1402" alt="Screen Shot 2020-07-04 at 10 26 20 AM" src="https://user-images.githubusercontent.com/67833391/86515742-d8739980-bde0-11ea-80f9-b261cbb6e25f.png">

In this example, DMoney could discard m2, knowing that piper will see the great opportunity to perform a layered blaze discard on pianoblook. piper would play b4, indicating to pianoblook that m2 is on his third finesse position. pianoblook would play slot 3, then continue to play to the right. Following the logic of the positional bounce finesse from null convention (and I do think that logic should apply here, since this is essentially the same concept), when he doesn't find the m2 on slot 4, pianoblook would play his new chop card to find m2. b4, w2, w3, and m2 play from one discard. Pretty rad.

Here's an example that _doesn't_ work (without some more rules to dictate exactly how piper should respond):

<img width="1399" alt="Screen Shot 2020-07-04 at 10 25 47 AM" src="https://user-images.githubusercontent.com/67833391/86515744-df021100-bde0-11ea-8995-a632b5225180.png">

If DMoney discards m2, piper could perform the exact same play as in the previous example. By playing b4, pianoblook would play g2, r2, and m2 in order. The problem is that piper could accomplish the same thing by bombing slot 4 (in which case pianoblook would play r2, g2, and m2 in order). Each of those plays would get all three 2's in pianoblook's hand played, and piper has no way to know which slot DMoney intended.

I love the idea of a layered blaze discard, but it might need some rigid rules to avoid ambiguous situations like this one.

**Comment by Zamiell** [comment]
> I love the idea of a layered blaze discard
thats illegal because you could be igniting the card thats in the layer

**Comment by pianoblook** [comment]
I don't want to push too hard for any Layered shenanigans, but shouldn't Bob be able to trust that Alice wouldn't be duplicating with the Ignited card?

**Comment by Zamiell** [comment]
no, that seems like an unnecessary stipulation, and one that would be prone to error

**Comment by Zamiell** [comment]
added this to the doc:
```
* Note that it is illegal to perform a *Layered Blaze Discard*.
```
