### ISSUE TITLE
Ejection/Discharge Theory and Proposals

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#311]
Over the weekend I wrote up a [guide](https://docs.google.com/document/d/1n3IjeFZo-VFEf5KSsk9mu_hDjPFvooZjXEuiYk0FSu4/edit?usp=sharing) that aims to unify + simplify all Ejections and Discharges.

Goals and included proposals:

1. A clean definition of Ejections/Discharges that aims to drastically simplify the what and why of these moves

2. A proposal to split the rarely-used _Double Play Ejection_ into two cleaner conventions (one Ejection and one Discharge)

3. 6 "new" opportunities for Ejections and Discharges, that don't interfere with any other conventional interpretations

4. A proposal for _Unnecessary_ forms of the 1-for-1 Ejections/Discharges. These are really just extensions of the [UTCP Proposal](https://github.com/Zamiell/hanabi-conventions/issues/237)

Just start [here](https://docs.google.com/document/d/1n3IjeFZo-VFEf5KSsk9mu_hDjPFvooZjXEuiYk0FSu4/edit#heading=h.b3ar6es9llx4) in the doc if you want to jump to the juicy stuff.

**Comment by pianoblook** [comment]
<img width="1201" alt="Screen Shot 2020-07-14 at 12 20 55 AM" src="https://user-images.githubusercontent.com/32303453/87383750-1bafd400-c568-11ea-8539-0bf084e6f0ef.png">

In-game example of what could have been an Unnecessary version of a _Trash Push Discharge_.

Context: multi-5 is known, b4 is known non-green, and Bonja's m1 is basically known trash (non-4/5)

- With negative green on piano's 4, a simple 4 clue would have gotten it played.
- Instead, cluing Black to Bonja's trash 1 would trigger a _Trash Push Discharge_
- After b4 plays, Bonja wonders why Nitrate would go through all this trouble to get the b4....
- He must be promising something extra: a _Trash Push_ on the card to the left of the 'pushed' card (which is now also known trash)

**Comment by pianoblook** [comment]
Here's a list of the individual Ejections proposed. Some have been proposed in the past, and I'm hoping this unifying 'Signal Shift' theory can help convince folks that these are all super intuitive and fall perfectly in line with existing Ejections/Discharges.

**1. Trash Push Ejection**
-	If a _Trash Push_ is given on a card that would require the next player to have two or more blindplays to fulfill, this calls for an Ejection.
-	Thus, the clued player should Chop Move their ‘Pushed’ card.


2. Tempo Chop Move Ejection
-	If a Tempo Clue would trigger a Chop Move, but the CM’d card is actually trash, an Ejection is called for.


**3. Trash Fix Discharge**
-	If a playable card is reclued in such a way that it appears to now be a Trash Fix Clue, a Discharge is called for in order to correctly (re)Shift the Signal.
-	This would only make sense if the card is not yet fully clued/known, since otherwise it would be completely illogical to consider it a Trash Fix.


**4. Pink 1 Rank Choice Ejection**
-	If a playable Pink-style 1 is the focus of a 5 clue (anywhere) or a 2 clue (while on chop), this would usually indicate a Save.
-	The next player should Eject to demonstrate that it is indeed playable.
-	(Note that this neatly avoids any conflicts with both 5NDs and Bubblegums)
-      (The inverse might also be reasonable - cluing '1' on a Pink 5 - though usually this can just be achieved through a 5CE)


**5. Order Chop Move Ejection**
-	If a player performs an Order Chop Move that would Chop Move known Trash, this calls for an Ejection from the next player.
-	This would usually occur as a Skipped Order Chop Move.


**6. Declined Skipped Order Chop Move Ejection [credit: piper]**
-	If a player declines to give a Skipped Order Chop Move on a critical card, and instead doesn’t OCM anything, this calls for an Ejection.
-	Once the Ejection occurs, the next player should Chop Move their rightmost card as a known critical card.


There are two other main proposals here:

1) Cannabilize the _Double Play Ejection_ into two distinct forms: 
(A) Remains an _Ejection_ under the umbrella of a Bad Tempo CM (when the card is now fully known to be playable and therefore can't be interpreted as a 'trash fix'
(B) Becomes a _Discharge_ in situations in which it remains unknown and, therefore, the clue makes it look like a _Trash Fix_.
- DPE is already rarely-used, inefficient, and doesn't even make sense logically. It also is the ONE outlier from all the rest when it comes to this overall model. This also would give us another Discharge, which is handy.

2) Unlock "Unnecessary" forms of 1-for-1 Ejections.
- Just as UTDs can now call for an additional _Trash Push_ / _Finesse_ when they were totally unnecessary, other Trash Ejections should be able to do the same
- This would unlock Unnecessary Junk Ejections and Unnecessary Trash Push Discharges, if not more.

**Comment by florian-5f3759df** [comment]
Sounds interesting! Small clarification about the "unnecessary" forms of 1-for-1 ejections. The proposal of #237, see also writeup at #322, already covers all the examples, in the sense that that proposal already talks about unnecessary forms of all these conventions (including non-trash 1-for-1 ejections).

The difference is that we decided on only going for the trash push / cm interpretation if the directly focused card was unknown trash. If it's known trash it just calls for a slot 1 blind play of the first player that doesn't have a blind play yet. So if an unnecessary Bad Chop Move Ejection or unnecessary Trash Push Discharge was performed, where the clue target was Carol, we still let Carol play slot 1 instead of play the card to the left of the blind unclued trash. And even if Donald is the target, it's always Carol who blind plays slot 1, never Donald.

So your proposal doesn't quite 'unlock' these conventions, but it does change which slot is played. It does make them more flexible, since if Donald is the clue receiver it calls for a play of either Carol or Donald, and so only one of them has to have a playable card. When writing, we thought about it and decided against this, since it seemed more complicated for players to learn and interpret. (But if there is some way of looking that makes your interpretation it the natural thing, then perhaps it can be changed sometime in the future.)

**Comment by pianoblook** [comment]
Yep, for sure a blind play from Cathy is totally reasonable in the Unnecessary forms, and for sure I assumed that was previously proposed. I guess this is just slightly broadening the use cases to include a _Trash Push_ interpretation from Donald, if Cathy doesn't play.

Although that might 'feel' messy and overly complicated, my main argument here is that these Ejections/Discharges are actually much simpler than we generally view them at the moment. In other words, if Bob _Ejects_ after a _Junk Ejection_ clue is given to David, it really shouldn't be rocket science for David to convert this to a _Trash Push_ if the initial ejection was totally unnecessary.

**Comment by florian-5f3759df** [comment]
I agree that it's not that complicated to turn it into a trash push, and that you could probably have a consistent set of conventions for which that's the most reasonable thing to do. But currently, Cathy only doesn't respond if she sees the matching follow-up card to Bob's blind play on someone's finesse position. (Like if Bob blind played r3, and she already sees r4 on Donald's finesse.) So Donald plays slot 1, because of the generalization of [the Finesse Form](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-unnecessary-trash-push-finesse-form), and when adding this, you'd have to be careful about the conflict with that part.

**Comment by ZakisanGithub** [comment]
Quote from page 2: "While there are a couple other ‘Shifts’ that aren’t Es/Ds, there are no Es/Ds that are not Shifts. In other words, this model cares about squares, not all rectangles." [Sidenote: I find the second sentence unhelpful - just say that your models only concerns the subset of 'Shifts' which are Es/Ds.]

I think that adopting this proposal as a way to determine whether to play finesse, or to eject or discharge **in-game** only makes sense **if all of these signals are ejections and discharges** since in-game, after Alice gave a clue that requires a signal change, Bob will know what signal change to give and has to translate into playing finesse/ejection/discharge, which would require memorizing special cases which are not ejections or discharges in this framework. (Of course one could keep the train of thought below for this convention, but then this proposal introduces mental overhead without apparent gain in the most common situations.) 

Currently, the thought process for trash clues given by Alice seems more natural, namely that Bob thinks about what the clue receiver will think after Bob blind plays finesse position. I acknowledge that we skip over ejections in this train of thought since we discharge even when there is no legal ejection interpretation, but _in my mind_ that has been done to make these conventions simpler to use without mistakes (since whether another interpretation for an ejection is available might depend on asymmetric information).

**Comment by Zamiell** [comment]
> Currently, the thought process for trash clues given by Alice seems more natural, namely that Bob thinks about what the clue receiver will think after Bob blind plays finesse position. I acknowledge that we skip over ejections in this train of thought since we discharge even when there is no legal ejection interpretation, but in my mind that has been done to make these conventions simpler to use without mistakes (since whether another interpretation for an ejection is available might depend on asymmetric information).

that's exactly what happened

e.g. unknown trash discharge was an ejection when there was no valid 5ce interpretation, and if there was a valid 5ce interpretation, it shifted to a discharge

this was absolutely terrible, so i changed it

**Comment by pianoblook** [comment]
So you're right that there would still need to be some mental overload for players to remember what 'weird clues' can be resolved by a simple Finesse vs requires 2nd or 3rd _FP_. But I strongly believe that setting this as the foundation to Ejections/Discharges would overall lead to less complexity and mental overload. 

To my knowledge, here are the only 'Finesse-and-not-Ejection/Discharge' Switches (aka the "rectangles that aren't squares", in the quoted metaphor)
- Trash Finesses/Bluffs (Play --> Trash)
- 5 Double Pulls (Save --> Play)
- Declined 5s-CM (Save --> Play)

I'd argue all of these *already* require mental overload to some extent. And full complacency would be dangerous too, because players _should_ always be consciously thinking, "what's the Signal, and do I need to Shift it?" 

For example:
> "Is this really a Trash Bluff, or does it need to be a UTD?"
> "Is that card stale enough that this is just a TCM?"
> "Is this a Trash Finesse or a Focus Inversion?"

As it currently stands, Ejections and Discharges already *are* the remedy to situations in which a simple blindplay doesn't correctly Shift signals. This proposal just aims to formalize/quantify/simplify/unify all of them.

In terms of reducing the mental overload of level 15 games (which all of these moves are except 5CE), it seems like a huge benefit to be able to have a fundamental definition of what an Ejection / Discharge is, rather than needing to memorize a list of different arbitrary conventions

**Comment by pianoblook** [comment]
This might sound blasphemous but another way to reduce that overload could just be to change Double-Pulls and Declined-5s-CMs to Ejections, lol. Other than trash finesses/bluffs I believe those are the only "special edge cases" of Shifting that exist (and maybe I'm forgetting another, but still).

Like, those are already weird special edge cases that people need to memorize in order to spot, right? If you haven't memorized them then it would be reasonable to just think "huh that's weird - maybe they're just trying to [leave the 5 open for a 5CE / cming the 1 so we can invert focus / etc etc]"

But they're still useful at high-level play.

**Comment by pianoblook** [comment]
https://hanab.live/replay/262891/37

<img width="1187" alt="Screen Shot 2020-08-05 at 6 14 19 PM" src="https://user-images.githubusercontent.com/32303453/89497801-102c8300-d78b-11ea-97da-5628213d9490.png">

Another clean example of a _Bad Tempo Chop Move Ejection_ in Dual Color

**Comment by NoMercyO** [comment]
I am interested to see a streamlined understanding of how 'clue shifting' would be implemented to streamline ejection and discharge (and perhaps how it loops into bluff/finesse. 

Currently they are split arbitrarily with very little intuition to derive which is correct besides memory. Practically ejection should be more common than discharge by roughly double i would estimate, based on need for hand management. Charm is pretty much useless (outside null).

**Comment by pianoblook** [comment]
This doc just aims to tie it all together and present a foundational logic. It seems like all existing Ejection/Discharge were just made up individually from scratch, this is just my attempt at analyzing them as a whole. 

And, super satisfyingly, all the logic is already 95% streamlined! So it's already clear that everyone has an intuitive sense of what makes an Ejection an Ejection - but let's just write it down. Even if the terminology of "Signal/Clue Shifting" hasn't been formalized in the past, it's _exactly_ what all these moves do. And I hope this doc (or something similar) can just serve as a reference guide to learners who want to understand.

To your point on looping in other conventions: I actually think the concept of Bluffs and Trash Finesses can be described as fundamentally different than a "Signal Shift on a Card". Maybe not to beginners, but in expert play.

For example if a trash 1 is clued as a play, the "true" signal is understood as being a play clue elsewhere, and the clued card is then known to be disposable. Heck, we're even allowed to do _Reverse Trash Finesses_ because that can be clearly discernible. Similarly with normal Bluffs, it's 100% clear that the real "Target" of the signal were the blindplays themselves instead of the clued card. And stuff like Trash Pushes, Positionals, _Ignitions_, etc, etc are all "knowable" without any other shenanigans needing to occur.

Stuff only gets weird (aka Ejectiony-Dischargey) when Bob realizes that wait, No: "the 'real' Play Signal (aka in a _Finesse_ or _Bluff_) **can't just be on my First Finesse Position card** because blindplaying that card will desync the team!"

With bluffs and finesses accounted for, I think there's only one outlier that remains: the 5-Double-Pull. I thought the Decliend 5s CM was too, but thinking back that's just another form of a "suboptimal save"

**Comment by Zamiell** [comment]
re: the chart
its weird though that it doesn't go in a circle

**Comment by pianoblook** [comment]
You can still think of it circularly if you'd like, just with a clockwise orientation (otherwise 'Two Shifts' would be impossible). Actually huh, if you think of it as a clockwise circle then Double Play Ejections would actually remain valid as a Single Shift (Trash --> Play).

The [Play <--> Save <--> Trash] sequence just arises from how all these moves naturally function. Trash is on the tail end because cluing a card as a direct "Trash Signal" doesn't currently exist: the 'real' signal when trash is clued always slides to a different card: e.g. it's actually a "Save" (trash cm) or "Play" (trash push, trash finesse, etc).

**Comment by Zamiell** [comment]
> Play <--> Save <--> Trash

- e.g. 5ce is play --> save (shift right)
- e.g. b5cme is save --> trash (shift right)
- e.g. ???? is trash --> play

**Comment by pianoblook** [comment]
I edited my above comment about clockwise circularity - I think it's much clearer to just think of it linearly. Trash is always a "surprise" interpretation for a Signal, since no simple clue will be given solely to Signal "Trash!".

There are a couple "counterclockwise" examples: 
- Rank Choice Ejection: Save --> Play (shift left)
- (deleted) Order Ejection: 'Trash' --> Save (shift left)
- (proposed) Turnabout Ejection: Save --> Play (cluing a playable pink 1 / reverse 5 as a 5/save)

**Comment by pianoblook** [comment]
<img width="1187" alt="Screen Shot 2020-08-18 at 2 03 22 AM" src="https://user-images.githubusercontent.com/32303453/90816542-6dcbde00-e2fa-11ea-862b-3ae89542caba.png">

The fabled Unnecessary Trash Push Discharge Trash Push

**Comment by pianoblook** [comment]
Another successful UTPDTP tonight

<img width="1244" alt="Screen Shot 2020-09-03 at 12 29 44 AM" src="https://user-images.githubusercontent.com/32303453/92071399-9b923780-ed7c-11ea-8f9c-8a53f9dcc98c.png">

**Comment by pianoblook** [comment]
<img width="1087" alt="Screen Shot 2020-09-09 at 1 26 17 AM" src="https://user-images.githubusercontent.com/32303453/92557979-8402f500-f23b-11ea-8b97-dacf7b180d3f.png">

OOP UUTDTPTP

**Comment by Zamiell** [comment]
> 6 "new" opportunities for Ejections and Discharges, that don't interfere with any other conventional interpretations

using complicated ejections and discharges in a game decreases overall win rate among intermediate and expert players alike, especially in non-crazy variants where it is not necessary to do anything fancy in order to win.

thus, i don't think that there is a strong case for needing "6 new opportunities for Ejections and Discharges".

furthermore, the way that you phrased this sentence is a little weird. you seem to be implying that by adding 6 new things, it would make the convention framework 6 units better. but thats not how this works. everything added to the framework has a cost. that is not to say that the convention framework can't change, but the story is that from 2018/2019 onwards, in the vast majority of cases, "more things" equals "worse framework", and not the other way around, so I think its important to emphasize this.

additionally, we should keep in mind that the convention framework is not supposed to be tuned for the absolute best players, it is supposed to be tuned for a wider audience.

> (A) Remains an Ejection under the umbrella of a Bad Tempo CM (when the card is now fully known to be playable and therefore can't be interpreted as a 'trash fix'

this doesn't make sense to me, you cannot get tempo on a card that already has tempo.

> (B) Becomes a Discharge in situations in which it remains unknown and, therefore, the clue makes it look like a Trash Fix.

sounds not very useful and complicated besides.

i am not a big fan of fragmenting an already rarely-used convention into two more-complicated things purely for the purposes of forcing the move into some kind of conceptual box .

if you think that:
* expanding the [Ejection Intro section in level 17](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#level-17---rarely-used-strategies---ejection) to include a short explanation of signal shifts and a graph
* expanding the [Discharge intro section in level 17](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#level-17---rarely-used-strategies---discharge)  to include a short explanation of signal shifts and a graph

would be beneficial for learning purposes, then you can submit a PR.
but the PR would also have to briefly mention that there are exceptions (e.g. DPE, and not sure if there are any others).

unfortunately, for me personally, i find the graph unhelpful in explaining what an ejection or a discharge is.
i can only imagine that this extends to other people. but since I invented ejections, I am probably not the best person to weigh in on this.
ultimately, in order to determine if it is useful, data will have to be gathered from newer players

**Comment by Zamiell** [comment]
> A proposal for Unnecessary forms of the 1-for-1 Ejections/Discharges. These are really just extensions of the UTCP Proposal

this should be in a separate thread

**Comment by Zamiell** [comment]
closing this since piano did a PR
