### ISSUE TITLE
5s Priority Proposal

### ISSUE THREAD

**Issue by Elatekur** [Zamiell/hanabi-conventions#313]
Suppose Alice has two known playable 5s. If she plays her right-most 5, it seems reasonable to ascribe some special meaning to this. I propose that we say that Alice is promising someone a playable card on finesse position. For example, in a 3p game, if Alice plays her right-most 5 and Cathy has a playable card on finesse position, Bob should not play and should let Cathy play.

This would allow Alice to get cards for free in this way in more situations than if we insisted that she could only "bluff" Bob. Unlike in a finesse, Alice is not promising anyone a particular card so it seems that this shouldn't be considered a "lie" since there should not be any confusion among her teammates.

**Comment by padiwik** [comment]
i.e. we're overriding *Known Priority Bluffs* and saying they apply to the *last* player with a playable card on finesse, similar to an Ambiguous Finesse.

However, this convention is probably worse if it forces a prio bluff to act on Donald instead of Bob in a 4-player game, for example. I do think it could be useful though for end-game scenarios where you want to prio bluff someone who is not immediately in front of you.

**Comment by ZakisanGithub** [comment]
To me, the disadvantage of this suggestion is something like the following scenario: 
Alice has b5 on slot 1 and y5 and slot 2, both known and playable, and plays y5 from slot 2. Bob, Cathy, and Donald have playables in their slot 1. If Bob gives a bluff using a clue to Donalds hand, Donald cannot know Cathy blind played from priority of from the clue to him. 

That is the real loss of giving up good lie principle in my opinion. Connecting blind plays with the corresponding clues is valuable to keep the team synchronized.

**Comment by Elatekur** [comment]
To clarify, I'm not proposing giving up the good lie principle. I'm just proposing that this wouldn't be considered a lie. What if Alice were only allowed to get Bob or Cathy to play and not Donald? This would still give more opportunities to get cards for free but would make sure the blind plays were resolved more quickly.

**Comment by NoMercyO** [comment]
A few comments: 
a) Often the identity of the two 5s is not globally known, and we allow a player to select which 5 to play to convey the most information to the table. An examples: Alice has X X r5 b5. b5 could also be g5 from Bob's perspective, but Alice sees Bob has g5. Alice plays b5 and Bob adds g5 elimination notes.
Is this being proposed to change?

b) Assuming the answer to (a) is no, this is a very niche situation. Admittedly the current known 5s priority bluff is even more niche as only Bob can act upon it. However lets consider every case. 

Only one of Bob, Cathy and Donald has a finesse position play. MOST COMMON:
- Previously 1/3 of these cases are executable (Bob). 
- Proposed changes: all 3 cases work. The upside is somewhat mitigated by the fact that the played 5 always generates a clue, which many times would be available for Bob to use to anyways. When Bob has a different semi-urgent play, Cathy and Bob now can both play, which is great. 

Two of Bob, Cathy, Donald has finesse position play:
- Previous Bob always can play. 2/3 times this is desired, usually Alice would prefer to act to instruct Bob to play. 
- New method If it is Cathy and Donald exactly, Bob cannot bluff Cathy, but can play clue or finesse Cathy, and Donald can trust deeply and still play slot 1. I expect errors here to be common. 
- New method if it is Bob plus Donald exactly this new proposal is quite bad. Now Bob never plays where originally Bob and Donald will likely both be able to play (Cathy cluing Donald). 

Three finesse position plays: very RARE.
- original convention is superior. Ability to instruct Bob to play is Alice's best case. 

Overall this change has probably more merits than not, but it is not entirely clear cut. 

c) One huge upside of Bob being always the only play to be instructed to play is human error. 5s order plays will be easy to miss. When Bob misses it, no misplays will follow, everyone understands the error. However if we extend the convention to anyone Finesse play, if anyone misses the 5s play, someone will almost always bomb. 

Overall im not sure the complexity merits the inclusion, largely due to the rarity of the situation.

**Comment by Zamiell** [comment]
> If she plays her right-most 5, it seems reasonable to ascribe some special meaning to this.

we have decided to explicitly not ascribe any special meaning to this

not everything needs to have a meaning, e.g. see convention goals.md

**Comment by Elatekur** [comment]
> a) Often the identity of the two 5s is not globally known, and we allow a player to select which 5 to play to convey the most information to the table. An examples: Alice has X X r5 b5. b5 could also be g5 from Bob's perspective, but Alice sees Bob has g5. Alice plays b5 and Bob adds g5 elimination notes.
> Is this being proposed to change?

I was not proposing to change anything in that case. However, if Alice has two 5s which are globally known to be playable but Alice may not know the exact identity of each card (e.g. Alice knows she has r5 and b5 in some order with r4 and b4 on the stacks), then I think this proposal would still be reasonable

**Comment by Elatekur** [comment]
> > If she plays her right-most 5, it seems reasonable to ascribe some special meaning to this.
> 
> it is reasonable yes, but we have decided to explicitly not ascribe any special meaning to this
> 
> not everything needs to have a meaning, e.g. see convention goals.md

That makes sense. I think this is a fairly natural interpretation of playing the "wrong" 5 but it does obviously create additional opportunities for misplays.

**Comment by Zamiell** [comment]
> it does obviously create additional opportunities for misplays.

exactly.
most people in the group are not good enough to even play with our existing conventions without messing up.
adding more stuff can lower win rate.
