### ISSUE TITLE
Convention Deletion: Black 4 Bluff

### ISSUE THREAD

**Issue by NoMercyO** [Zamiell/hanabi-conventions#333]
With 4s double bluffs nad a much wider variety of 'black-like' variants this convention is no longer well defined in unique game space and consequently much more prone to misunderstanding, as well as less effective.

I propose its deletion, to be superceded by the more generally applicable 4-double bluff.

**Comment by aliblong** [comment]
I would prefer to do the opposite and bring back critical 4 bluffs with colour. To this day, I disagree with the argument that it's somehow hard to remember that bluff targets could be critical 4s, and I maintain that the convention was not given a fair assessment. You've seen how commonly we do black 4 bluffs alone. It essentially amounts to doing a combined bluff and early save every few games, which is pretty good.

**Comment by florian-5f3759df** [comment]
I also think it makes sense to have all critical 4s as single bluff targets (with color clues only), instead of having a special black version. Since it's critical, it's clearly good value to have as a single bluff target. And it's easy to remember if it holds for all suits, black will just be a particular case.

**Comment by Zamiell** [comment]
i would rather delete a convention rather than add a convention

**Comment by aliblong** [comment]
My counterproposal is a modification of valid bluff targets, so I don't think it's fair to frame it as an additional convention. Since it supersedes the black 4 bluff, it is in a sense also "removing a convention".

**Comment by Zamiell** [comment]
with the combination of one-away-from-playable cards and 3s, it *feels* like we usually have enough bluff targets to bluff if we want to (although obviously not always the case).

thus, it would be a shame to lose the ability to 4s double bluff in a situation where there are only one-away-from-playable cards and only critical 4s.

with that said, this argument doesn't really strike me as very important. the main reason i would favor having no conventions at all is because it reduces the total amount of headspace conventions, reduces the difficulty of learning the hyphen-ated conventions, and reduces the total space of possible mistakes.

**Comment by aliblong** [comment]
> it reduces the total amount of headspace conventions

Again, it's not a new convention. It's a change to an existing convention, namely adding critical 4s to the list of valid bluff targets. There's virtually no additional cognitive load to having to remember that a bluff target can be a critical 4; maybe just a static cost to introducing the change to existing players. It's even less complicated than using rank to bluff with a one-away 4.

> it would be a shame to lose the ability to 4s double bluff in a situation where there are only one-away-from-playable cards + critical 4s.

That's not quite right. You would only lose that ability when the 4 couldn't be targeted with a rank clue.

**Comment by Zamiell** [comment]
> Again, it's not a new convention. It's a change to an existing convention, namely adding critical 4s to the list of valid bluff targets.

Maybe we are arguing over semantics here. In this specific case, I am contrasting between mercy's proposal (not having any additional bluff targets) and your proposal (having additional bluff targets). So yes, I think that it is more cognitive load. Maybe you don't agree that more bluff targets = more cognitive load, which would be weird. But at the end of the day, it is certainly more complicated than simply not having any additional conventions that give extra legal bluff targets.

In any case, we should also note that your proposal should be evaluated differently than mercy's proposal, because mercy's proposal only applies to games with black cards (10% of games?) as opposed to your proposal, which applies to 100% of games.

**Comment by aliblong** [comment]
> Maybe you don't agree that more bluff targets = more cognitive load, which would be weird.

This framing is missing the forest for the trees. Let's say we decided that red 2 is the only valid bluff target. We've now reduced the number of valid bluff targets. Is this rule more or less complicated before? The former, obviously, because it's less general.

> But at the end of the day, it is certainly more complicated than simply not having any additional conventions that give extra legal bluff targets.

Please, please stop framing my proposal as an "additional convention". It's not.

I maintain that "One-away cards and 3s and critical 4s" is not appreciably more difficult to remember than "One-away cards and 3s". If you personally had difficulty with this, I posit that it's because you were experiencing a static switching cost, just like when we introduced 3 bluffs.

Furthermore, I maintain that a general rule of "you can bluff with critical 4s" is significantly less complicated than the variant-specific convention that @NoMercyO proposed to delete.

> In any case, we should also note that your proposal should be evaluated differently than mercy's proposal, because mercy's proposal only applies to games with black cards (10% of games?) as opposed to your proposal, which applies to 100% of games.

I dislike your continued suggestions to discuss highly related conventions separately (#332). None exists in a vacuum. Action on one of these proposals affects the other.

**Comment by Aigul9** [comment]
As far as I know, 3 bluffs were invented to save non-critical 3s in order to reduce bottom-deck loses. Critical cards can be saved later in most variants, especially in easy ones, without risking efficiency. Moreover, delay of a playable 3 is likely to decrease the percentage of wins, if the player draw a 4 of the same suit.

**Comment by aliblong** [comment]
> As far as I know, 3 bluffs were invented to save non-critical 3s in order to reduce bottom-deck loses.

That's a significant benefit of 3 bluffs, but the more general reason to use them is that doing so increases winrate. This effect is anecdotally observed regardless of the variant's "difficulty" (likelihood of getting a max score); in higher-"difficulty" variants, the "avoiding bottomdeck" aspect becomes relatively less important than the "extra efficiency" aspect, where the latter is helped by critical 4 bluffs.

> Critical cards can be saved later in most variants, especially in easy ones, without risking efficiency.

There absolutely are situations where in absence of critical 4 bluffs, you would lose efficiency by having to give separate play and save clues. That's the whole reason I'm proposing this amendment to bluffs.

**Comment by Zamiell** [comment]
> Let's say we decided that red 2 is the only valid bluff target. We've now reduced the number of valid bluff targets. Is this rule more or less complicated before? The former, obviously, because it's less general.

is that obvious? i have the exact opposite intuition. it would obviously be the latter. just think about how easy that convention would make playing rainbow (and dual-color) games. you wouldn't have to ever split your brain to think about multiple possibilities, and it would streamline a lot of gameplay - much less note-taking would be needed.

**Comment by aliblong** [comment]
> > Let's say we decided that red 2 is the only valid bluff target. We've now reduced the number of valid bluff targets. Is this rule more or less complicated before? The former, obviously, because it's less general.
> 
> is that obvious? i have the exact opposite intuition. it would obviously be the latter. just think about how easy that convention would make playing rainbow (and dual-color) games. you wouldn't have to ever split your brain to think about multiple possibilities, and it would streamline a lot of gameplay - much less note-taking would be needed.

It's funny that you use the word intuition, because this seems to me like exactly the difference between an intuitive approach to Hanabi vs an algorithmic one. I'm hoping someone else will chime in.

**Comment by sjdrodge** [comment]
I think we should discuss the relative merits of the convention. Obviously all conventions induce cognitive load. Critical 4 Bluffs do not introduce any particularly strenuous amount of load compared to any other convention we play with, and it's not worth anybody's time to argue about the exact nature and mount of cognitive load it might induce. If we focus on actually discussing the pros and cons of the convention, we can make an informed decision about whether to accept it or not.

The major upside is that we gain efficiency in common situations. The major downside is more possibilities for the clue recipient when a bluff occurs. A minor downside is a reduction in number of double bluffs available.

I personally think that the convention has enough merit to at least be worth testing out. I'm going to start playing with it.

**Comment by NoMercyO** [comment]
I am hesitant to undersell the cognitive load of critical 4 bluffs. We already have hard 4 bluffs vs 4s double bluffs so the idea of weighing up 1 vs 2 blind plays for Cathy is already present. Clues historically have typically meant the same thing whether they are color or number, giving free choice to choose (with 5s being a major exception, along with 2 saves). This is contrary to that, which is undeniable complexity.

Setting aside cognitive load the merits of the convention are interesting, but certainly hard to evaluate without data. More bluff targets is probably good? For the most part any 3 remains superior to a critical 4 as a target. It also will reduce double bluff targets (less so as number will often exist as a good option) I agree with Stephens summary there.

I'm ok trying out critical 4 bluffs, and have no strong opinion on it generally. However i maintain that black exceptionalism is bad.

**Comment by Zamiell** [comment]
>  it's not worth anybody's time to argue about the exact nature and amount of cognitive load it might induce

A quibble: we do indeed need to find out how much cognitive load a convention introduces, and this is one of the main criterion I use when evaluating new convention proposals that people post here. The reasoning behind this is documented in convention_goals.md.

**Comment by florian-5f3759df** [comment]
In defense of extending: I think the extra cognitive load is quite small, since it's comparable to checking if a clue is a save clue or not. All the clue receiver has to do is look at the trash and write "2,3,4" instead of "2,3" on a card, and afterwards it's like resolving any good touched card.

A bigger issue is that a lot of 2s and 3s that were bluff targets would be additionally marked as possibly-4, making them harder to be automatically known. But (as with black) this partially resolves itself if another player draws the unique 4. I am in favor of trying the change, and I think it will be a net positive (but I see that there's a negative side too, so experience might change my mind in the end).

**Comment by fpvandoorn** [comment]
I think critical 4 color bluffs are good. I think a play + a save on a critical card is enough value that it doesn't warrant an additional blindplay.

**Comment by Zamiell** [comment]
### The Critical 4 Bluff

* Building on the *3 Bluffs* convention, we also agree that it is possible for a card that initiates a *Bluff* to be a copy of any of the 4s that are currently in the discard pile.
* This means that the full list of "legal *Bluff* targets" is:
  * any *one-away-from-playable* card
  * any 3
  * any critical 4

**Comment by Zamiell** [comment]
im wondering if i should unify the bluff section and the 3 bluff section and teach them both at once

**Comment by NoMercyO** [comment]
I think that is a bad idea.
I still think bluffs are too high for level8, and remain unconvinced bluffs should come after layered finesses.

But putting that point and the layered finesse vs bluff complexity aside, 3 bluffs do non trivially amp up the complexity of a bluff. Without them (and complex variants and hard bluffs) a bluff exactly marks the identity of a card, which really simplifies them. Additionally jumping to 3bluffs without a fundamental grounding in bluffs it not intuitive, as evidenced by how many times people ask about them.

**Comment by fpvandoorn** [comment]
I'm not sure if anyone was arguing about critical 4 bluffs with *number* instead of *color*. I prefer only allowing this with *color*. Otherwise, there are even more possibilities for true finesses interpreted as hard bluffs.

And I agree with NoMercy. First teach normal bluffs, then teach 3 bluffs + *color* critical 4 bluffs.

**Comment by Zamiell** [comment]
doing it with only color introduces even more complexity, but okay.

i worry that only-experts voting in conventions that make it more difficult to play with beginner and intermediate players is a harm that may not be properly weighted by the expert players who are voting.

consider why we deleted critical 4 bluffs in the first place - has any of those reasons changed or become any less relevant?

**Comment by aliblong** [comment]
> consider why we deleted critical 4 bluffs in the first place - has any of those reasons changed or become any less relevant?

The principal reason you pushed to delete critical 4 bluffs was this belief about complexity, which most here are disagreeing with you on. I believe you also argued that "we never do them", which I never agreed with except in the sense that the opportunity is uncommon (maybe 10% to 20% of games). Neither of those has changed; IMO, they remain weak arguments.
