### ISSUE TITLE
Delete Patch Finesse (Strong Form) section

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#338]
* In the 0.1% of games that *Patch Finesses* successfully occur, they are *Hidden Form*.
* Even more rarely, they can also be Strong Form.
* *Hidden Form* is nice because no-one assumes a *Patch Finesse* is occurring at all, and no-one has to even know that *Patch Finesses* exist. *Hidden Form* "just works".
* *Strong Form* is where we get into problems.

As I said in the #convention-questions channel recently, the amount of successful *Patch Finesses* are woefully outnumbered by the combination of failed *Patch Finesse* and other types of clues that people stupidly interpret as *Patch Finesses*. Having the convention exist at all is a net-harm. There is just no possible way that the 1 in 10,000 successful *Strong Form Patch Finesse* could possibly outweigh all of the confusion and misplays that it causes in other situations.

Mercy seems to agree:

> NoMercy07/30/2020
It would be a shame to delete patches but it may be required as too many players fail to evaluate urgency and efficiency of finesses with a lie. 

Floriman seems to agree, showing this excellent example: 

> https://hanab.live/replay/255285/12 . I suggested that to prevent g4 from dying, reuzed should consider cluing green to sephiroth, and sephiroth then fixes the wrong prompt since he's fully on board by good touch. Sephiroth said that he would consider blind playing slot 1 as r1, which is an interpretation I would be happy with banning

A possible counterargument:
*Strong Form* is fine and good for high-level play, it is only intermediate players that make mistakes.

Counter-counter argument:
Florrat, Libster, and I have not performed a single *Patch Finesse* in any of our competition games, nor has it even come up as a possibility.

In addition to *Strong Form*, we could also delete *Hidden Form* - I believe that there is a strong argument for deleting this as well. Even though *Hidden Form* is more frequent than *Strong Form*, I *still* have not seen a *Hidden Form* in thousands and thousands of games.

For now, as a compromise, I think it is fine to keep the *Hidden Form*, and just delete the *Strong Form*.
This is a nice first step because effectively, from the perspectives of everyone evaluating what a clue means, they can completely delete *Patch Finesses* from their brains.

**Comment by pianoblook** [comment]
Reposting this in the right thread:
------

At least speaking from personal experience, I think the problem comes from the Doc and the example given in the Strong Form. Could there be a couple specific Requirements, similar to _Out of Position Bluff_?

here's a stab:
> A _Patch Finesse_ should only be assumed if it is "Known" that a Fix is not intended or possible. Therefore, one of the following conditions must be true:
1. No clues remain to Fix, or only one clue remains and a Fix will result in losing something critical
2. _Blindplaying_ is currently being called for anyway this turn, from an apparent _Finesse or Bluff_ (or even 5CE etc)
3. The player who initially gave the clue has had a subsequent turn to _Fix_ but chose not to do so

**Comment by Zamiell** [comment]
adding more verbiage to the doc doesn't really solve the underlying problem. notice that most people don't bother to read the doc

**Comment by pianoblook** [comment]
Overall it would still be less verbiage. If Weak Form is deleted, the "[Stipulations](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#patch-finesse-stipulations)" can just be reworded to set really clear ground rules. Here's an attempt:

**Patch Finesse Stipulations**
- Expert players commonly perform Finesses with a Lie Component (and Layered Finesses with a Lie Component) in order to solve various tricky situations that come up. Since Patch Finesses are extremely rare, players should almost always assume a more-ordinary Lie Component that requires a Fix Clue instead of a Patch blind-play.
- Therefore, a Patch should **only** be assumed if one of the three conditions is true:
> 1. The player who initially gave the clue has had a subsequent turn to Fix but chose not to do so
> 2. No clues remain to Fix, or only one clue remains and a Fix will result in losing something critical
> 3. Blindplaying is currently being called for this turn, from an apparent Finesse or Bluff (or even 5CE etc)
- It is expressly illegal to perform a Patch Finesse that contains two Patch Components.

**Comment by Zamiell** [comment]
or we could just delete the strong form section, and delete the patch finesse stipulations section

**Comment by NoMercyO** [comment]
Between deletion and verbiage change with piano's stipulations i would vote the stipulations clarity. 
For me specifically the first one stipulation is a valuable one, as is the clarity to "almost always assume more ordinary lie component."

I am also ok with us redefining "patch finesse known form (illegal)" in the document. I think ive performed one strong form patch finesse that i believed was clear, (by intentionally not fixing on future turn and choosing to discard. It failed).

**Comment by Zamiell** [comment]
### The Known Patch Finesse (Illegal)

* Legal *Patch Finesses* are **always hidden**, meaning that from the person who is blind-playing a card to "patch" will **never** know that it is a *Patch Finesse* until **after** they blind-play.
* In other words, if Alice performs a legal *Patch Finesse*, then **no-one else on the team has to even know that the *Patch Finesse* convention exists** - everything will just work out properly because everyone will just blind-play cards like any other ordinary *Layered Finesse*.
  * The exception is when it comes time for the patched player to begin blind-playing. In this situation, the patched player might be "spooked" from the blind-play of the patcher, because they will not understand why the blind-play happened. In this situation, players need to have full trust and not be spooked by unexpected successful blind-play from other people on the team.
