### ISSUE TITLE
5CE Reverse Finesse Revisit

### ISSUE THREAD

**Issue by NoMercyO** [Zamiell/hanabi-conventions#341]
https://github.com/Zamiell/hanabi-conventions/issues/84

a) No changes, maybe some document clarity.
b) re-add clause stipulating reverse finesse that precendence over 5CE
c) OOP 5CE Ejection exception for reverse finesse (but normal case still is aw written)
d) Ban all OOP 5CE Ejection (or even all OOP Ejection).

I am inclined to vote for d, else b.

**Comment by NoMercyO** [comment]
Example of OOP 5CE Ejection, overriding ignoring reverse clause, and looking potentially like a true finesse

https://hanab.live/replay/263936/4

**Comment by Dr-Kakashi** [comment]
I'm against having a ban on OOP 5CE Ejection.  You can do "legal" OOP 5CE's.  Here are Some Examples.

![2020-05-25_1339_(OOP_5CE - Stacked Ejection)](https://user-images.githubusercontent.com/48993588/89623661-d9697200-d849-11ea-80f7-0859b13f192c.png)
![2020-05-28_2321_(OOP_5CE - No Ejection Slot)](https://user-images.githubusercontent.com/48993588/89623668-dec6bc80-d849-11ea-9b08-32e51f435350.png)
![2020-06-12_1347_(OOP_5CE - Negative Information)](https://user-images.githubusercontent.com/48993588/89623686-ebe3ab80-d849-11ea-84f0-b1ea00441b86.png)

I've read post #84 and I see that we removed reverse finesse's to remove head space and to simplify the convention.    

I do believe we should have some sort of stipulation of when 5CE's vs true finesse should be entertained.  In the example that NoMercy Provided, the true finesse should be entertained over a 5CE.  

Quote from NoMercy on Discord:
> No that analogy does not apply. What you are invoking is delayed play clues. 
>
> EG: Alice clues a green 3. 
> 
> a) No green cards. Bob plays slots 1 immediately and stops if the card does not match. Normal Finesse/Bluff.
> b) Green 1 is waiting to be played. Bob NEVER plays and always assumes finesse, perhaps layered.
> 
> This is the the logic being extrapolated to this situation, with double finesse taking precendence as the bluff could never immediately resolve (and so by extension the potential 5CE).

**Comment by Dr-Kakashi** [comment]
I've talked with Stephen further on Discord and what we're really referring to is:

https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-out-of-position-ejection
Bullet point #5
- Note that you are not allowed to perform Out-of-Position Ejections in reverse, unless it is super-obvious what is going on.

So what we're really asking here is a clarification to this?

**Comment by Zamiell** [comment]
> a) No changes, maybe some document clarity.

Specify what clarity you would like.

> b) re-add clause stipulating reverse finesse that precendence over 5CE

Still against, for the same reasons that I was against in #84.

> c) OOP 5CE Ejection exception for reverse finesse (but normal case still is aw written)

* For this situation, I prefer **not** specifying what to do in the document and let it be up to context and/or player's discretion.
* Reason: Players who perform the exceedingly rare "legal" version of the OOP 5CE are generally going to be expert players that are playing in expert-only games. And they can likely be able to figure out the correct resulting action.
* Reason: Specifying what to do in extremely niche situations clutters the doc, costs headspace, and is generally undesirable from the point of a doc maintainer.
* Reason: Sometimes it is **super clear** that a clue is an *OOP 5CE* and not a *Reverse Finesse*. Consider the following example:
  * Nothing is played on the blue stacks.
  * Alice clues blue to Donald, touching a blue 5 as a *Play Clue*.
  * Bob is locked. Bob performs a *5 Save* on Alice. (unrelated clue)
  * Cathy sees that Emily has a blue 1 in *Finesse Position*. Normally, Cathy would treat this situation as a *Reverse Finesse*, meaning that Cathy would have the blue 2, the blue 3, and the blue 4 on *Finesse Position*.
  * However, that is extremely unlikely. As an an expert player, Cathy uses both her knowledge of the conventions and analyzes the context of the game to see that it is much more likely that Alice intends a OOP 5CE on Cathy.

> Ban all OOP 5CE Ejection (or even all OOP Ejection).

Personally, I have use OOP 5CE sparingly. However, when I do use it (3-4 times so far), it has succeeded 100% of the time, and it has been super clear to the rest of the team. Thus, I think that they are fine, there's many other things to ban before 5CE.

I will reiterate one of my previous positions, since it is relevant:

**"Just because a complicated move exists in the doc does not mean that you should always use that move. Only use complicated moves when they are clear. Otherwise, choose a simpler line, or you risk losing the game."**

This is advice that we should give to any player that gets carried away with OOP 5CE.

**Comment by Zamiell** [comment]
I added this to the doc:

* Remember that just because *OOP Ejections* are technically legal in some situations, this does **not** mean that you should players should try to always use them. Just like any other complicated move, only use it when it is super-clear to the rest of the team. Otherwise, a simpler line should be chosen.
