### ISSUE TITLE
New Convention Proposal: The Flare Finesse

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#365]
So the concept of _Blaze Discards_ has really opened a whole new design space. These sorts of clues that trigger positional blindplays are just stupid-powerful. Feels like it's turning into a whole new 'class' of moves: **Ignitions**. Note how the classic _Double Ignition_ actually perfectly meets the same definition: the 'burn' clue 'ignites' one player to play the _Matching Finesse Position_ of the original "Declined Play Clue."

So, keeping with the illumation/burning metaphor, here's a new extension - mostly for Black/Dark variants, but also usable in some normal variant scenarios:

- If a color play clue is given to a newly touched card in the next player's hand - but that they know **cannot** be currently playable, this must be a true  _Finesse_ of some kind (since SCB on newly touched cards are almost always illegal anyway). OOP 5CEs, UTDs, and other shenanigans are also basically nonexistent.
- The player should look to see if another player does indeed hold the 'Target' card in a _Finesseable_ position...
- ...But what if they do see the single (usually critical/unique) matching card, but it's 'buried' behind trash and/or >1-away-playable card(s)? 

---------
**The Flare Finesse**
- In this situation, the team must react immediately to send an emergency signal to the _Finessed_ player about where their card is, to prevent the impending bomb.
- This is called a _Flare Finesse_: just like in a _Blaze Discard_ or _Shadow Finesse_, this calls for a Positional blindplay of the **matching Finesse Position** as the Target card.
- This _Flare_ blindplay will highlight the exact location of the matching card in their teammate's hand.
> In other words, this is basically an "inverted _Finesse_" for a critical/unique card.

- If the Target card is indeed critical (e.g. Dark suits), this can even work in Reverse: just like a _Reverse Shadow Finesse_, the clued player (always Bob) just needs to be sure that Cathy's _Matching Finesse Position_ is indeed playable as the _Flare_.
- This also works cleanly with the proposed [Mirage/Lucidity Bluff](https://github.com/Zamiell/hanabi-conventions/issues/350)
---------

Example:
All 2s are played. Purple 3 has been discarded.
- Alice clues purple to Bob, touching a card off-chop as a play clue.
- Bob sees that Cathy holds the only remaining purple 3, so he knows this **must** be a _Reverse Finesse_.
- That said, Bob also sees that Cathy's purple 3 is in her _Third Finesse Position_ and is buried behind a 5 and a trash card. Bob therefore trusts that Alice is actually performing a _Flare Finesse_
- Bob plays his (matching) Third Finesse Position to highlight which card Cathy should blindplay.
- Cathy GASPS in surprise, but knows exactly what has happened.

In-Game example:

![MarkusKahlsen goes first](https://user-images.githubusercontent.com/32303453/94356714-64533580-005f-11eb-80be-6d5f24265715.png)

> Markus clues black to Andrew_UK.
> Andrew knows this is finessing swineherd, but p5 will bomb.
> Andrew needs to send a _Flare_ by playing his _Third Finesse Position_.

￼

**Comment by pianoblook** [comment]
A couple notes:

- It's interesting that this works just as cleanly in normal suits when _Elimination Notes_ have been written for the second copy of a playable. The _Flare_ would still be necessary as long as the target isn't on chop, since the resulting _Elimination Finesse_ would be pulling the wrong card! 

- Unlike a _Shadow_, this should still work cleanly even if multiple cards are newly touched in the initial clue.

- This should play relatively well even if SCBs on new cards are instated. Obviously if the connecting card isn't on the board and the color clue is given, it's 100% a play clue of *some* kind (either a direct play clue or a SCB, via negative info). But if the critical connecting card is seen, this should take precedence (Finesse over Bluff! much simpler too.)

**Comment by Zamiell** [comment]
> If a color play clue is given to a newly touched card in the next player's hand - but that they know cannot be currently playable, this must be a true Finesse of some kind (since SCB on newly touched cards are almost always illegal anyway).

SCB will be legal following your PR in #353

thus, SCB would conflict with flare finesse - meaning that in this situation, players would use Occams Razor and almost certainly assume SCB over anything else

**Comment by pianoblook** [comment]
I dunno which way Occams Razor should really apply here though. 

I imagine I'd feel equally ambivalent if that statement were reversed, like if Flares were an understood concept and SCBs were being newly proposed ("thus, flare finesse would conflict with SCB when touching a new card - players would use Occams Razor and almost certainly assume flare finesse over SCB"). 

Here are the 'Pros' for the Flare interpretation as I see it:
- Keeps the spirit of "assume Finesse over Bluff"
- Helps gain tempo on the actual suit being clued
- Helps reinforce an emerging class of moves (Ignitions)
- Inherently more efficient: the Flare gets two blind-plays plus a fully known card, instead of one blind-play plus a bluffed card (marked as k234, e.g.) + ens for k1

Cons:
- More complicated; I can imagine SCB being more intuitive, especially if you're not really used to Blazes & Shadows
- Less common: The SCB form could occur more frequently since the clued card wouldn't necessarily have to be the exact matching card (although this could still work - and actually be a 4-for-1 - w/ a Flare Mirage)
- Convention bloat: I know you're always wary of stuffing more conventions into the mix and adding to people's mental overhead.

**Comment by Zamiell** [comment]
> I imagine I'd feel equally ambivalent if that statement were reversed, like if Flares were an understood concept and SCBs were being newly proposed ("thus, flare finesse would conflict with SCB when touching a new card - players would use Occams Razor and almost certainly assume flare finesse over SCB")

to clarify my position, I have historically used "Occam's Razor" as a term to mean that players should "assume the move that we've been playing with for the past 3+ years over the move that was invented last month", in the absence of actually having a dedicated term to convey that concept. I guess you could call that "History Bias".

"History Bias" is closely related to "Frequency Bias", where you "assume the move that happens in 1 out of every 20 games over the move that happens one out of every 1000 games".
these two biases are highly correlated to each other (with some exceptions like 5CE), because we've figured out all the common shit long ago and the only stuff left to add are conventions that explain what to do in super edge-case scenarios

**Comment by Zamiell** [comment]
expanding on this further, the new conventions that I like best are ones that have 0 overlap with any existing conventions.
this is for reasons that are probably obvious - they don't require existing players to rewire things in their brain.

if a new convention does have overlap, then a good default way to determine precedence is to just use History Bias and Frequency Bias.
this is a nice and simple mechanism. and notice that it is mostly unstated - players don't have to specifically coordinate on anything.

thus, I would consider it a "con" that existing players would have to memorize that a brand-new flare finesse would have precedence over a move that they are using already. imagine:

* Alice does a perfectly good SCB.
* Bob plays the wrong slot and the team loses the game.
* The team goes into the review and explains to Alice that the type of SCB that she did won't work anymore because the group implemented a new, more-complicated convention.

How would you feel if you were Alice in this situation?

**Comment by pianoblook** [comment]
Yeah I'm sold. SCBs are really sick already and this does indeed conflict.

Close it down!
