### ISSUE TITLE
Delete Trash Push Discharge

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#407]
it sort of conflicts with Double Ignition

**Comment by Zamiell** [comment]
i've not seen this move used since double ignition was invented
well actually to be fair i've never seen this move period, but my point remains

**Comment by piper0** [comment]
Not going to write out a full defense of the TPD right this second, but here's [an excellent in-game example of a pretty rad trash push discharge](https://hanab.live/replay/296125/36).

![image](https://user-images.githubusercontent.com/67833391/98771179-ada1df00-2398-11eb-8840-ed368647310c.png)

Note that r3 was fully known prior to this clue – g3 and p3 are the only newly-touched cards. b4 and r2 played in response to this clue.

**Comment by pianoblook** [comment]
By turning off Late Game Trash Push Discharge you'd be turning off **all** Late Game Trash Pushes (well, unless Cathy's *Finesse* is the same slot as her *Push*). This would kill the information channel for Cathy, since Bob playing slot 1 in response would just make her assume Double Ignition

Also, choosing to not clue exactly the card on Chop is *always* an option for Alice - I'll continue to strongly urge reconsidering the exact parameters of Double Ignitions (see #363 )

**Comment by Zamiell** [comment]
i will close this for now
