### ISSUE TITLE
delete positional finesses

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#425]
i am tired of losing to this, they only work 66% of the time, and sometimes cards are literally uncluable because any positional clue that you do looks like a finesse

**Comment by Zamiell** [comment]
would make #412 irrelevant

**Comment by iamwhoiamhahaha** [comment]
i don't have the problem with positional finesses

**Comment by iamwhoiamhahaha** [comment]
I'm fine with deleting this, but still I don't see the problem with it. I understand that a good convention should easily be read by most of the players, but maybe it's just because null is not a beginner-friendly variant. Those who can't read positional finesses should not play a variant with a null suit. It's not a problem of the convention itself but the players who play with that convention.

**Comment by Zamiell** [comment]
did you read the example i put in the doc?

**Comment by iamwhoiamhahaha** [comment]
no

**Comment by Zamiell** [comment]
then read it

**Comment by iamwhoiamhahaha** [comment]
okay i see. this is the cost of the positional finesse. i won't give this clue if it is turned on.

**Comment by Zamiell** [comment]
the cost sucks

**Comment by iamwhoiamhahaha** [comment]
fair enough
