### ISSUE TITLE
No assuming assymetric information exception

### ISSUE THREAD

**Issue by hakha3** [Zamiell/hanabi-conventions#434]
Its inspired by discussion about this [move](https://hanab.live/replay/371012#8) , where conventionally Lelouch should assume having r2 over assuming that hakha3 somehow knows that he has 3 and its self finesse. I think its fairly common that you can make self finesse, which to one of players will look suprising that it works, but I propose that they should assume that it will somehow work rather that they have another copy in finesse position, which they are expected to play. There are a lot of context possibilities like declined finesse, declined bluff, timing, which are more likely than that it was never self finesse. 

I dont have yet complete convention proposal, so far I was thinking something like
-when player isnt in bluff seat and he sees clue which looks like self finesse, but he doesnt know why wouldnt it be interpret as play clue instead, he should assume that there is enough context for other player to know it isnt play clue.

Im mostly unsure how many situation it should count. All, which would make it clear, but would involve situations where having enough context is less likely than that it was just finesse and not self finesse or try to define some conditions like "if having some card in your hand would be enough context that other player knows its not self finesse, you should think that there is enough context and dont try blind play". Also probably some note that player shouldnt assume which context let other player know its self finesse

**Comment by Zamiell** [comment]
in general, a goal of the conventions is to have them be simple and easy to remember.
that may sound surprising to newer players, because, for example, our *Priority* system is pretty complicated and has [a gigantic flowchart](https://raw.githubusercontent.com/Zamiell/hanabi-conventions/master/img/flowcharts/priority_flowchart.png).
however, the idea is that we do allow for some complicated things, but only if it provides a lot of value.

you can read more about [the meta page](https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Meta.md#head-space-convention), which introduces the concept of a *Head-Space Convention*

we don't want players to have to remember all kinds of exceptions and rules (e.g. Head-Space Conventions) unless there is a really good reason to. players routinely forget about *Head-Space Conventions* in the middle of the game, and it causes the team to bomb out and get a score of 0.

having players

1) sometimes assuming no async info in one situation and
2) not assuming it in a similar-situation

falls squarely into this category - to me it feels like it would almost never be worth adding extra complexity for the purposes of squeezing out an extra self-finesse 1 out of every 1000 games.

as a minimum baseline for your proposal you should be showing three or more in-game situations where having the convention configured this way results in a significantly better game state in order to prove that the convention will be generally applicable

**Comment by hakha3** [comment]
![image](https://user-images.githubusercontent.com/43155373/103162454-35c93000-47f1-11eb-89e7-baa64eefdfad.png)
When 4 is clued to jeff, hakha3 assumes he has 4 teal instead of g3 on finesse slot

**Comment by hakha3** [comment]
I got another [example](https://hanab.live/shared-replay/389284#21). Ricardodd clues green to i2 which would be self finesse if katian had g5. Katian instead of responding to clue assumes having g5 and that clue will work as self finesse.

This would 3rd one. In last 2 examples card which made clue work was already clued in player hand, but that shouldnt be necessary imo. Though it is some first step, which I feel many players already follow

**Comment by Zamiell** [comment]
since noone else has chimed in, i will close this now as part of spring cleaning

**Comment by hakha3** [comment]
In this [game](https://hanab.live/replay/409035#19) from hakha3 pov he has w2 or g3 finessed at slot 2 
![image](https://user-images.githubusercontent.com/43155373/105111172-a1d14800-5ac0-11eb-8cd1-5696d79343f4.png), so instead of not assuming he has w2 and thinking self finesse wont work and bombing slot 1, he should expect w2 to be at slot 2.

I havent seen yet clue which looked like potential self finesse, but cluer expected others to not assume assymetric information and assume its finesse/bluff on them

**Comment by Zamiell** [comment]
if hakha has a globally known g3/w2, then the clue works as a self finesse from good touch principle.
in other words, there doesn't need to be anything added to the doc in order to cover this situation

**Comment by hakha3** [comment]
hmm how does it work? I cant be certain I have w2

**Comment by Zamiell** [comment]
if the card is in a 50% superposition then it is not your responsibility to 1-for-1 dupe, the clue doesn't meet mcvp

**Comment by hakha3** [comment]
Im not sure I follow what do you mean by 0.5 for 1. w2 is already gotten

**Comment by Zamiell** [comment]
its not gotten from hakha's perspective
(1 for 1 + 0 for 1) / 2 = 0.5 for 1

**Comment by hakha3** [comment]
I meant card is gotten, hakha just doesnt know if thats w2 or g3. How do you get (1 for 1 + 0 for 1) / 2?

**Comment by Zamiell** [comment]
you need to add the probabilities together

read this and it explains https://www.statisticshowto.com/how-to-find-the-probability-of-two-events-occurring-together/

**Comment by hakha3** [comment]
but probabilities of what you are adding? What is 1 for 1 and what is 0 for 1?

**Comment by Zamiell** [comment]
1 for 1 if g3, 0 for 1 if w2

**Comment by hakha3** [comment]
Im sorry im still struggling seeing what 1 for 1 or 0 for 1 you see.

The way I see it is that if I have w2 its clean 2 for 1 (y1 and y2 plays in cost of 1 clue)
And if Im supposed to play my finesse slot then its still 2 for 1 (my blindplay + y2 marked in cost of 1 clue)

**Comment by Zamiell** [comment]
1 for 1 the clued card is w2 and slot 2 is g3, 0 for 1 if the clued card is w2 and the slot 2 card is w2

**Comment by hakha3** [comment]
but clued card is y2, so why are talking like if its w2.

**Comment by Zamiell** [comment]
because it is w2 by default from occams razor

**Comment by pianoblook** [comment]
To me this clue just serves to resynchronize the team - it should confirm that the blind-card is w2, because otherwise it's an awful clue 🤷

**Comment by hakha3** [comment]
but from indego pov its not superposition. Indego will never assume its 0 for 1

**Comment by Zamiell** [comment]
the premise of your hypothetical as stated is that the card is in a superposition, thus indego will assume that that is in a superposition

**Comment by hakha3** [comment]
Thinking this way seems wrong

Imagine all 1s and b2 is played. Alice clues 3 to Cathy. Bob discards. Cathy looks around table and see no b3 marked and is ready to play her card, but then she is getting remainded by voice in her head "consider others superpositions", so she looks around and see that Bob has r3 marked, which is in superposition of b3 and r3, so considering that superposition, if Cathy had b3, clue would be 0.5 for 1, so instead she assumes its self finesse and blind plays slot 1.
Is this what you think should happen?

**Comment by Zamiell** [comment]
> Imagine all 1s and b2 is played. Alice clues 3 to Cathy. Bob discards. Cathy looks around table and see no b3 marked and is ready to play her card, but then she is getting remainded by voice in her head "consider others superpositions", so she looks around and see that Bob has r3 marked, which is in superposition of b3 and r3, so considering that superposition, if Cathy had b3, clue would be 0.5 for 1, so instead she assumes its self finesse and blind plays slot 1.

that example is not analogous because the person without the superposition gives the clue, and in the previous example the person with the superposition gives the clue

**Comment by hakha3** [comment]
in the example from screenshot, Markus who doesnt have superposition gave 2 clue to indego

**Comment by Zamiell** [comment]
oh, sorry i was looking at the screenshot from the perspective of hakha giving the clue

**Comment by pianoblook** [comment]
> Cathy looks around table and see no b3 marked
cool, then she should play her 3 as b3. Bob didn't respond, and it was a play clue. therefore it's b3.

That doesn't have anything to do with your 3p screenshot - we are Bob in that case, considering whether or not to play y1 or trust he has w2 from the superposition w2/g3. If it was g3 then Alice just caused a bomb and it's not Bob's fault.

That's like asking whether hakha should blind-play slot 1 right now if Markus had given green to indego instead - no, they should (first) assume that this line makes it very likely that they do, indeed, have g3 and not w2.

**Comment by Zamiell** [comment]
here's my new take: in the screenshot, if hakha genuinely can't decide whether or not to play slot 1 or slot 2, then markus is giving a bad clue, and he should do something else

**Comment by hakha3** [comment]
> That's like asking whether hakha should blind-play slot 1 right now if Markus had given green to indego instead - no, they should (first) assume that this line makes it very likely that they do, indeed, have g3 and not w2.
I understand your point, its just that you mean you are searching for g3 starting from the card which is in w2/g3 superposition, though small detail in that game there is w2/g3 superposition bc 4 clue is given to hakha and it was either finesse w2->w3->w4 or g3->g4, so actually green to indego would cause first slot to play :P, but yeah I know what you meant. And anyway im on team that Bob should trust that self finesse will work

**Comment by pianoblook** [comment]
Just going through these examples now.

Your first example: it's 100% not m3 because Kyle could have cleanly finessed m3 with m4. Therefore hakha should (conventionally) assume a self-finesse on either r2, b2, or a2 depending on the response.

Your second example: yes, hakha is being promised t4, conventionally. This has nothing to do with async information: this 4 clue is a clever way to synchronize the team.

Third example: exactly, this promises g5. Once again, giving Bob more information about his previously touched cards is different than assuming asynchronous information.

Fourth example: As discussed above, Markus would not be allowed to give this clue unless hakha is promised w2 now

**Comment by pianoblook** [comment]
From my understanding (jump in if this doesn't quite fit Zam), you should *not* assume a self-finesse would work out if you don't already have a card touched/'gotten' that could match, or unless there's enough context for the clued player to know otherwise. 

Looking more closely at the first example (3s to hakha - question being should lel0uch assume they have r2?) - I think I'm actually swayed; they probably should assume a (non)"ambiguous" finesse rather than having exactly m4.

But really that's actually covered: what Kyle performed was a hidden patch finesse 😆

**Comment by Zamiell** [comment]
i think the point of the thread is that hakha is pushing back against "always assume no async info", and he wants there to be an algorithm so that he can safely play slot 2 in the screenshot.

but the reality of the situation is that most expert players will already play slot 2 in the screenshot because of the context of the game. codifying "context" into the document is difficult to do, and not very helpful besides

**Comment by pianoblook** [comment]
My main point/reply is that I don't think it's correct to think of most of these examples as 'assuming async info'.  We have plenty of conventions that rely on trusting no bombs will occur due to good-touch. So most of these self-finesse work *because* we don't assume async info: instead we assume everyone is in sync due to the cards already 'gotten' in our hand.

**Comment by hakha3** [comment]
so I have 2 points, first is to make sure that what piano said about if something in your hand marked could make self finesse work, then you should believe it does. Because for me with current conventions it isnt clear
Though here there is also interesting scenario:
Imagine r1 and b2 played. Alice clues 3 to Cathy to r3 with r2 being on her finesse spot. Bob has unknown 2 and 3 marked. I would prefer him to assume he has b3 instead of assuming r2, but I could see vouching for otherwise.

Second one is that sometimes you should just trust that self finesse clue which someone give will just work and you shouldnt respond. How often is "sometimes" Im not sure. Its def easier to set it as never than trying to come up with some conditions
