### ISSUE TITLE
4 Charm vs. Safety Charm

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#439]
I think *4 Charms* sort of conflict with *Safety Charms* with color clues.

#### Solution 1
* *4 Charms* can only be performed by rank clues.
* This solution preserves *Safety Charms*.

#### Solution 2
* *Safety Charms* can only be performed by rank clues.
* This solution preserves *4 Charms*.

### Solution 3
* It is illegal to perform a *4 Charm* by giving a color clue which touches only one off-chop card.
* This solution preserves *Safety Charms*.
* `off-chop card`: It is because *Safety Charms* can never be performed on a *Chop* card.
* `one card`: It is because *Safety Charms* are performed by 1-for-1 clues.

**Comment by pianoblook** [comment]
Solution 3 has been our go-to assumption. That gives the highest chance for high efficiency clues: all these Charms are therefore at least 3-for-1s

Technically a _Safety_ can be done on chop, as a declined 5 Double Pull :P but it would still not conflict because no one else would blind-play.

**Comment by iamwhoiamhahaha** [comment]
Apparently, *4 Charms* should always be done by rank clues if it touches two cards. The only situation where *4 Charms* can be performed by a color clue which touches two cards is it touches a 4 and a 5. That's because it's more like an *OOO Finesse* if the color clue touches 14, 24, or 34. Which means solution 1 might be the best solution and it is easy to remember.

**Comment by pianoblook** [comment]
Just realized this would also play nicely with #399 , if that ever becomes a thing. 4 Charm (touching multiple cards) has taken precedence in our games but I like your point about trusting OOO in those cases anyway!

**Comment by pianoblook** [comment]
Interesting example demonstrating the potential of rank choice, even if it's 2 away (not 3). if there's free choice between color and rank, this should trigger a charm (though double bluff should still take precedence I assume)

<img width="1240" alt="2 away charm example" src="https://user-images.githubusercontent.com/32303453/102570069-a74c0480-40b4-11eb-91fd-f9bb5ef2ac8f.png">

**Comment by pianoblook** [comment]
Couple small exceptions, fwiw:
- if the 4 is clued while on first finesse position
- if the 4 is clued while the player has negative 5 to its left

**Comment by pianoblook** [comment]
A nice in-game example that worked; no ambiguity bc the 4 was on slot 1

<img width="1195" alt="Screen Shot 2020-12-24 at 11 51 36 PM" src="https://user-images.githubusercontent.com/32303453/103119814-02e13980-4643-11eb-87a8-80847ca16b3c.png">

**Comment by pianoblook** [comment]
actually wait nvm, these are just a *lot* more common in rainbow + dual variants lol. This would work in all slots as long as multiple cards are touched

**Comment by iamwhoiamhahaha** [comment]
I think solution 2 is probably better since *4 Charms* are more common than *Safety Charms*. (I just did it today.) But players are allowed to perform a *Safety Charms* with color clues if it's known not to be a three-away 4.

**Comment by iamwhoiamhahaha** [comment]
I.e., we don't need to change the convention but just add this rule: "*4 Charms* take precedence over *Safety Charms*."

**Comment by pianoblook** [comment]
It seems strange to prioritize a Charm that gets a 4 touched + 1 play vs a 5 + two plays.

I think if a player needs to assume a 4 charm just occurred, Safety Charm would have to be deleted. That seems like a mistake, since it's always a 3-for-1 and seems to be pretty understandable by people I've played with

**Comment by iamwhoiamhahaha** [comment]
*Safety Charms* are not common since they are always 3-for-1. And that's reason why *4 Charms* should take precedence over *Safety Charms*.

This is the example I performed a *4 Charm* today. It is ambiguous if we don't define the rule I mentioned above.
https://hanab.live/shared-replay/382713#10

How should boba interpret my purple clue after frosty blind-plays his slot 4?  Is it a *4 Charm* or a *Safety Charm*?

![4 charm](https://user-images.githubusercontent.com/50160641/103154562-0efc0100-47d3-11eb-86cc-a9be855ca6d2.png)

(Image 1: 4 Charm Interpretation)

![safety charm](https://user-images.githubusercontent.com/50160641/103154563-13c0b500-47d3-11eb-8def-e1f9c2019181.png)

(Image 2: Safety Charm Interpretation)

I believe we should define that it is illegal to perform a *Safety Charm* if it looks like a *4 Charm*. Since it requires three cards to satisfy the condition, which is rare. And we can just do the 5 pull in that situation, which is clearer, even it is just a 2-for-1 not a 3-for-1.

But note that we can still perform a *Safety Charm* if it can't be a *4 Charm*. Look at the example below, if purple 1 is played on the stacks.

![safety charm 2](https://user-images.githubusercontent.com/50160641/103154566-18856900-47d3-11eb-85fa-bb0fe65924a4.png)

(Image 3: Legal Safety Charm)

**Comment by pianoblook** [comment]
Just saw a game where a very clear declined pull occurred but it was misinterpreted as a 4 charm. Neither of these conventions are good if we can't all agree on a good compromise.

After more reflection, here's my vote, for a good mix of flexibility + simplicity + power:

Rule 1: If a SINGLE card is touched with color and a _Charm_ occurs, Declined 5 Pull has priority (when possible, ofc)
Rule 2: If MULTIPLE cards are touched with color and the focus is on a 3-away 4, Bob should still assume a _Charm_ over a true _OOO Finesse_ **as long he would still need to blind-play 2 cards in total to make the _OOO_ real.
And obviously all Rank clues already function cleanly as is.

**Comment by pianoblook** [comment]
A couple recent examples of why this current lack of clarity has caused problems:

https://hanab.live/replay/386848#1
- pianoblook figured "well since it does touch 4 *and* 2, maybe I just have x1-o1-o3 and this is a true _OOO_
- In hindsight, I think that's really silly and I absolutely should still _Charm_, even though the 2 is touched as well.

https://hanab.live/replay/387453#1
- kimbi assumed this was a 4 after the Charm
- I wasn't there for the review, but that seems very sad to 'turn off'


The main reason why I think Declined Pull needs to take priority when a single card is clued is because **that's the only way 5 Pulls work anyway**. If we give 1-for-1 4 clues priority over that interpretation, I suspect true 5-Pull Charms will be close to nonexistent

**Comment by pianoblook** [comment]
Last thing I'll add: I think 4 charms are just not very useful unless they can have the ability to touch multiple cards anyway. Being able to touch, say, b4+b3 with color and get a Charm feels *great*, and the idea that it should actually be treated as a real _OOO_ seems (1) unlikely (it still requires 2 blind-plays from a single hand) and (2) inherently needs a Fix clue anyway, so is kind of clunky to have that be the first assumption

**Comment by iamwhoiamhahaha** [comment]
*OOO Finesses* took precedence over *5CE/5CD* when it was invented because I didn't want to make it conflict with the current conventions. However, it turned out that the 5CE is very powerful and common then we defined the `two or more blind-plays rule`. For the same reason, I didn't want to kill *OOO Finesses* and *Double Finesses* when I extended *4 Charms* to all variants and defined them with `three blind-plays rule`. But if it has been proved to be more common and powerful, I believe we can extend the rule, says `two or more blind-plays rule`, and make it consistent with other conventions.
Note that they still follow `two or more blind-plays rule` in the *Variants with No Positive Clues*.

**Comment by iamwhoiamhahaha** [comment]
For *Safety Charm*, it's an interesting convention that I didn't want to kill it. But just keep in mind that it is not very common since it requires *three* cards to satisfy the condition:
* A playable card on next player's fourth finesse position
* A playable card which is next to a 5 in another player's hands
* Also, "5 pulls" can be read from both player's perspective (the next player and the player who receives the clue)

That's why 5NDs are less common than 5CE for the same reason.

**Comment by iamwhoiamhahaha** [comment]
https://hanab.live/replay/388191

There are some players use *4 Charms* which follow `two or more blind-plays rule`, i.e., they take precedence over *OOO Finesses*.

**Comment by pianoblook** [comment]
> But just keep in mind that it is not very common since it requires three cards to satisfy the condition:

We're not making these decisions just based on what's  "less common" though. In making all these conventions, (my understanding is that) we're trying to maximize for a mix of (a) strategic macro-utility and (b) simplicity/comprehensibility. Both are important for improving overall winrate.

Instead of thinking "which is more common", the real question to ask is "which will be **more commonly optimal**"?

lol this will be my final post about this, then I'll rest my case and accept whatever is decided.

- 4 Charms in general are really powerful and useful tools. Remember the only thing in question here, though, is whether it should take priority *in the specific instance* where a single card is clued, *with* color, that *also* already can't be a 5-pull. 
- In those specific instances, the 4 Charm would always be a 2-for-1. This means that even if it's common to be **ABLE** to perform that move, I doubt it would very often be the **OPTIMAL** thing to do.
- >This is especially true when you account for the fact that the _Charmable_ card will usually be on Chop anyway, so if you're just looking for a good 2-for-1 you can frequently just clue that card directly as long as you can pick up at least a second card in the process. And importantly, I'd argue, cluing those cards directly would very often be more beneficial than doing this weird single-touch 4 Charm).

- So with all that said, here's my final argument: 
> - While this specific 2-for-1 _4 Charm_ is good, it's almost never really exciting and powerful. Even if the *opportunity* happens frequently, that doesn't mean that it's *the optimal* clue to give* frequently.
> - By contrast, **a Declined 5-Pull will _always_ be a strict improvement over a normal 5-Pull** (minus the rare double-2-offchop-5 situation lol). 5-Pulls are already very common and often utilized, and Safety Charms are just always a full extra blind-play on top. So, even if *the opportunity* is less frequent, it **will** very often be the optimal move on the board.

**Comment by Zamiell** [comment]
> In making all these conventions, (my understanding is that) we're trying to maximize for a mix of (a) strategic macro-utility and (b) simplicity/comprehensibility. Both are important for improving overall winrate.

right, but if a move is super common then b is very well satisfied.
weak prompts are super simple, but they almost never happen, so when they do happen players forget they exist and lose the game.

> 4 Charms take precedence over Safety Charms."

i agree with this.

furthermore, I've yet to see a safety charm, and with 4 charms being a thing, they are even less likely to occur. thus they are a candidate for deletion

**Comment by Zamiell** [comment]
i added a line to the  4 charm section and the safety charm section that explicitly mention the precedence
