### ISSUE TITLE
When bluffs were moved to the higher levels than clandestine finesses, their interactions with clandestine finesses were removed from the doc.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-conventions#444]

**Comment by Zamiell** [comment]
can you link the relevant commit

**Comment by hanabirnoob** [comment]
Pretty hard to search for the commit where "beginner/intermediate/advanced/expert" was changed to level numbers.

**Comment by hanabirnoob** [comment]
Here we go!

 https://github.com/Zamiell/hanabi-conventions/blob/5a1d2fbe12085622ebc42e37ed4ac71d5e59f4ac/Reference.md#level-4---expert-strategies

"Since we are allowed to lie in Bluff Seat, doing a Layered Finesse in Bluff Seat typically won't work. Instead of getting a big layered chain of cards, it will be interpreted as a Bluff, and only one card will be played. However, note that a Clandestine Finesses can get around this restriction, because it induces a potential misplay. The blind-playing player must continue to blind-play cards, or else the player receiving the clue will assume that the Finesse is "over" and will play the clued card."

**Comment by Zamiell** [comment]
iirc i deliberately deleted that passage because it wasn't very useful:

- if you are learning about clandestine finesses, then you don't know what a bluff is yet. 
- if you know about bluffs, then you already understand the mechanics of how a 2 that plays into a 3 will look like a *Finesse* and the card will bomb

**Comment by Zamiell** [comment]
good looking out though
