### ISSUE TITLE
Unknown Trash Blast (Declined 5ND)

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#447]
This isn't a meme, I just love 3player and think this is pretty sick.

## Unknown Trash Blast ##
- This convention only applies in the _Low Score Phase_
- If a single trash card is clued as _Unknown Trash_, normally this would call for a _UTD_.
- But what if the next player can see that this trash card could have just as simply been used as a _5ND_? In other words, what if the card directly to its left is a 5 that could have been clued with rank to trigger a 5ND?
- Sometimes this may be intentional, since Bob should respect that perhaps this _UTD_ is _Unnecessary_ and therefore will serve as an _Unnecessary Trash Clue Chop Move_ on Cathy's hand. But what if Cathy's (current) chop is also trash?
- In this case, Bob must be being called to play something else, as a _Declined 5ND_.
- If Bob plays his _Fourth Finesse Position_, this would look like a _Safety Charm_.
- Therefore, Bob must _Blast_ to signal that (a) the card is trash while also (b) that this was a Declined 5ND
- Cathy can comfortably mark her clued card and her rightmost unclued card as both _Known Trash_, plus the card to the left of the trash as a known 5

**Comment by pianoblook** [comment]
Actually this requires one update; this could be intentional if Alice is trying to do an Unnecessary UTD Chop Move on Cathy's cards. So I'll add that this should only occur if Bob sees that Cathy's chop is trash, and therefore this is truly unnecessary

**Comment by pianoblook** [comment]
This also has potential use in 4+ player. Call it an _Unnecessary blind-play_ or a _Blast wrap-around_ or w/e, but check this out:

> All 1s are played
> Donald's hand is r5 b1 x g1
- Alice clues blue to Donald
- Bob _Discharges_
- Cathy sees that this was very strange, because Alice should have used the 5 clue to Donald as a 5ND
- Cathy can see that this was an _Unnecessary Trash_ move. If nothing further were to occur, Donald would _Trash Chop Move_ his rightmost cards, which is clearly not the true intent of the clue.
- Therefore, this _Unnecessary_ move is actually calling on Cathy to blind-play slot 1 as an _Unnecessary Unnecessary UTD_
- After all this, Donald can mark his slot 1 as a 5, and his chop card as known trash

**Comment by pianoblook** [comment]
5p example:

<img width="1271" alt="Screen Shot 2020-12-22 at 5 23 13 PM" src="https://user-images.githubusercontent.com/32303453/102938469-62d8b400-447a-11eb-9b70-946131599869.png">

**Comment by jakestiles** [comment]
Not in favor. Also it seems like a bad 5 player example since that portion of the game went perfectly efficiently and clearly without need of the new tool.

**Comment by hanabirnoob** [comment]
I assume it can be integrated into moveset.

**Comment by Jayhui-q** [comment]
Wow, when we engineered ways to get slot 5, we also called it a blast! Talk about independent innovation and landing on the same terminology. 

I quite like this idea, and more so for 3 players. I suppose this would only work if it's a 1-for-1 UTD and not a 2/3-for-1 UTD, as that would pick up other good cards too, and might be better than the 5ND.

The concern I have with this is when there are lines that use the 5 for something else. 

Perhaps Alice declines to give the 5ND because:
- It can be used for a trash pull (or finesse), BCME, 5CE, 5ND, declined 5 pull charm later (also note that it is more likely that a newly drawn card makes the UTD impossible on another round rather than making the 5ND impossible)
- The negative information was valuable for chop moved or previously clued cards

The info of whether declining the 5ND was valuable as well can totally be asymmetric. For example, say the red 1 is on the stacks and Bob has:
b2 r1 b1 x x 

If Alice had given the 5ND, she may not have an ejection option later, whereas a UTD would be necessary (and not cause a chop move), and the 5CE can be done cleanly on the next round.

**Comment by pianoblook** [comment]
Great points. Interesting stuff, hmm. 

I'm inclined to scrap this then in favor of keeping the flexibility of future 5NDs/5CEs then, as you say. But I'll keep this open in case others disagree

**Comment by Jayhui-q** [comment]
My logic is a little inconsistent with the fact that declined 5 pulls exist! I used to intentionally not give 5 pulls when I saw that I could/needed to eject/discharge with it later (but now that's illegal!). Definitely some pros and cons to either way, so definitely keep this open! This is totally safety charm logic but one more step into the water.

**Comment by Zamiell** [comment]
too rare
