### ISSUE TITLE
Magic Finesse

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#451]
It's like the 5th time I saw this move. But I need to dig in my replays to find the examples.

### Magic Finesse
* In an expert game, if someone performs a *Finesse* and the player who is *Finessed* refuses to play their *Finesse Position*, they are intended to do a *Magic Finesse* on the player who does the *Finesse*.
* In this situation, the player who gives the original clue is promised to have the finessed card on their *Finesse Position*.

#### Example 1
* Replay: https://hanab.live/replay/384563
* Turn 11: It is a finesse on the green 4 since o2 was gotten from the early finesse.
* Turn 13: piano discards yellow 2 instead of playing the green 2.
* Turn 15: IAMJEFF trusts that piano was not making a mistake. It must be a *Magic Finesse* on him! Thus, he blind-plays his *Finesse Position* as a known green 2. (It's a magic, since IAMJEFF was finessing himself in turn 11 lol.)

**Comment by Jayhui-q** [comment]
Oh, this is a neat idea! Though, I'm actually not super sold on how this works. Is it purely contextual that the y2 discard is so bad for the team that it tells Jeff that he has the g2 on finesse?

Had it been a finesse using a g3 instead of a g4, then I'm not so sure the delay of refusing to play g2 is that weak, especially if piper had criticals (and possibly avanderwalde too). 

The generation of the clue in the example might also be really valuable on a game-by-game basis.

The codification of this makes me worry about players discarding to pass it back when the finessed player is genuinely layered.

**Comment by pianoblook** [comment]
The reason it works is because pianoblook wouldn't be allowed to discard otherwise: by not responding to the finesse, normally this would risk avander blind-play as an Ambiguous Finesse.

...unless avander can see the other copy in Jeff's hand :P

**Comment by Jayhui-q** [comment]
Oh... *facepalm*. 
I think then an addendum might be:
- If the finessed player discards and it is not an emergency situation, then it must be a magic finesse! 

Would also add the rationale that piano provided if it does get added to convs. 

Does this also apply to plays rather than discards? Such as piano playing y2 on that turn. 
Or would we say that that would cause priority instead (if g2 was globally known)?

**Comment by iamwhoiamhahaha** [comment]
To be honest, I came up with this idea from common mistakes in beginner games. They missed the finesse and thought the finesse was on the player who gave the clue (terrible mistakes). And when I blind-played my slot 1 (kind of a punishment lol), it was usually a playable card (either the matching card or another playable card). Apparently, we can also made *Magic Bluffs*.

**Comment by iamwhoiamhahaha** [comment]
Yeah it looks like players can only perform this move if they are occupied or having a known trash in hand.

**Comment by NoMercyO** [comment]
Can the magic pass back be declined? 

If the pass back is accepted does the original finesse receiver know the original clue must be a certain finesse, and never layered or a bluff?

**Comment by Zamiell** [comment]
not a fan. also, that is a terrible thing to do to new players

**Comment by Zamiell** [comment]
in the example given, what is the benefit of passing g2 to jeff?
it gets 0 new cards, and just introduces more vectors for mistakes

**Comment by pianoblook** [comment]
> in the example given, what is the benefit of passing g2 to jeff?
looking back through the review, it was for a couple reasons:
- piper just did a Sarcastic Finesse on y2, so it seemed nice to discard y2 asap
-  jeff might have just OCM'd his g2 and I was afraid he would therefore feel locked. that felt like good enough reason to force him to play g2

**Comment by Zamiell** [comment]
those do not seem like sufficient reasons to invent a brand new, confusing convention

**Comment by Zamiell** [comment]
also I will point out that in the game linked, you all bombed out with 3 strikes

**Comment by iamwhoiamhahaha** [comment]
we bombed out which is unrelated to magic finesses

**Comment by iamwhoiamhahaha** [comment]
i have some examples but i just couldn't find them. it's really hard to dig in my 10k replays (including pokemon accounts)

**Comment by Jayhui-q** [comment]
I'm starting to lean against this convention:

I wrote earlier: "If the finessed player discards and it is not an emergency situation, then it must be a magic finesse!" 

This seems like more of an emergency move rather than normal play and passing it back to the same person.
As you put it: "Yeah it looks like players can only perform this move if they are occupied or having a known trash in hand."

If they are occupied, I would say they are desperately doing a priority move. 
If they have known trash, I would say they are screaming.

**Comment by Zamiell** [comment]
seems to be me + jerry against jeff + piano.
closing since only one example was provided and the usefulness of this hasn't really been demonstrated

**Comment by iamwhoiamhahaha** [comment]
another example for the magic finesses: https://hanab.live/replay/595094#12

**Comment by Dr-Kakashi** [comment]
Jeff asked me in discord and I just realized it's probably best to put my thoughts here:

What's basically happening?
It's just another form of Gentleman's discard with a caveat. The card is not discarded because you can be layered.
The layered component is important for this discussion because you should consider those cases.

If you choose to not consider layered cases, then you're saying that the person who doesn't play into the finesse must know their slot 1 is the card, which is super rare on top, while requiring high level context reads. If they are 100% confident that it's in their slot 1, then they just discard it performing a normal Gentleman's discard or do something else. The con to this, is that if the read was wrong, then some other playable card is discarded (hopefully not a playable 5). 

If you choose to consider layered cases, then you must consider cases where the clue giver is also layered. This is the main reason why Gentleman's Discard is done, in order to get more cards for free at the cost of tempo. 

If you are layered and pass the finesse, then the team must spend clues to re-get those cards. This means the team would've been better off using those clues to get cards from the initial clue giver's hand to begin with. 

That means, the efficiency essentially cancels each other out, which means it's a worse convention than regular Gentleman's Discard.

Knowing this, then when should it be done and if that is the case, would it be beneficial to the team?

The only thing I can think of, in my mind, is a super edge case where the clue count is 0 and where the player, who gave the clue, may discard a critical card and the team has no possible way to save that critical card.

I don't think you can find the 1 in 1,000 where it could be done, in addition to it being beneficial to the team. 

To push it home the two games presented here just didn't warrant passing their cards to the clue giver. 

The first game there's no urgency to have Y2 played, since there are two Y3's visible and not in any danger of being discarded.  Even if Jeff did CM his g2, it wouldn't cause problems for the team. 

The last game, I personally ran the hypothetical and the game is still won playing normally without passing.

**Comment by Dr-Kakashi** [comment]
Now, if you asked me what I would do if I gave a clue and someone performed a magic finesse on me? Without reading this proposal, I would've naturally blind played, once it got back to my turn. Assuming I trust everyone and everyone at the table were high level players.

**Comment by iamwhoiamhahaha** [comment]
a standard mistake which initiates a magic finesse
https://hanab.live/replay/769936#4
