### ISSUE TITLE
Disease Bluff rework: Fevered Bluff

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#452]
I've been sifting through deleted conventions, and Disease Bluffs look exciting. It was deleted for being "inefficient", but that's because it requires a second clue...

## The Fevered Bluff ##

- If a _Bluff_ occurs that immediately look like a _Self-Finesse_, this used to require a _Heal Clue_ (as a [Disease Bluff)](https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Deleted_Conventions.md#the-disease-bluff)
- This was deleted because the 'fix' itself required a second clue, which made it rare to be efficient.
- But what if the 'fix' was actually an _Ignition_ blind-play, just like _Blazes_ and _Shadows?_
- Therefore, the very next player should _Ignite_ their hand, and blind-play the matching finesse position of the real matching card seen elsewhere.

This now becomes a 4-for-1 instead of the old 3-for-2. 
There is some friction with _Pestilent Double Bluffs_ I suppose, but this sort of Self-Finesse-into-Pestilent seems quite rare. 
'Disease Bluff' still works as a name, but 'Fever' at least sticks with the 'heat/fire' theme.

**Comment by Jayhui-q** [comment]
Fascinating. Does the re-introduction of this conflict with a pestilent double bluff?

For example, in line with the given example for diseased bluff:
- It is the first turn and nothing is played on the stacks.
- Alice goes first.
- Bob has a red 1 on slot 1 and a blue 2 on slot 2.
- Alice clues number 2 to Bob, touching a blue 2 on slot 2.
- Bob does not see any other 1's on Finesse Position. Thus, the number 2 clue must be a Self-Finesse, so he blind-plays red 1.
- Cathy comes next. From her perspective, Bob should currently think that his slot 2 card is red 2 (instead of blue 2). 

I think the way we currently play is Cathy plays slot 1. Even though it can't be a 1 (as Bob wouldn't have played if he did), Cathy might be playing the matching red 2 instead.

Would your convention demand a different slot instead?

Also, I'm not sure what you mean by the real matching card seen elsewhere, is it the card that plays into Bob's clued card, or the card that his finesse played into?

That is, if Bob had a blue 1 on slot 4, would Cathy play the matching finesse position?
Or is it if any player, even say Donald, has a red 2, that Cathy should play the matching finesse position?

I personally am a huge fan of how pestilent clues currently work. The blind-play of the finesse position heals the situation by itself.

**Comment by pianoblook** [comment]
yep, it would only conflict with that scenario, where cathy's slot is exactly the matching 2 of the 1 that got bluffed in the first place, lol.

My argument would be that it isn't that big of a loss in that very specific situation because (A) Alice could have just found some other double bluff to start with, and (B) this improvement would still be a 4-for-1 vs 3-for-1 when it does work.

So the pros & cons:
CONS: this is less efficient whenever Alice wouldn't have a different way to double bluff the cards *and* doing the true finesse on Cathy's 2 would only be a 2-for-1 total.
vs.
PRO: this is more efficient as long as *anyone else* has the true matching 2 anywhere in hand, as long as Cathy has a matching-position playable.

Both sides of that seem fairly low probability, to be fair, but this seems more flexible + powerful

Maybe always assuming a Pestilent is just simpler though. especially in brown variants

**Comment by Jayhui-q** [comment]
It's confined to r2 only in the no-stack situation. If all stacks are up to 3s except for red and blue, and the same maneuver were done, then Cathy could also have any of the playable 4s.

That is, for every pestilent bluff, the person blind-playing the second card can actually be any playable card greater than the clue given (as otherwise, Bob would likely entertain a reverse finesse). Cathy can play the number equal to the clue given only in the case of them both matching. 

As such, I would remove the "and' part of your CON, and I think the con really gets bigger. 

The pestilent is neat as a 3 for 1, and can avoid situations of bad-touch on Cathy (for which the straight finesse is insufficient).

**Comment by pianoblook** [comment]
Well these normally wouldn't work once the stacks are uneven anyway, right? like if Bob gets a 2 clue once one or more 1s are down, he shouldn't assume self-finesse anyway.

But, I agree that maybe this is more hassle than it's worth. Feel free to shut this down if you want Zam

**Comment by Jayhui-q** [comment]
Hmm, I'm not sure what you mean!
- Green 3, Yellow 4, and Purple 2 are on the stacks. 
- Nothing else is clued
- Alice clues a 2 clue to Bob's blue 2. 
- Bob sees that there are no 1's that are on finesse, or can be gotten via a layered finesse. 
- Bob knows it must be on him, and blind-plays red 1.
- Cathy sees that Bob has now incorrectly labeled his hand, and Cathy is now being asked to blind-play to signal that the action was pestilent. 

Cathy can be playing Green 4, Yellow 5, Purple 3, or Red 2.

Maybe I'm goofing and missing something about the scenario.

**Comment by pianoblook** [comment]
To rephrase: if there's at least one playable [x], you normally couldn't clue an [x] to Bob to initiate a Self-Bluff (Pestilent or otherwise). 

So I just mean there's still a restriction whether or not we're using Self-Pestilent or Feverish. 

*But* your point holds that there can be times when other stacks are higher but a self-finesse still works, in which case yeah there are more chances of Cathy's slot 1 being some other playable (not just the 'real' matching 2, in the turn 1 example)

**Comment by Jayhui-q** [comment]
Ah, gotcha! That's my misunderstanding. 

The last remark I'll make is that the clue itself can be convenient in moving the finesse position. 
For example, if r1 was on Bob's ejection slot instead and b2 was on finesse, the pestilent double bluff replaces what would normally be an impossible red finesse or 4 double bluff. 

It is interesting though. If the deal is a classic deal and cards play on the stack as expected, then the chances that Cathy's slot 1 is playable gets increasingly low. (A 4 for example only works if Cathy has playable 5's and there are no 3s on the stacks.)

My personal opinion is that keeping pestilence consistent rather than making it split off based on whether it is a self-bluff may reduce confusion and mistakes, but I'd love to hear other thoughts about the absolutely bonkers efficiency of the fevered bluff vs. the likelihood of a pestilent self-double bluff.
