### ISSUE TITLE
Discussion: Define interaction of LPC and Low Score Phase for one-off-chop 5 clue

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#476]
As currently being discussed on Discord, there seems to currently be a small gap in how to interpret a 5s clue in the following scenario:

> Hard Variant
> Still Low Score Phase, but NOT Early Game
> Bob is _Loaded_, and Alice clues him 5 one off-chop (while not in DDA)

How should Bob interpret this clue? We're having trouble reaching a consensus, because there are three conflicting possibilities:

1) It's a normal 5CM: this conflicts with the normal LPC convention
2) It's a direct _Play Clue_ on the 5: this conflicts with the _Low Score_ convention (no 5 play clues allowed)
3) It's a 5 Pull: this conflicts with the historical convention that 5 Pulls only occur while 2+-away from chop, since otherwise 5CM traditionally takes precedence.

What do we dooooo

**Comment by Zamiell** [comment]
historically the way we have played is that it is a 5cm

**Comment by pianoblook** [comment]
> historically the way we have played is that it is a 5cm

I'm surprised it hasn't historically been read as a LPC on the 5. I've seen plenty of LPCs on 5s even when directly on chop, no?

**Comment by Zamiell** [comment]
it could be a finesse on the 5, it just depends on the game.
1) if they wanted a finesse, they would (probably) just use color instead of a number 5 clue, so that fact usually stops the finesse interpretation.
2) every player sees that that they would have to blind play 3-4 cards into a finesse, which is very unlikely, so they prefer a 5cm interpretation

**Comment by Zamiell** [comment]
if a player sees that
1) color isn't available and
2) they only have to blind-play 1 (or potentially 2) cards into a finesse, and
3) the chop moved card isn't valuable
they they will probably treat it as a finesse

**Comment by pianoblook** [comment]
Couldn't the same be said about saving, say, a 3-away critical 4 on someone's chop? If it currently 'should' be interpreted as a Loaded Play Clue I'd expect Bob to still be called on to blind-play.

In that case, the fact that the player was loaded would have resulted in a _Bluff_ instead of a save. So what's to stop this from being a _Pull_ (a single blind-play) rather than a save (a 5cm)?

Anyway that's my argument for 5-pull at least. If 5cm will lead to less confusion / has a historical precedent, I suppose I won't mind 5cm being the agreed on interpretation

**Comment by Zamiell** [comment]
> Couldn't the same be said about saving, say, a 3-away critical 4 on someone's chop?

not at all, you could have the same 4 on your chop currently

**Comment by Zamiell** [comment]
i think of the 3 options in the op the 5 pull option is least likely interpretation, just because it is so bizarre and doesn't really match anything else (outside of the esoteric and rarely used 5 double pull convention)

**Comment by Jayhui-q** [comment]
In my opinion, the 5 clue is a 5CM. The way that I have usually been able to retain some ability to dictate what cards are being saved when a player is loaded is by using chop moves (like a trash chop move, and like this 5CM). For hard variants, when there is no DDA, I find this to be particularly valuable.

There's also an argument to be made that a 5CM actually isn't an early save (which is what LPC prevents). 

For example, suppose in a 3-player game, Bob has 
clued playable - x - unclued playable - 5 - matching card of Cathy's chop.

If Alice is barred from giving the 5cm this round, we will likely lose the unclued playable.

Granted, what are the chances? Instead of the matching card on Cathy's chop, Cathy could also be loaded, has a matching card (say an unknown 2, so that she doesn't know the urgency of the situation), or there weren't enough clues, or we want to give Cathy the opportunity to focus the card correctly with chop focus. 


I don't think the pull option is as attractive, it implies that the card on chop is a playable card, which means
1. if the 5 matches the color, giving a direct color play clue is a 2-for-1
2. You give that player the opportunity to give a priority finesse/bluff
3. Turns off BCME options
4. if the 5 doesn't match the color, you could discard and let someone else clue a 5 for a 5DP, or have someone else eject/discharge/charm it

Also conventionally, the 5 pull is a delayed play clue, which could definitely cause some issues depending on other player's hands. It might be easier to force them to play it with some other special move

I also am personally against the finesse read, just because color is a great choice for that usually.

**Comment by pianoblook** [comment]
> In my opinion, the 5 clue is a 5CM. The way that I have usually been able to retain some ability to dictate what cards are being saved when a player is loaded is by using chop moves (like a trash chop move, and like this 5CM). For hard variants, when there is no DDA, I find this to be particularly valuable.


That's a nice way to think of it - sold!

**Comment by pianoblook** [comment]
Looks like the [doc](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#loaded-play-clues-in-hard-variants-part-2) currently has this as always being a LPC on the 5: 

> Loaded Play Clues also apply to the 5's Chop Move. This means that any clue that looks like a 5's Chop Move will instead look like a Loaded Play Clue (if the clue receiver is currently "loaded" with a play).

**Comment by Zamiell** [comment]
that was written prior to #260 iirc

**Comment by sjdrodge** [comment]
I've given some of my input elsewhere already, but I'll recap here. LPC is definitely the historical meaning in this situation, but things have been complicated by the new rule about no 5 play clues w/ number in the Low Score Phase.

However, after thinking about this more, I'm convinced that LPC is still the correct meaning for this kind of clue. A normal on-chop 5 save becomes a play clue when given to a loaded player. To my knowledge, nobody would argue that this kind of play clue is banned because of the "no play clues w/ number 5 in LSP" convention (please correct me on this point if I am mistaken). The situation with 5CMs seems perfectly analogous to 5 Saves, so play clue is the winner.

**Comment by sjdrodge** [comment]
Okay, after even more discord discussion on the matter, my vote is just to go hard on "no number 5 play clues during LSP" and therefore allow both 5 Saves and 5CMs to loaded players during LSP. This has major benefit of cutting down on the number of mistakes that can be made in these situations.

**Comment by Zamiell** [comment]
> my vote is just to go hard on "no number 5 play clues during LSP" and therefore allow both 5 Saves and 5CMs to loaded players during LSP. This has major benefit of cutting down on the number of mistakes that can be made in these situations.

agree, everyone knows how much i like cutting down on mistakes

**Comment by Zamiell** [comment]
### Loaded Play Clues in Hard Variants (Part 2)

- As an exception, *Loaded Play Clues* never apply to clues that look like they could be a *5's Chop Move*.
- For example, in a 3-player game:
  - Red 3 is played on the stacks.
  - Bob has a known red 4 in his hand on slot 5.
  - Alice clues number 5 to Bob, touching a 5 on slot 3.
  - Bob knows that he is *Loaded*, because he has a red 4 to play. Bob knows that normally, no-one else is supposed to give *Save Clues* to *Loaded* players (and that they should be transformed into *Play Clues*).
  - However, Bob knows that this rule doesn't apply to the *5's Chop Move* and that players are allowed to perform a *5's Chop Move* whenever they want.
  - Thus, Bob marks his slot 4 card as being *Chop Moved* and plays the red 4.

**Comment by sjdrodge** [comment]
I do not believe the accepted convention matches the group consensus. This was always about the Low Score Phase. Presumably a play clue to a 5 is still permitted during the Normal Score Phase, but the accepted change indicates otherwise. Furthermore it makes no mention of the treatment of 5 clues to chop during the Low Score Phase, which is a point under discussion as well.

**Comment by Zamiell** [comment]
- *Loaded Play Clues* **do not** apply to number 5 clues during the *Low Score Phase*.
- For example, in a 3-player game:
  - It is the *Low Score Phase*.
  - Red 3 is played on the stacks.
  - Bob has a known red 4 in his hand on slot 5.
  - Alice clues number 5 to Bob, touching a 5 on slot 3.
  - Bob knows that he is *Loaded*, because he has a red 4 to play. Bob knows that normally, no-one else is supposed to give *Save Clues* to *Loaded* players (and that they should be transformed into *Play Clues*).
  - However, Bob knows that this rule doesn't apply to number 5 clues during the *Low Score Phase*.
  - Thus, Bob marks his slot 4 card as being *Chop Moved* and plays the red 4.
- For example, in a 3-player game (similar to the last example):
  - It is the *Low Score Phase*.
  - Red 3 is played on the stacks.
  - Bob has a known red 4 in his hand on slot 4.
  - Alice clues number 5 to Bob, touching a 5 on slot 5 (Bob's chop).
  - Bob knows that he is *Loaded*, because he has a red 4 to play. Bob knows that normally, no-one else is supposed to give *Save Clues* to *Loaded* players (and that they should be transformed into *Play Clues*).
  - However, Bob knows that this rule doesn't apply to number 5 clues during the *Low Score Phase*.
  - Thus, Bob knows that Alice is performing a simple *5 Save* and plays the red 4.
