### ISSUE TITLE
Occupied focus inversion

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-conventions#48]
Example 1)
![occupied focus inversion](https://user-images.githubusercontent.com/12693191/67507243-d1f82400-f68e-11e9-80da-6f13b599f35a.jpg)
Alice is occupied, she have a play.
Alice clue two cards in Donald's hand.
Either Bob or Cathy have no play, so they could do the same clue.

Why Alice did that? Cause the clue should not be interpreted normally.
So if this clue could be a save, it's an occupied play clue.
If this clue couldn't be a save, it's an occupied focus inversion : Alice shouldn't play the focus of the clue, but the other card.

**Comment by NoMercyO** [comment]
Interesting idea. I like it. 2 thoughts.

1) Wording clarify for situations with 3 cards from 'other' to the 'next card' (it should be implied that this means left most for chop focuses clues, and 2nd left most for left focused clues.

2) My main concern is to caution against out cases where Romain's playable is not globally known.
This is the same issue that plagues priority and a common intermediate mistake.

**Comment by alercah** [comment]
I'm confused. Who's Alice in this example? What other card? There's only one card clued.

**Comment by NoMercyO** [comment]
Romain is Alice with a yellow 1 to play. 
Instead of playing y1 Romain clues yellow to asaelr. 

The fact that both are yellow is not related here. What is important is asaelr sees no reason why Romain should give this clue instead of play knowing Kakashi could give the clue instead.

**Comment by Zamiell** [comment]
seems fine

**Comment by Romain672** [comment]
![occupied focus inversion 2](https://user-images.githubusercontent.com/12693191/67574858-8e0f2880-f73b-11e9-8cac-398f3d1dc64c.jpg)
I have a known r4 and a known b3 (b5 finesse).
Asaelr know it was a finesse since i have a b3.
I can clue 3 to Valetta.

**Comment by alercah** [comment]
Would this also work to change focus on, say, a clue that hits slots 2 and 3? Or only clues that would normally target chop?

**Comment by NoMercyO** [comment]
Some further thoughts:

Is it illegal if Romain's b3 IS a blind play?
 - as yet undefined as you could arrange the priority of conventions as you want, but most likely no, it would still be allowed. Asaelr can see the clue to Valetta works as a OPC focus inversion and considers that the intended outcome (as opposed to a stacked finesse for his b3 and g2). This is a good point for debate though.

Is it illegal if Romains b3 is blind and the focus inversion is on asaelr?
- almost certainly yes. Asaelr will be unable to untangle whether the b3 is gotten and the clue is a focus inversion vs the b3 was ambiguous and the clue is a normal clue to him. As he is not in a position to reasonably entertain both options, one must be prescribed as illegal to prevent confusion and/or bad tempo.

**Comment by NoMercyO** [comment]
Actually, the more i look at it the more i seem inclined to agree with Romain's comment that the conflict with Bluff is too much to ignore. 

Option a) Allow OPC Focus inversion to take priority over bluffs and finesses. So IF the player is ever occupied and gives a bluff or finesse, IF the second touched card is playable you must assume as such.

Option b) OPC focus inversion requires that both the focus and inversion card are the same suit. Thus from good touch principle the bluff interpretation is illogical. 

I think i prefer B. It is certainly the smaller change, i think it's the better one (but not sure).

**Comment by Romain672** [comment]
So does Option a) allow finesse on the focus inversion? Like on the second example change all the 3 into 4 in Valetta's hand, and change g4 into y2.

Does option a) allow bluff? Change all the 3 into 4 in Valetta's hand, add a purple suit with 3 played, and remplace g4 by p4 (or hard bluff, remplace g4 by k1).

**Comment by Romain672** [comment]
> Would this also work to change focus on, say, a clue that hits slots 2 and 3? Or only clues that would normally target chop?

Yes, I was searching for an example of that.
But most of the (limit or bad) example I found are in early game, so you can generally just make a player not occupied do the clue with color, or wait that the card arrive on chop. So (I think) for the clue to be worth it, you really want something extra, like an useless card on the player after you who could give the same clue, or an usefull and not critical card on the player who receive the clue.

**Comment by Romain672** [comment]
![focus inversion 3](https://user-images.githubusercontent.com/12693191/67619637-37b6ee00-f7fe-11e9-991c-3efed60eb7d9.jpg)
Floriman clue green to Valetta.
Honza clue purple to Valetta.
Valetta clue red to Romain excepting my next move.
Romain clue red to Floriman.

Not sure it's the best line, but it's a good one who use that convention and who aren't on chop.

**Comment by Zamiell** [comment]
> I have a known r4 and a known b3 (b5 finesse).
> Asaelr know it was a finesse since i have a b3.
> I can clue 3 to Valetta.

This conflicts with the move called the *Occupied Finesse*.
Currently, the way that we play is if Romain clues 3's to Valetta, Valetta should blind-play her *Finesse Position* as a *Occupied Known Self-Finesse* (meaning red 2 into red 3 or green 2 into green 3).

Is the intent to delete this kind of *Occupied Finesse* and replace it with *Focus Inversion*? If yes, then I don't currently feel that is a very good configuration. *Occupied Finesse* are more efficient than *Focus Inversion*. And they are quite common too!

Thus, I think that this convention **should only be allowed with color**. (Is this more or less what Mercy is saying in his option B above?)

> Is it illegal if Romain's b3 IS a blind play?

**I think it should be illegal if Romain has any kind of blind-play to do.** Otherwise it looks like an *Ambiguous Finesse*, etc. As an aside, one of the most infuriating things is when players tell me in a post-game review that they did not blind-play into a *Finesse* because they were trying to perform a *Priority Finesse* instead. And trying to do *Focus Inversion* instead of blind-playing into a *Finesse* is more of the same bullshit.

> Would this also work to change focus on, say, a clue that hits slots 2 and 3? Or only clues that would normally target chop?

Yes. How *Focus Inversion* works is that, in a clue where slots 2 and 3 are hit, if slot 2 was normally the focus, then it would invert to slot 3 (and vice versa).

**Comment by NoMercyO** [comment]
It's partially what I was saying for b), but not exactly.

In multicolor variants color clues on that touch different colored cards (eg a rainbow and yellow card) are still not allowed. 
Only in situations where finesse or bluff are not possible is is allowed. This includes
a) color clues on cards of the same color so focus inversion is self evident from good touch
b) number (or rarely color) clues where the clue focus is known trash after focus inversion occurs.

**Comment by Zamiell** [comment]
ok we so agree that normal OPC interpretations should take priority over OFI
and we agree that color clues on cards of the same color is a clear OFI

```
number (or rarely color) clues where the clue focus is known trash after focus inversion occurs.
```
can you type out an alice and bob story where Alice uses a number clue to initiate OFI and it does not conflict with OPC

**Comment by NoMercyO** [comment]
Example 1: Mid game of a rainbow 6 suit game, 4 players.
- All 1s have been played, all 2s have been played except the b2. 
- Alice has a playable r4. Bob has nothing to do. 
- Cathy's hand is [X m2 b2 X] all unclued. Her hand has been static pretty much all game. 
- Alice invokes OFI and clues Cathy 2s. She sees a b3 in Donalds hand and doesnt want to lose tempo on the blue suit, waiting/hoping for Cathy to finally discard. She also feels the r4 playing right now is pretty irrelevant and OFI is much clearer than trying to invoke a stale 2s context read.

This is the 'trash example' which relies on the fact that the clue can never be a finesse or bluff, simply because the conventional clue focused card will never be playable. Note that my example is more contrived than necessary. So long as the focused 2 is trash everyone except Cathy knows the clue is OFI. And Cathy knows the clue is unusual in some way due to Alice giving it over Bob, with OFI being the best logical conclusion.

Example 2: No variant 5 suit 4 player. Board played is b1 r3 y0 g1 p0
- Alice has r4 to play again. It is globally known. 
- Bob has nothing to do. Her hand has a y5 saved with yellow (5CE) and 3 unknown cards that are negative yellow cards.
- Cathy's hand is [y3 b3 X X].
- Donalds hand is also void of interest.
- Alice clues 3s to Cathy. Due to the unique nature of both Bob's hand's negative infomation he is able to rule out any chance that this clue is intended to focus on the y3 and so It must be OFI. Cathy sees that Alice's choice to clue her was strange when Bob could. OPC is irrelevant again as the clue is never a save. There are no finesse or reverse finesse options. Only OFI remains, and Cathys plays the b3. 
Donald Sees Cathy play the wrong 3 and is suprised. He had marked his hand for y1 and y2 after Alice's original clue. He checks to see if there is context that the b3 played from good touch principle and cannot see anything simple. Thus he assumes the clue is OFI and discards instead of playing slot 1.

**Comment by Zamiell** [comment]
are you okay with leaving the number case undocumented since it is so rare

**Comment by Zamiell** [comment]
actually i guess we can just word it such that "OFI only applies if it is impossible to be a more-ordinary OPC or an occupied finesse"

**Comment by Romain672** [comment]
One game, three screen.
Scharkbite have a nice y2+y4 we want to get, unfortunately, k2 is blocking the clue.


Example 3)
![OFI - 3](https://user-images.githubusercontent.com/12693191/68168915-b2a0a700-ff6a-11e9-8e1b-56b3b95cfbbe.jpg)
I suppose it didn't work, since I can't do the clue myself because i have y1, it seem for me logical to consider it a yellow clue now would mean to play y4.

Example 4) one turn later
![OFI - 4](https://user-images.githubusercontent.com/12693191/68169037-090de580-ff6b-11e9-9787-ae644a2c5672.jpg)
Now it's my turn, and again, I don't think the clue would trigger the OFI, because asaelr perhaps consider his chop less usefull than mine, so he want me to clue that y2 in slot 5.

Example 5) five turn later
![OFI - 5](https://user-images.githubusercontent.com/12693191/68169040-0c08d600-ff6b-11e9-8208-18a9daa5cc50.jpg)
Now again, there is a finesse on g2+g3+g4 working. But I have no play. Asaelr have a play, and Scharkbite know Asaelr have a play.
So it should trigger here.
(but again, you was not fan about delaying blind plays, even if it's one turn later)

**Comment by NoMercyO** [comment]
I assume at all points the OFI clue you are referring to in your example above is yellow. If so i agree with your evaluation with a few comments
- The upside to the clue never seems huge here. At best it saves a y4 which is unique, bu also the least valuable card in scharkbite's hand. 
- There is no risk here of the 'blind play delay' violation because:
     a) Primarily the 2 is touched. Good touch principle protects us knowing which g2 is called. there is no ambiguous prompt conventions.
     b) practically in 3 player you are almost always safe from ambiguous clues. in this case scharkbite 100% knows his g4, and noone else exists to think they have g2 and/or g3. 

So i agree the clue works here exactly as you describe (and only at the end

**Comment by Zamiell** [comment]
> Example 3)
> I suppose it didn't work, since I can't do the clue myself because i have y1, it seem for me logical to consider it a yellow clue now would mean to play y4.

* normally it looks like a save on y2, which you have to do before playing the y1
* however, shark will save the b2, so a save on y2 is unnecessary
* so it probably still works as OFI

> Example 4) one turn later
> Now it's my turn, and again, I don't think the clue would trigger the OFI, because asaelr perhaps consider his chop less usefull than mine, so he want me to clue that y2 in slot 5.

* I think it would trigger OFI for the same reasons as in example 3
* it is very bad teamwork for asaelr to make you get the y2, i think that is absurd and players can not entertain that possibility

**Comment by Zamiell** [comment]
**Occupied Focus Inversion**

* Normally, when a player is *Occupied* and they give a clue to someone else, it signifies one of the following three situations:
  1) They are giving a *Chop Focus* clue to the next person as an urgent *Play Clue* or *Save Clue* before it gets discarded.
  2) They are giving a clue that would normally look like a *Save Clue* with the intent to transform it into a *Play Clue* (as an *Occupied Play Clue*).
  3) They are giving a clue that would normally look like a 1-for-1 *Play Clue* with the intent to transform it into a 2-for-1 *Self-Finesse* (as an *Occupied Self-Finesse*).
* If none of the above situations apply and an *Occupied* player gives a *Play Clue* that touches two or more brand new cards, then they must be trying to communicate something additional.
* In this situation, they are trying to communicate that the focus of the clue should be inverted. The *Play Clue* is either on the left-most card (if it would normally be *Chop Focus*) or on the right-most card (if it would normally be the left-most card).
* For example, in a 4-player game:
  * It is the first turn and nothing is played on the stacks.
  * Alice clues red to Cathy, touching a red 1 as a *Play Clue*. Cathy now has a globally known red 1.
  * Bob discards, implying that there is nothing to do.
  * Instead of playing her red 1, Cathy clues red to Donald, touching a red 3 on slot 1 and a red 2 on slot 2. This must be a *Play Clue*, since these cards are not on Donald's chop.
  * Donald knows that since Cathy is not playing her red 1 and giving a clue, she must have a good reason.
  * Donald also knows that this cannot be a *Self Finesse* or *Self Bluff*. (*Self Bluffs* with color are explicitly illegal.)
  * This must be an *Occupied Focus Inversion*, so Donald marks his right-most card as red 2 for later and discards.

**Comment by Romain672** [comment]
Seem fine.
You didn't inclued a 3 card clue with like r3-r2-r5-x in Donald's hand because we got no example of it?

**Comment by Romain672** [comment]
But we are in early game on your example.
So when Bob discard he said to the team there is no play clue to give.
So when Cathy clue Donald, it should be focus inversion because of focus inversion convention and not because of occupied focus inversion convention, right?

**Comment by jakestiles** [comment]
In your example, Bob can neither clue 3 to Donald as a self finesse nor 2 to Donald as a play clue? If we’re saying both these things hold, it might be worth specifying Donald’s exact hand that caused this to be possible.

**Comment by Zamiell** [comment]
> So when Cathy clue Donald, it should be focus inversion because of focus inversion convention and not because of occupied focus inversion convention, right?

yes i will rewrite the example

**Comment by Romain672** [comment]
@jakestiles I will wait to have an example of it with 3 cards, for seeing what we can do with it.
Perhaps it's too complicated.

**Comment by Romain672** [comment]
If you change the action of Bob by something else unrelated (clueing a color on a 1 or clueing 5 as a save clue) it should be fine Zamiell.

**Comment by Zamiell** [comment]
oh ok

**Comment by Zamiell** [comment]
what about this:

> Bob clues 5 to Alice as a 5 Save.

**Comment by Romain672** [comment]
Mmm...
Do you prefer perfect example or clear example?

Because I still see two problems :
 - Bob didn't clue r2. It could be blocked. Perhaps he planne an OFI, but it stay strange
 - Bob didn't clue 3 to Donald as a finesse. I suppose Donald is in bluff seat so is either forced to save Alice's 5 and assume a finesse | or trust Bob that Alice will have something to do on her turn.

**Comment by Zamiell** [comment]
you can write a new example?

**Comment by Romain672** [comment]
> 
> 
> **Occupied Focus Inversion**
> 
>     * Normally, when a player is _Occupied_ and they give a clue to someone else, it signifies one of the following three situations:
>       
>       1. They are giving a _Chop Focus_ clue to the next person as an urgent _Play Clue_ or _Save Clue_ before it gets discarded.
>       2. They are giving a clue that would normally look like a _Save Clue_ with the intent to transform it into a _Play Clue_ (as an _Occupied Play Clue_).
>       3. They are giving a clue that would normally look like a 1-for-1 _Play Clue_ with the intent to transform it into a 2-for-1 _Self-Finesse_ (as an _Occupied Self-Finesse_).
> 
>     * If none of the above situations apply and an _Occupied_ player gives a _Play Clue_ that touches two or more brand new cards, then they must be trying to communicate something extra.
> 
>     * In this situation, they are trying to communicate that the focus of the clue should be inverted. The _Play Clue_ is either on the left-most card (if it would normally be _Chop Focus_) or on the right-most card (if it would normally be the left-most card).
> 
>     * For example, in a 4-player game:
>       
>       * It is the first turn and nothing is played on the stacks.
>       * Alice clues red to Cathy, touching a red 1 as a _Play Clue_. Cathy now has a globally known red 1.
**>       * Bob clues blue on b1 to Alice as a play.
>       * Instead of playing her red 1, Cathy clues red to Donald, touching a red 3 on slot 2 and a red 2 on slot 3. This must be a _Play Clue_, since these cards are not on Donald's chop.**
>       * Donald knows that since Cathy is not playing her red 1 and giving a clue, she must have a good reason.
>       * Donald also knows that this cannot be a _Self Finesse_ or _Self Bluff_. (_Self Bluffs_ with color are explicitly illegal.)
>       * This must be an _Occupied Focus Inversion_, so Donald marks his right-most card as red 2 for later and discards.

**Comment by Zamiell** [comment]
ok i updated the example, you can re-check it

**Comment by jakestiles** [comment]
If it’s a red 4 or 5 instead of r3, does it become OOO or does it work exactly the same way?

**Comment by Zamiell** [comment]
it would be OOO

**Comment by jakestiles** [comment]
So that means not only does r2 get marked, r3 should be marked and playable as well. I feel like that should be mentioned.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Zamiell** [comment]
OFI only applies as a last resort
in general, that is typically how we implement new conventions, e.g. that they only apply if it can't be one of our existing conventions

**Comment by Zamiell** [comment]
> So that means not only does r2 get marked, r3 should be marked and playable as well. 

no, the r3 could be r5, its not a double play clue, its only focus inversion

**Comment by Zamiell** [comment]
i've edited the above example to clarify

**Comment by jakestiles** [comment]
So if it was r4 or r5, it would be OOO? If Cathy sees no r3 on other people’s finesse, Cathy can rule out r4 or r5 and mark r3?

**Comment by Zamiell** [comment]
i dont understand your question. how could it be a finesse on red 3 if nobody has the red 2

**Comment by Zamiell** [comment]
why dont you type up an alice and bob story

**Comment by jakestiles** [comment]
Here’s my updated story:

This must be an Occupied Focus Inversion, so Donald marks his right-most card as red 2 for later. Furthermore, if the other red card in his hand is red 4 or red 5 then this is a OOO finesse calling for r3 (and maybe r4). If Donald sees no r3 on finesse position, Donald can also immediately mark their other red card as r3. Donald discards.

**Comment by Zamiell** [comment]
no, thats not how it works

**Comment by Zamiell** [comment]
i added the following to the above example, which was implied before but is now explicit:

>  * Donald looks around the table and does not see the red 2 in anybody else's *Finesse Position*. Thus, this cannot be a *Selfish Finesse*.

**Comment by Zamiell** [comment]
additionally, see #97

**Comment by jakestiles** [comment]
So you’re saying Donald has to entertain leftmost r5 and rightmost r2? Even though Donald knows Alice and Bob would interpret this as a OOO finesse and would be promised r3+r4 which Donald knows they don’t have.

**Comment by Zamiell** [comment]
oh i see what you are saying

**Comment by Zamiell** [comment]
> it would be OOO
> OFI only applies as a last resort

i think what i said above is wrong,
OFI must takes priority over OOO in the case where the occupied player is the one initiating the OOO. (otherwise i guess OFI wouldn't exist at all and it would always be OOO)

**Comment by Romain672** [comment]
Example 6)
Brown Up & Down, so brown on chop is a play clue.
![OFI brown](https://user-images.githubusercontent.com/12693191/68548993-7dc1a380-03f3-11ea-8e03-5e14af71397e.jpg)

**Comment by Zamiell** [comment]
i added the following to the above example:

> * *Occupied Focus Inversion* takes precedence over an *Out-of-Order Finesse*. (This follows from *Occam's Razor*; if it could just be a normal *Focus Inversion* play clue, then it does not necessarily promise any blind-plays.)
