### ISSUE TITLE
Convention Proposal: Extension to disease bluff

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#52]
![](https://cdn.discordapp.com/attachments/238379117794426881/636949212994600972/2019-10-24_0826.png)
We've had discussions where color self-bluffs are illegal and will not be considered positional clues.  However, I feel they may work as a extension of disease double bluff.  

Romain here can see that there is no R1 so he blind plays finesse position as a known bluff.  B2 plays. 
Jeff see's that Romain played.  The only explanation is that he's patching into R1.  Jeff will play his finesse position and should be expecting a B3.  G1 plays.  Since the clue got 2 unrelated cards to play it meets the definition of double bluff and immediately resolve.

**Comment by aliblong** [comment]
A more succinct description of this is: "we disallow color self-bluffs, but enable color self-double-bluffs".

**Comment by jakestiles** [comment]
I like this more than translating self color bluffs to positional.

**Comment by Zamiell** [comment]
* probabilistically, it is much more likely for one playable card to be in finesse position than two playable cards in a row.
* thus, it follows that you would want to configure self-bluffs with color for single bluffs instead of double bluffs.
* if self-bluffs with color were good, then i think that we would have already done this

so im not seeing the logic behind continuing to ban them for single bluffs but instead making it so that it is required to be a double bluff every time.

**Comment by Dr-Kakashi** [comment]
Well the logic is that Romain plays a card that's unrelated to the clue.  The only explanation is that he's patching.  In a situation that you're explaining where it's only 1 playable card, how does Jeff know it isn't a patch?  He doesn't, so he'll just misplay.  Additionally, to self bluff to only get 1 card is just....nonsense when you can just spend that 1 clue to directly pick up that card either directly or through our other conventions.  That's why something like this should get at least 2 cards to even be worthwhile.

**Comment by Zamiell** [comment]
> Additionally, to self bluff to only get 1 card is just....nonsense when you can just spend that 1 clue to directly pick up that card either directly or through our other conventions. That's why something like this should get at least 2 cards to even be worthwhile.

i agree with that

**Comment by Zamiell** [comment]
in the past, i've repeatedly seen mistakes where players misinterpreted a clue of this style as a *Self Bluff with Color* (and misplayed their finesse position card). in fact, it has happened **so often** that i decided to **explicitly write a section in the document to try and prevent this mistake from ever occurring again**: https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#self-bluffs-with-color-clues-illegal

given that misinterpretations of this nature have happened in the past (due to the fault of players not knowing that self-bluffs with color were expressly illegal), i notice that if clues of this style **were** legal, then the misplays would have occurred in exactly the same fashion

thus, we have to weight the benefit of this convention versus the complexity cost + the cost of it getting misplays or not working. i remain unconvinced that the benefit is worth the cost

**Comment by Zamiell** [comment]
https://cdn.discordapp.com/attachments/456214043351580674/639205676362760222/Out_of_position_bluff.jpg

this proposal would make the following OOP (yellow to the yellow 4) in the following screenshot not work

**Comment by Dr-Kakashi** [comment]
You've brought up a good point on OOP.  I didn't consider that.  I don't really see a way to distinguish the two and I'm pretty sure other players would agree that OOP is much more valuable than this convention proposal.
