### ISSUE TITLE
Convention Proposal: Reverse 5 Color Ejection

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#55]
![2019-10-20_0523](https://user-images.githubusercontent.com/48993588/67511174-28dc0a00-f64b-11e9-98e9-928f1ee285d7.png)

I believe this is the only way a Reverse 5 Color Ejection can be done and it's good enough to consider to add to the doc. 

Dr_Kakashi can give green to Sucubis.
Sucubis has to respect that it's G2 and will be forced to do something else.
Jeff can see that the intention of the clue is a 5CE and will immediately eject. 
Jeff can also reason that Sucubis did not play G5 as G1 because Sucubis thinks he has G2.  The only way Sucubis can reason that is because Jeff has G1 on finesse position and/or layered in. 

Thus this is a potential 3 for 1 clue.  

Worse Case Scenario:
Suppose that someone has W2.  Sucubis will clue the W2 as a play clue to finesse the W1 into the W2.  Stacking a 2nd finesse onto the original finesse.  
Jeff will still eject.  Which will surprise Sucubis as we are not allowed to jump ahead in this manner and must play our finesse's in order.  
Because Jeff ejected, Sucubis will immediately know that Dr_Kakashi's initial clue was a 5CE
The purpose of explaining this is to show that a fix never needs to be given.

**Comment by aliblong** [comment]
> Sucubis has to respect that it's G2
Well... no, because 3/g to romain exists. Remove that from the equation and there's still a problem: romain *knows* it's g2, and clues g3 in your hand. If this gets implemented as a convention, sucubis has to know that he can have g5, which is a) increase in complexity, and b) reduction in specificity.

Just as a general comment that applies to most/all of the issues you've posted today, we should not make conventions with such narrow application space. I guarantee they are not worth the complexity and corresponding failure rate.

**Comment by alercah** [comment]
This breaks Good Touch Principle. There's nothing to stop Sucubis from giving a clue that also gets the w1, causing a giant problem.

**Comment by Zamiell** [comment]
> We are not allowed to skip ahead in our layers. Sucubis should assume the G1 is gotten and maybe he'll even not touch iamwhohahaha's hand because he may have G1 himself. The logic is that stacking a finesse would cut off the route of information on whether or not he has G1 or G2. In the cases where he does it, it would definitely strike it as strange for iam to just eject afterwards.

ok I think that you do you understand what good lie principle is.
From the doc, *Good Lie Principle* states that:
"good lies almost always reveal themselves on the very next turn."
In the example in the OP, the very next turn is Sucubus' turn. as you say, he is "forced to do something", which presumably means give some clue. After that, it is iams turn. Before iam can even take an action, *Good Lie Principle* has already been violated, because the lie did not resolve on the very next turn.

> we should not make conventions with such narrow application space

indeed, it is probably worth formalizing this somewhere
