### ISSUE TITLE
Convention Proposal: Brown Positional Clues

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#56]
![2019-10-24_1004](https://user-images.githubusercontent.com/48993588/67511784-77d66f00-f64c-11e9-8b4c-12fa8d969676.png)

I'm not quite sure how to propose this, but I will explain what I feel should be interpreted as a positional clue.

Jeff's hand was previously locked with a 2 save.  Jeff thus knows that this is not G2.
Jeff also received a browns clue earlier letting him know that slot 5 is either N2 or N5.
Because jeff can see that there are no playable 1's in scharkbite's finesse position.  He can reason that the clue is a positional clue telling him which slot is N2.  2 in this case means slot 2 and blue means slot 3.

Scharkbite can see that Dr_Kakashi gave a play clue on the 2. 
However, scharkbite can also see that blue could've been given to tell him that he has B1.
Scharkbite has to reason that Dr_Kakashi is not allowed to hard burn. 
Does the clue meet minimum clue value principle?  
1. Is this a cm move?  It is not.
2. Does it get at least 1 card to play.  It does not
3. Does this clue prevent a possible discard. No
Since he can reason that the clue does not meet minimum clue value principle.  He has to play finesse position. 

In a situation where Jeff is not holding B5, then scharkbite will just reason it's a play clue on the 2 and play finesse positional normally.

When Jeff plays the indicated slot for no other reason.  Scharkbite will not go on to continue playing his finesse position and will stop.

I believe it's possible to extend this convention to other variants besides Brown.  So I'm not asking this to be a strictly Brown convention.  Though, if determined to be, then so be it.

**Comment by Dr-Kakashi** [comment]
Now that I think about it....is this Form 2 in this proposal:
[https://github.com/Zamiell/hanabi-conventions/issues/58](url)

**Comment by aliblong** [comment]
Follows from existing conventions, and therefore is not a new convention.

**Comment by Zamiell** [comment]
the link is broken

**Comment by Zamiell** [comment]
> Positional clues on brown cards is definitely already being used in practice

i have not seen it being used in practice, do you have any game ids

**Comment by Zamiell** [comment]
**Brown Positional Clues**

* This convention only applies to variants with a brown suit.
* In some situations, a player may have multiple brown cards in their hand. If the next brown card to play is not the oldest card, it can be difficult to "get" it to play.
* In cases where a number clue is given that has no other conventional interpretation, it is an indication to the player with two or more brown cards of which slot to play.
* For example, in a 3-player game:
  * All of the 2's are played.
  * Bob has four brown cards clued with a brown color clue on slots 2, 3, 4, and 5.
  * Alice clues Bob number 2, touching a blue 2 on his slot 1.
  * Bob knows that since all of the 2's are already played, whatever 2 this is must be a trash 2.
  * Bob also knows that this cannot be a *Trash Chop Move*, a *Trash Push*, or any of the other trash moves.
  * Bob instead interprets this as a *Brown Positional Clue*, and plays his slot 2 card.

**Comment by iamwhoiamhahaha** [comment]
![positional clue for brown suit 1](https://user-images.githubusercontent.com/50160641/68095016-f9e25580-fee0-11e9-807c-f27602107117.png)

![positional clue for brown suit 2](https://user-images.githubusercontent.com/50160641/68095018-fd75dc80-fee0-11e9-8341-f6fe5e2e74ec.png)
