### ISSUE TITLE
The Missing Link Finesse

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#59]
![2019-10-23_0126_(7_for_1_finesse_where_lie_resolves_itself)](https://user-images.githubusercontent.com/48993588/67520653-17e8c400-f65e-11e9-87cf-7101d5edee60.png)

For the first turn, Kyle clue's 4s to Dr_Kakashi to initiate a G4 finesse.
Dr_Kakashi plays G1 
Sucubis Plays R1 then G2
Dr_Kakashi will then look for G3 and plays R2.  Demonstrating to the team that G3 is not in their hands.
Dr_Kakashi will then play B1 and the finesse heals itself immediately, since he now knows that he too doesn't have G3

**Comment by NoMercyO** [comment]
I dont like it. In a larger player count this is too prone to unsuspecting players, all of whom have a marked g3, stomping on the channel of infomation to reveal the delayed bluff.

In your example given 4s is a 7 for 1 clue with a modest chance of a bomb (duplicated b1s) and thus worth giving as a clue in this unique situation.

**Comment by aliblong** [comment]
It's not clear what you're proposing here. Conventionally, this is adequately described as a lie that gets 7 cards (assuming Sucubis doesn't respect a patch finesse of this magnitude, which is probably a correct assumption). We have too many conventions as is, so let's not try to add a new one for every imaginable high-efficiency lie.

**Comment by Dr-Kakashi** [comment]
Conflict with Patch Finesse and potential stomping is enough of a reason.

The reasoning that we have too many conventions is not.  That follows the whole if it ain't broke don't fix it mentality.  The conventions are constantly changing and adapted to improve efficiency and gameplay.  Sometimes new conventions are proposed that become widely accepted, 5CE for example.

**Comment by sjdrodge** [comment]
This response seems to me to be deeply confused. The reason @aliblong is giving for rejecting this proposal is that it is neither specific enough nor generalizable enough to warrant a convention, as it would already be a lie that you could try at the table. If we tried to codify every single possible high-efficiency clue that breaks the rules, it would result in a large number of new conventions of very limited utility. This objection does not apply to 5CE since that proposes a completely new meaning for a clue that could not be reasonably attempted at the table without the existence of the convention.

**Comment by alercah** [comment]
This breaks *Good Lie Principle* and not in a good way. There are only a few situations where we entertain *Good Lie Principle* violations, and with good reason. While *Layered Finesse*s are one of them, because usually they are worth the value even with the occasional need for a fix, there's a key difference. With a *Layered Finesse*, everyone except for the player with the layers has a pretty good idea of what's going on, which helps to limit the damage that a *Good Lie* violation can do. By contrast, with this clue, *nobody* knows what's going on until Dr Kakashi plays except for the clue-giver. In particular, Sucubis would now not be allowed to clue red or blue cards without risking the need for a fix. Where one player is subject to this restriction and has stuff to do anyway, that's not so bad. Where everyone is subject to this restriction, it's awful.

**Comment by Zamiell** [comment]
interestingly, i've actually done this move myself in a 3 player game and have had it work (maybe even twice). iirc raz was the person i lied to, and we started laughing in discord once he played his final card and it wasn't it.
i dont think this move would work in a 4 or 5 player game though, due to the nature of the lie being much better contained in a 3-player game.

anyways, the move is rare enough (one in 1000 games?) that giving a name to it and putting it in the doc would not provide very much value. for it to work correctly, all players really need to know about is how layered finesses work, and thats about it.

**Comment by Zamiell** [comment]
I did this move again yesterday, so it looks to be common enough to add to the doc in level 5:

**The Purge Bluff (Layered Bluff)**

```
* This convention only applies to 3-player games.
* Sometimes, a player will have a fully playable hand from left to right. In this situation, players will normally try to perform a *Layered Finesse* in order to get all of the cards in the most efficient manner. However, a *Layered Finesse* may not always be available.
* In extremely rare situations, it is possible to orchestrate a lie in which the player with the fully playable hand thinks that they are *Layered Finessed* when they really do not have the connecting card. After they play their final card and it is not the matching card, they will know that they were *Purge Bluffed* and that nobody has the missing card.
* Care has to be taken that the player who is not *Purge Bluffed* will understand what is going on. For example, they might think that a *Patch Finesse* is happening. Thus, *Purge Bluffs* can only be done in expert games where there is no other possible interpretation for what is happening.
```

**Comment by aliblong** [comment]
Can you explain why this convention has been accepted? Before your comment 15 minutes ago, the last discussion was two weeks ago with everyone else voting it down.

**Comment by aliblong** [comment]
Also, I can't re-open the issue.

**Comment by Zamiell** [comment]
to be clear, this thread is not really a proposal. it is more of a discussion of whether or not we want to document an existing move that is rarely performed in our group. i've personally done this move several times in the past, and I did it again yesterday. but of course a case could be made either way for whether or not it is actually rare enough to be included in the "level 5 rarely used" section. if you feel strongly that it is too rare to bother including in the "level 5 rarely used" section, then I can delete it, as I do not have strong feelings on the matter either way.

**Comment by aliblong** [comment]
Regardless of how I feel about this particular proposal, I feel strongly that we should not have someone unilaterally /accept-ing a proposal before the group has, as your bot says, "reached a consensus", which has very clearly *not* happened in this case.

**Comment by aliblong** [comment]
I am in favour of closing this and opening a new issue with the thing that *you* are proposing.

**Comment by Zamiell** [comment]
ok
