### ISSUE TITLE
New Main Document Proposal: Contextual Document

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#60]
Not sure if it's feasible, but it would be nice to have a Contextual Document added to the Main Documents.  Just like the Reference Document, we can have it separated into levels.  Maybe even have the levels correspond to the levels of the Reference Document to include contextual situations and/or exceptions to our conventions. 

For example we can start it off with something basic. 

2P Scenario
Cards played on the stack: Y2

Alice discards saying that there are no playable cards and/or cards to clue
Bob Discards Chop.  P4 is discarded.
Alice then clues a yellow card on slot 3
Bob should find this strange as she could've clued this yellow card as a play clue when it was on slot 2.  Since she discarded previously, she's saying this yellow card isn't playable.  The simplest explanation is that this yellow card is trash and Alice is using this card to chop move slot 4 and 5.  
Bob discards the yellow card and it reveals itself to be Y1

This sort of falls in line with why a 1 would be "stale."  This would be an example of a stale color clue.

A good next layer of the onion for this is for Bob to see what he discarded.  
Cards played on the stack: Y2 G4

Alice discards saying that there are no playable cards and/or cards to clue
Bob Discards Chop. Y1 is discarded.
Alice clues Bob yellow touching a card on slot 2
Now Bob can reason that this newly clued yellow card is Y3 because he discarded a blocking Y1 card.  Maybe he can further reason that he wasn't given 3's as he may have a G3 in hand.  He could potentially have both R3's.

Another Context Read:
3P
Cards played on the stack: R1

Alice clues 2 to Bob as a 2 save.
Bob can look at the replay and see that this 2 was on finesse position, while Cathy was holding R3.
Alice has plenty of clues at that time, but decides to discard.
Bob can safely reason that this 2 is not R2

For the advanced section:
It could list my Potential Conflict with 5CE Exception, if it is indeed deemed to be an exception to the exception.
[https://github.com/Zamiell/hanabi-conventions/issues/57](url)

**Comment by Dr-Kakashi** [comment]
Context Suggestion:
Pink 1 Context
If a player has a single 1 in their hand and no other pink cards, it's better to give 1 as it gives both negative 1 and negative pink to the other cards in their hand.

**Comment by Zamiell** [comment]
isn't it pretty hard to explain context?

back when the group first started doing *Focus Inversion* clues, we played on keldon.net, and this was the days before the in-game replay feature was coded. so believe it or not, we had no way to rewind the game state and check to see whether or not a card was actually "stale" or not. Sometimes, a clue would be so strange that we would focus invert just by pure instinct (because we could not examine any particular turn). This was the beginnings of "context" - just a feeling that something was off.

I feel like there may not be a way to short-cut that feeling. You just have to play 100's of games under your subconscious knows what is a normal clue and what is a irregular clue.

If you think a "context guide" would be a helpful and interesting read for a beginner, you are welcome to give it a shot. You would have to be careful that it doesn't get bogged down in details, or get really technical, or be too dry, etc.

**Comment by Zamiell** [comment]
closing this since kakashi isn't responding
/idle
