### ISSUE TITLE
5CE and Prompts

### ISSUE THREAD

**Issue by alercah** [Zamiell/hanabi-conventions#85]
It's currently unclear if 5CE continues to apply where there are *Prompts* involved. I think it should, as long as Bob has to make two *blind* plays---so a *Prompt + Finesse* to Bob cannot invoke 5CE, but a *Prompt + Double Finesse* can.

If we retain the *Reverse Finesse* exception (see #84), there is the additional question of how to clarify that exception with respect to *Prompts*. Is it the location of the first *blind* play that decides whether or not the exception applies, or the first play period? Stephen's view was that it should be the first play.

**Comment by NoMercyO** [comment]
There is no doubt some room for different interpretations here. 

Lets start by clarifying that we are considering a prompt as a clue that gets a previously touched card that's identity was not already globally known to play. 

Unfortunately the issue is the strength of a prompt various based on the variant and the amount of previously known information on the card.

Two examples: b1 on stack.
1) Bob's hand:
b? X b? b? , (with chop being b2/3 from a previous bluff.)

2) X X 3?(or pink) b?(or multi)

When Blue is thus given to a b5 it seems absurd to suggest Bob should play his slot 2 X in example 1. In example two however it is much less obvious that [b4 X b3 b2] is the most logical hand configuration to assume. 

I think an optimal convention would somehow consider prompted cards as a fraction of a finesse card, perhaps even a variable percent of a finesse card depending on the previous identity state of the card. 
Of course this is an absurd conventions for humans. 

Thus really we are left with two* choices.
1) All prompt cards have zero weight.
2) All prompt cards have equal weight to finesse cards

I believe 1 is preferable to 2, agreeing with alercah.

**Comment by Zamiell** [comment]
i was under the impression that the group was already playing with 1

**Comment by Zamiell** [comment]
and the way the doc is written already implies 1

**Comment by alercah** [comment]
The doc doesn't mention the possibility of *Prompts* at all, and I think it should at the least be clarified that it applies even in the case of, say, a *Prompt + Double Finesse*.

**Comment by Zamiell** [comment]
I added the following to the doc:

>  *Prompts* don't factor into the "two or more blind plays" rule. Players only count the number of blind-plays.
