### ISSUE TITLE
4's Double Ejection

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-conventions#87]
Alice clue blue to Donald.
There is no blue card on finesse position.
.
Situation 1 : no blue card are played.
If it's (equal the focus of the clue) b1, Bob can discard.
If it's b2 or b3, it's a finesse or bluff : Bob play slot 1.
If it's b5 : it's a 5ce, Bob play slot 2.
If it's b4 and Cathy have a playable or a one away card in finesse position, Bob assume a double bluff and play slot 1.
**If it's b4 and Cathy haven't that, Bob assume b1+b2+b3+x, which is weird.
If it's b3+b3 : it's weird, either Bob have b1+b2, and it's a fine clue, or either it's not, but then, it should require two blinds play from Bob.
Same with b4+b4.**
.
Situation 2 : b1 is played.
focus b2 : nothing
focus b3 : play slot 1
focus b5 : play slot 2
focus b4 with Cathy finesse position playable or one away : play slot 1 as a double bluff
**focus b4 without Cathy finesse position playable or one away : assuming b2+b3 which is two blind cards**
focus b1 : unkown trash ejection : play slot 3
focus leftmost : b1+b2 or b1+b3 or b1+b4 or b1+b5 : (old slot 2) now slot 3
focus leftmost : b1+b1 : (old slot 2) now slot 3

**Comment by Romain672** [comment]
Yes and yes.
That's why I put that here, it's assuming 3 blind plays.

**Comment by Romain672** [comment]
Problem is that slot 2 is for 5ce.
So I feel like the old slot 2 should be slot 3 and the old slot 3 should be slot 4.

**Comment by Zamiell** [comment]
> focus leftmost : b1+b1 : I think it should be slot 3 or slot 4, but I feel like it's actually slot 3.

1+ months ago, this **used** to be UTD (slot 3) before UTE (slot 2) got changed to UTD (slot 3).
**now** it is still UTD (slot 3), but just a normal-ish "lie" clue that violates good touch principle. (the team may need to give a fix clue to the 2nd blue 1 at some point, or maybe not, depending on what happens, e.g. maybe all the other blue cards become visible without any clues having to be given)

**Comment by Zamiell** [comment]
> Yes and yes.
> That's why I put that here, it's assuming 3 blind plays.

so what exactly are you proposing, that we change the meaning of assuming b1+b2+b3? to what?

**Comment by Zamiell** [comment]
> Problem is that slot 2 is for 5ce.
> So I feel like the old slot 2 should be slot 3 and the old slot 3 should be slot 4.

we could have remapped it in the following way:
* UTE (slot 2) --> UTD (slot 3) 
* and UTD (slot 3) --> UTZ (slot 4)

however, we chose **not** to do this. instead, we chose to just **delete** the old UTD entirely, because it had never been used in 1000+ games, so it is not worth the cost of putting it in the document and memorizing this interpretation

**Comment by Romain672** [comment]
And same thing, on the other post about 5ce, there is many discussions about assuming 2/3 blind plays.
So if you want to push that to normal finesse, blue to b4 while b1 is played should be different.

Don't think it's good, but wanted to point that/discuss that.

**Comment by Romain672** [comment]
Done.

**Comment by Zamiell** [comment]
> Actually, we have nothing to get slot 3 on a color who have nothing played.

that is correct. hypothetically, if you desperately needed to have such a thing, you could make a 4 color discharge (4CD).

speculation:

the likely formulation of it would be that:
1) it uses the same "2 or more blind-plays" rule that 5CE does
2) double bluffs take priority over it (e.g. you have to look at the next guy's finesse position). 

but consider that:
2a) some double bluffs wouldn't work anymore, e.g. if bob's blind-play leads into cathy's blind-play
2b) it adds a good amount of complexity with bob having to look ahead to see if the next guy has a playable card (that does not match the color)

and also consider that:
3) 5CE is extremely powerful because it gets a 2-for-1 on a 5, and then you don't have to 5 save that 5.
4) 4's are **the worst card** and we don't want to even touch them at all most of the time

so this convention is not very good

**Comment by Romain672** [comment]
> 2a) some double bluffs wouldn't work anymore, e.g. if bob's blind-play leads into cathy's blind-play

For me, it should be considered as a double bluff anyway. So it would not work with ~40% of clue (more if there is prompted card).

**Comment by Zamiell** [comment]
> And same thing, on the other post about 5ce, there is many discussions about assuming 2/3 blind plays.
> So if you want to push that to normal finesse, blue to b4 while b1 is played should be different (and no b2/b3 in finesse position and no double bluff possible).

* an important component of all of this is that **4's suck**. if 4's were good, we would already have a *4 Bluff* convention or something like that for the same reason that we have a *3 Bluff* convention: it would allow for more 2-for-1 clues to be given and higher overall efficiency
* right now, if we clue a 4 (without nothing played), it is as minimum a 3-for-1 clue.
* **this is key** - 4's are so bad that **2-for-1's on them are bad** but **3-for-1s on them are good**.

> Else can this be a double ejection for slot 2 for both Bob and Cathy?

ok so that is interesting. you could configure it as follows:
* if bob does not see a playable card on cathy's *Finesse Position* **but** bob sees a playable card on cathy's *Second Finesse Position*, then bob ejects and cathy ejects

**Comment by Zamiell** [comment]
You could call this *4's Color Double Ejection* (4CDE). To be more specific:

* No cards are played on the stacks.
* Alice clues Donald red, touching a red 4 as a *Play Clue*.
* Bob uses the "2+ blind-plays from my own hand rule":
  * No-one on the team has any other red cards.
  * For this to be a *Finesse*, Bob would have to play red 1, red 2, and red 3.
  * So it from the rule he knows that this is not a *Finesse*.
* Bob sees that Cathy has a blue 2 in her *Finesse Position*.
* If Bob played blue 1 into blue 2, this could be a *4's Double Bluff*.
* Bob plays his *Finesse Position* as a known *4's Double Bluff*.

And in the counterfactual:

* Bob sees that Cathy has a blue 3 in her *Finesse Position*.
* Since nothing that Bob could blind-play would make the blue 3 playable, Bob knows that this cannot be a *4's Double Bluff*.
* Bob sees that Cathy has a blue 1 in her *Second Finesse Position*.
* Thus, Bob knows that this must *4's Double Ejection*.
* Bob blind-plays his *Second Finesse Position* and it is a red 1. (Donald now thinks that his red card must be the red 5, since Alice did a *5's Color Ejection*.)
* Cathy blind-plays her *Second Finesse Position* and it is a blue 1. (Donald now thinks that his red card must be the red 4, since Alice did a *4's Color Double Ejection*.)

This all sounds fine and dandy except  am skeptical of real-world applicability and value. I would need to see several game states / screenshots that demonstrate that this would be the best move for the situation.

**Comment by Romain672** [comment]
Problem with that convention is the fact you can generally already get 1 card out of 2 with a color clue on a 5.
So this move is : +1card played, -1five clued, +1four clued, which isn't too great.

**Comment by Zamiell** [comment]
that only holds true *if* there is an available, unclued 5 to use for 5CE

**Comment by iamwhoiamhahaha** [comment]
i remember i had proposed a 4 double ejection (with rank clue) few months ago, not sure if it could work now

**Comment by Zamiell** [comment]
in this formulation, it seems to work with either rank or color

**Comment by hanabirnoob** [comment]
Would 4 double discharge work as well or would it conflict with unknown trash discharge?

**Comment by Zamiell** [comment]
this convention would require the algorithm where you have to look at next person's finesse position in order to determine the correct card to play

ith the clarification of 5CE>TripleBluff, it seems like the group is moving away from this algorithm, so that is a strike against

**Comment by Zamiell** [comment]
> 4DE would require the algorithm where you have to look at next person's finesse position in order to determine the correct card to play

unless anyone else feels strongly, i think we should reject 4DE due for this reason

**Comment by iamwhoiamhahaha** [comment]
![double ejection example](https://user-images.githubusercontent.com/50160641/69005411-e4e3d880-095c-11ea-9769-3926132cc47d.png)

If IAMJEFF blind-plays slot 1, then Floriman would probably misplay blue 1 (trash) from slot 1.
If IAMJEFF blind-plays slot 2, and if Floriman blind-plays nothing, then Valetta would mark her red card as a red 5.
In this case, both IAMJEFF and Floriman should blind-play slot 2 as a 4 Double Ejection.
