### ISSUE TITLE
5CE with number 5 - 5NE

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-conventions#92]
So it would not anymore be a 5 COLOR ejection.

Would be mainly used on variant where you can't clue some color : white, light pink, etc...

.

Alice clue Cathy's w5 with number 5.
Could be a 5 save if it's on chop.
Could be a 5 chop move if it's one away from chop.
Could be a 5 stall on specific circonstances (early game, dda, locked hand, 8 clues)
Could be a normal 5 pull.
Could be a 5 pull one away from playable so you need to play your finesse position.
(Could be a bad 5 chop move if it chop move a 1, so we need to decide which convention have priority.)
Could be a big finesse.

If now, none of these possibility are likely, we actually assume a big finesse in theory. Why not adding an extra 5CE with number 5 but only either on suits where you can't color it (and perhaps, OR because the color was blocked because of the card on chop or one card who are before the 5)(and perhaps if there is no other 5CE available)?

**Comment by iamwhoiamhahaha** [comment]
It conflicts with Junk Ejection (with a 5), Double 5 Pull and 5 Pull Ejection

**Comment by Zamiell** [comment]
* you could configure D5P to have higher priority than 5NE (which i think is the correct configuration). if configured that way, then there is no conflict.
* it doesn't "conflict" with delete junk ejection, 5NE by definition is just a more generic implementation of junk ejection, so that isn't a problem. in other words, a chop move on any useful card at all would take precedence over both a 5NE and a *Finesse*, so the chop card would necessarily have to be trash if anything special happened.
* it does conflict with 5PE, but I have not seen a **single** 5PE yet, so i dont think the move is very valuable to have. maybe jeff feels otherwise

**Comment by Zamiell** [comment]
so the proposal would be something like the following:

1) Delete Junk Ejection with 5's
2) Delete 5 Pull Ejection
3) Add 5NE with the stipulation that:
  * 5CM > 5NE
  * 5Pull >5NE
  * 5DPull > 5NE

**Comment by Zamiell** [comment]
i like this formulation a lot better than having 5PE turned on tbh

**Comment by iamwhoiamhahaha** [comment]
Recently, I got some ideas about changing 5 Pull Ejection to some other types of moves. Deleting the current 5PE is fine and I will propose the new form of 5PE later.

**Comment by Zamiell** [comment]
ok so here's an important thing:
with the other convention proposal, 5 pull ejection gets deleted for 5 pull discharge.
so if number 5 is discharge in the early game and ejection in the mid-game, then i kind of hate that, so we need to come up with a more streamlined approach

**Comment by Zamiell** [comment]
Ok, let's consolidate the options here.

**Option 1: *5 Pull Discharge***

- The current convention of *5 Pull Ejection* is deleted. (It is deleted in all options.)
- A *5 Pull* on a 2-away-from-playable card OR a trash card = *5 Pull Discharge*
- *5 Pull Discharges* are only "turned on" in the *Early Game* (because that is when *5 Pulls* are turned on).

**Pros**:
- In general, *Discharges* are overall most useful in the opening hards / *Early Game*, so it makes sense to add another *Discharge* for this time period.
- We already have the ability to do a 2-for-1 clue to get slot 2 (5CE). Now, we will get the ability to do a 2-for-1 clue to get slot 3 (5PD), which has the potential to give us a lot of flexibility.

**Option 2: *5's Number Ejection***

- The current convention of *5 Pull Ejection* is deleted. (It is deleted in all options.)
- The current convention of *Junk Ejection with 5's* is deleted. (This is in order to simplify things, since it is rarely used and it could conflict with this.)
- If a clue is **not** a *5 Save* and **not** a *5's Chop Move* and **not** a *5 Pull* and **not** a *5 Double Pull*, then a number 5 clue must be a *Finesse*.
- If you would have to play **two or more blind-plays from your own hand** to fulfill the *Finesse* (e.g. same logic/rules as 5CE), then it is a *5's Number Ejection* instead.
- *5's Number Ejection* is turned on in **both** the *Early Game* and the *Mid Game*.

**Pros**:
- 5NE is turned on throughout the game, whereas 5PE is only turned on in the *Early Game*, so 5NE might be more useful overall.
- The concept of 5NE is pretty consistent with 5CE, which is nice.

**Option 3: Both** (BAD)

- We could also turn both on, but I hate this and propose that we do **not** consider this option.
- Recently, we simplified 5CE to **always** call for slot 2 instead of conditionally slot 2 or slot 3. I think that doing this **really helped a lot** to simplify things and reduce mistakes.
- If we turn on both 5PE and 5NE, it would be similar to the old situation with 5CE, because a number 5 clue would be either an *Ejection* or a *Discharge* depending on the state of the game, and that is confusing. Let's just pick one or the other.

**Comment by aliblong** [comment]
Option 4:
* Delete Junk Ejection with 5's
* Delete 5 Pull Ejection
* Now you can finesse the whole white/light pink suit at the extremely marginal cost of losing YAE (yet another ejection).

**Comment by Zamiell** [comment]
That is kind of tangential, since
a) the conventions in general need not be optimized for those suits specifically
b) if white or light pink is a problem, you can always extend *White Compromise*

**Comment by NoMercyO** [comment]
Option 1: Seems fine. Agree with logic that discharge in the early game is at its most useful.

Option 2: Unless im mistaken is missing another specification: "If a 5s color ejection was not possible it is 5NE, otherwise it is a full finesse always". Regardless i think this convention is too complex in evaluation to be safe to use. Reducing big 3-1s and 4-1s for more 2-1s is probably good, but this is doubtful to add much more. 

Option 3: You could always make 5NE 5 Number Discharge to avoid the issue. I dont believe discharge in the mid game is very useful though so i am against this. 

Option 4: Libster's point is sound that this is pretty minor.

All that said i vote option 1 > 4 > 2 > 3

**Comment by aliblong** [comment]
Option 1 looks okay, but we shouldn't use the "pull" terminology when it's not actually pulling (playing the card to its right). Just call it 5 discharge?

**Comment by fpvandoorn** [comment]
I'm fine with either option 1 or 4.

If we choose option 1 then it should be mentioned that 5 discharges are off (in easy variants) when the only other legal clues are 2 saves or finesse-position 1-or-1s, similar to `2 Saves (Advanced Section; Interaction With 5's Chop Moves / 5 Pulls)`.

**Comment by Zamiell** [comment]
> shouldn't use the "pull" terminology when it's not actually pulling (playing the card to its right). Just call it 5 discharge?

seems fine

**Comment by Zamiell** [comment]
**5 Pull Ejection* (deleted)

```
* *5 Pull Ejection is deleted* in favor of *5 Number Discharge*.
```

**5 Number Discharge** (by Jeff)

```
* This convention only applies in the *Early Game*.
* In the *Early Game*, if a number 5 clue is performed on a 5 that is not already on chop, then it is a *Play Clue* on the 5 (if there are any 5's that are directly playable).
* If there are no directly playable 5's, then the clue is instead a *5 Stall*.
* If a *5 Stall* is not allowed, then it is a *5's Chop Move* (if the card is one-away-from-chop) or a *5 Pull* (if the card is two or more away from chop).
* If a *5 Pull* is performed on a card that is one-away-from-playable, it typically communicates a *5 Pull Finesse*.
* However, if the *5 Pulled* card is two or more away from playable **or** the *5 Pulled* card is trash, then the clue must instead be a *Play Clue* on the 5 as a *Finesse*.
* If the very next player sees that they will only have to **blind-play one card** in their hand to fulfill the *Finesse*, then they should assume that it is a *Finesse* and blind-play their *Finesse Position*.
* If the very next player sees that they would have to **blind-play two or more cards** in their hand to fulfill the *Finesse*, then a *Finesse* is unlikely. Instead, players agree that this signals an *Discharge* and that the next player should play their *Third Finesse Position*.
  * *Prompts* don't factor into the "two or more blind-plays" rule. Players only count the number of blind-plays.
* For example, in a 3-player game:
  * It is the first turn and nothing is played on the stacks.
  * Alice clues number 5 to Cathy, touching a 5 on slot 1.
  * Cathy hand is as follows: red 5, red 2, red 3, green 1, green 2
  * Bob sees that Alice's clue cannot be a *5 Stall* or a *5 Pull*. If it were a *Finesse* on the red 5, he would have to blind-play a red 1 and a red 4.
  * Since Bob would have to blind-play two cards into the *Finesse*, he knows that he should instead treat this as a *5 Number Discharge*. Bob blind-plays his slot 3 card and it successfully plays as the red 1.
```
