### ISSUE TITLE
The Purge Bluff (Layered Bluff)

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#96]
i've done 2-3 of these now and just did one recently (successfully). it might be worth putting a small entry in the doc in "level 5 rarely used"

**The Purge Bluff (Layered Bluff)**

* This convention only applies to 3-player games.
* Sometimes, a player will have a fully playable hand from left to right. In this situation, players will normally try to perform a *Layered Finesse* in order to get all of the cards in the most efficient manner. However, a *Layered Finesse* may not always be available.
* In extremely rare situations, it is possible to orchestrate a lie in which the player with the fully playable hand thinks that they are *Layered Finessed* when they really do not have the connecting card. After they play their final card and it is not the matching card, they will know that they were *Purge Bluffed* and that nobody has the missing card.
* Care has to be taken that the other player (e.g. the player who is not *Purge Bluffed*) will understand what is going on. For example, they might think that a *Patch Finesse* is happening. Thus, *Purge Bluffs* can only be done in expert games where there is no other possible interpretation for what is happening.

**Comment by alercah** [comment]
I've seen this attempted before, but never successfully. I believe that it could work with advanced players, but I think more discussion is needed as to why this ordinarily this can't happen:

> Alice sees that Bob has a fully playable hand. She can't initiate a *Purge Bluff* to him, though, because after seeing that his first card doesn't match, he will simply assume it was a regular *Bluff*.
> 
> Alice sees that Cathy has a fully playable hand. She gives a clue to Bob to initiate the play. Bob does not see the matching card anywhere in Cathy's hand, so he thinks he has it on *Finesse Position*. He wants to *Pass Bluff* to make Cathy play, but cannot, because he is in *Bluff Seat*.

If we add this convention, however, then just like in a *Patch Finesse* situation, Bob has to see the possibility of a *Purge Bluff* and pass. Cathy will then assume that she has the missing card unless Bob *actually* has it on *Finesse Position*, and perform the *Purge Bluff* in full, before finally being exposed to the lie. If Bob does have the actual card, *Cathy* will read it as an *Ambiguous Finesse* and still play.

I am not sure how this could be mistaken for a *Patch Finesse* in a 3-player game. Bob is in *Bluff Seat*, so he would simply misplay. He wouldn't wait for Cathy to potentially patch his card (again, since *Pass Bluff*s cannot be made from *Bluff Seat*).

However, in a four-player game, this mistake *can* get made:

> Alice sees that Cathy has a fully playable hand. She clues Bob's y3 to initiate a *Purge Bluff*. Bob passes. Cathy blind-plays. What does Donald do? Cathy's play could have been a patch to Donald, in which case Donald should start blind-playing to find y2. Or it could be a *Purge Bluff* in which case he passes and lets Cathy play out.

I can see three possible resolutions:

1. *Purge Bluffs* take priority over *Patch Finesses*. In this case, Donald would not play at all.
2. *Patch Finesses* take priority over *Purge Bluffs*. This would mean that you can only *Purge Bluff* the player to your right, *unless* there is something that prevents it from being a *Patch Finesse* (for instance, if Cathy's first play were b1 and b2 were already touched, Donald would know it can't be a patch to b2).
3. You can only ever *Purge Bluff* the player to your right, even if other information can eliminate the possibility of a *Patch Finesse*.

I think the second option is far too headspacey. And I'd say that *Purge Bluffs* are quite powerful, so there's definitely a case for them always taking priority.

One other issue: I think there should be a minimum value for a *Purge Bluff*. Otherwise, anything could look like a *Purge Bluff* if Cathy only has one unclued card. A good rule to experiment with might be "at most one unclued card"? So minimum 4 cards in 3-player or 3 cards in 4 or 5.

**Comment by Zamiell** [comment]
> If we add this convention, however, then just like in a Patch Finesse situation, Bob has to see the possibility of a Purge Bluff and pass.

No. Adding this to the doc does not change any existing conventions, it just documents an existing move.

**Comment by Zamiell** [comment]
> I am not sure how this could be mistaken for a Patch Finesse in a 3-player game. Bob is in Bluff Seat, so he would simply misplay. He wouldn't wait for Cathy to potentially patch his card (again, since Pass Bluffs cannot be made from Bluff Seat).

Bob wouldn't misplay if Bob has full information on his entire hand

**Comment by alercah** [comment]
> No. Adding this to the doc does not change any existing conventions, it just documents an existing move.

I don't understand how this follows as legal at all, unless Bob has enough information to know his entire hand is unplayable.

> Bob wouldn't misplay if Bob has full information on his entire hand

If Bob knows no card is playable, it can't be a *Patch Finesse* though.

**Comment by Zamiell** [comment]
in an arbitrary game state where Cathy knows that Bob is trying to play into a Layered Finesse and Cathy knows that she does not have the Layered Finesse target, then Cathy knows that a Purge Bluff is occurring and will just let it happen

you can construct many such arbitrary game states, but that is left as an exercise to the reader. i dont intend to include an example in the doc passage nor do i think an example is necessary, as the move is purely for expert players who already deeply understand all of the necessary mechanics involved.

**Comment by alercah** [comment]
But you can't Purge Bluff Bob because it looks like a normal bluff?

I'm opposed to putting this in the doc if it is only intended to document a read/fringe play, rather than actually getting the work required to make it a proper convention.

**Comment by Dr-Kakashi** [comment]
Sometimes you can look at someone's hand and realize that more cards can be played if you don't play.

**Comment by Zamiell** [comment]
you are talking about the move called the *Pass Bluff*, which is unrelated to a *Purge Bluff*

**Comment by Dr-Kakashi** [comment]
Ah, sorry about that.  Thanks for the clarification

**Comment by Zamiell** [comment]
> rather than actually getting the work required to make it a proper convention.

im not sure what that really means.

to be clear, the doc is meant to be a reflection of how we play.
thus, if players in our group do a move at a frequency of more than 1/250~ games, the move should probably be documented in the doc, because that is what the doc is for, to document all the moves

the doc doesn't need to document a move if it is rare enough though. but obviously the whole point of me opening this issue is because i believe this move could pass the threshold

**Comment by Dr-Kakashi** [comment]
I've done it several times myself....which is why I made the proposal...We've deleted dump truck and I feel this is a way to get someone's entire hand without a misplay occurring.  Shouldn't the team realize that it's best to lie to a player to get their entire hand to play?

**Comment by Zamiell** [comment]
> Shouldn't the team realize that it's best to lie to a player to get their entire hand to play?

i think you may misunderstand what the point of this issue is, as "realizing lies" is not really related.
at the risk of repeating myself,

> Adding this to the doc does not change any existing conventions, it just documents an existing move.

**Comment by Dr-Kakashi** [comment]
Right, sorry I'm having trouble putting things into words.  The main proposal is that there isn't a matching card anywhere.  What I'm talking about is having the matching card but not playing it, so it's completely unrelated to this.  In any case, the original post has a screen shot of this proposal.  I'm sure there are more screen shots, since you've encountered them yourself.  It looks like having examples helps with explaining things....I'll keep that in mind on future proposals.

**Comment by Zamiell** [comment]
![image](https://user-images.githubusercontent.com/5511220/69208243-df36f000-0b20-11ea-881c-b54b5bbeeba4.png)

green to mice

**Comment by alercah** [comment]
Ah! I hadn't thought about where it was on top of another finesse or prompt. This makes a lot more sense, though I still think that there's no reason to limit it to three-player games.

I think more discussion of the circumstances where it's permitted would be good, rather than simply saying that other interpretations must be impossible, but I am satisfied now that this is worth adding.

**Comment by Dr-Kakashi** [comment]
![2019-11-21_0950](https://user-images.githubusercontent.com/48993588/69363048-8e201c80-0c44-11ea-8e76-9bed2ea2eee4.png)

Complicated Purge Bluff.  The idea was to have kopen clue 5's to get R5 to play before R4.  I would do a blue fix on kopen and deal with Y4 when we finally get there.

**Comment by Dr-Kakashi** [comment]
![2019-11-25_0405](https://user-images.githubusercontent.com/48993588/69539232-ed2dac00-0f38-11ea-91be-67382cddd6ac.png)
I've done a few purge bluffs lately...but thought this was the most simple one to interpret

**Comment by Zamiell** [comment]
valetta bombs y1 as y3 in this line

**Comment by alercah** [comment]
@Zamiell I think you still haven't explained why this is only for three player games?

**Comment by Zamiell** [comment]
you could technically do a purge bluff in a 4 player game but that chances of that happening are even more remote than the chances of a purge bluff happening in a 3 player game
